### ISSUE TITLE
unexplained "undefined variable"

### ISSUE THREAD

**Issue by ratel223** [ashinn/chibi-scheme#1001]
Hi,

Using both 0.11 and master from 2024-09-17 on Debian based distro MX Linux x86_64 with kernel 6.1.0-25-amd64 on AMD A8-7600.

This code

    (let loop ((i 0))
      (unless (= i 5)
        (display i) (newline)
        (loop (+ i 1))))

produces this error

chibi-scheme named-let-test.scm
ERROR on line 3 of file named-let-test.scm: undefined variable: i
  called from <anonymous> on line 1268 of file /usr/local/share/chibi/init-7.scm
  called from <anonymous> on line 800 of file /usr/local/share/chibi/init-7.scm
Searching for modules exporting i ...
... none found.

Between the two tests, I uninstalled the previous version. I also tried from the build directory after uninstalling. I see this with larger programs also. Other Scheme interpreters run the code without complaining.

What am I missing?

Thanks.

**Comment by ashinn** [comment]
There is a default language for the repl, but for scripts you need to be explicit.

You can either add `(import (scheme base) (scheme write))` at the top of the script, or run `chibi-scheme -xscheme.base -mscheme.write named-let-test.scm`.

Added a warning for this.

**Comment by ratel223** [comment]
Thank you.
