### ISSUE TITLE
snow-chibi package leaves out files

### ISSUE THREAD

**Issue by Retropikzel** [ashinn/chibi-scheme#1002]
Command:
`snow-chibi package foo/bar.sld`

in a directory with files:
foo/bar.sld
<pre>
(define-library
  (foo bar)
  (import (scheme base))
  (export hello)
  (begin (include "bar.scm")))
</pre>

foo/bar.scm:
<pre>
(define hello
  (lambda ()
    (display "Hello")
    (newline)))
</pre>

VERSION:
<pre>
0.1.0
</pre>

and ~/.snow/config:
<pre>
((command
   (package
     (authors "Retropikzel <retropikzel@iki.fi")
     (doc-from-scribble #f)
     (version-file "VERSION"))))
</pre>

Produces foo-bar-0.1.0.tgz with files:
foo-bar-0.1.0/
foo-bar-0.1.0/foo/
foo-bar-0.1.0/foo/bar.sld
foo-bar-0.1.0/package.scm

**Comment by ashinn** [comment]
You want

`(include "bar.scm")`

not

`(begin (include "bar.scm"))`

The packager only looks at the static library language, not the contents of the Scheme code.
