### ISSUE TITLE
Existence of srfi/151.sld in module search directory gives errors 

### ISSUE THREAD

**Issue by Retropikzel** [ashinn/chibi-scheme#1012]
If srfi/151.sld exists in module search path then Chibi gives errors when run.

<pre>
retropikzel@rm-aio:/tmp/chibitest$ chibi-scheme -V
chibi-scheme 0.11.0 "sodium" (chibi chibi-0.11.0 r7rs ratios complex mini-float uvector threads full-unicode modules dynamic-loading linux x86_64 little-endian)
</pre>

Simplest way to reproduce:

<pre>
mkdir srfi
touch srfi/151.sld
chibi-scheme -I .
</pre>

Error from that is:
`ERROR on line 720 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm: write-string: not an output-port: #f`

I stumbled upon this working on making the SRFI-151 reference implementation portable and testing it.

To reproduce with code:

<pre>
mkdir srfi
cd srfi
wget https://github.com/srfi-explorations/r7rs-srfi/raw/105a2667b44bbecbaa71957b7b4232608d2c249f/srfi/151.sld https://github.com/srfi-explorations/r7rs-srfi/raw/105a2667b44bbecbaa71957b7b4232608d2c249f/srfi/bitwise-33.scm https://github.com/srfi-explorations/r7rs-srfi/raw/105a2667b44bbecbaa71957b7b4232608d2c249f/srfi/bitwise-60.scm https://github.com/srfi-explorations/r7rs-srfi/raw/105a2667b44bbecbaa71957b7b4232608d2c249f/srfi/bitwise-core.scm https://github.com/srfi-explorations/r7rs-srfi/raw/105a2667b44bbecbaa71957b7b4232608d2c249f/srfi/bitwise-other.scm
cd ..
chibi-scheme -I .
</pre>

I tested that on isolation, but for some reason the error message when running the r7rs-srfi projects test commands is different. So I'm including steps to reproduce that too.

<pre>
git clone https://github.com/srfi-explorations/r7rs-srfi.git
cd r7rs-srfi
git checkout 105a266
git clone https://github.com/srfi-explorations/srfi-test.git
cd srfi-test
git checkout 65e7735
cd ..
make -C srfi-test # Need to have Gauche installed for this to work
make test-srfi-64-chibi
</pre>

Since this one is more tedious to reproduce I'll add the whole error message here:

<pre>
WARNING: exception inside module with no imports - did you forget to (import (scheme base)) in: (scheme base)
ERROR: module attempted to reference itself while loading: (scheme base)
  called from <anonymous> on line 211 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 1191 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 804 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from error on line 108 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 83 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 804 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from call-with-current-continuation on line 827 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 195 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 251 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 279 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 83 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 83 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 259 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 251 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 279 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 82 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 82 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 259 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 251 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 279 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 81 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 81 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 259 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 250 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 279 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 81 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 81 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 259 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 250 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 279 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 81 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from for1 on line 81 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 259 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 250 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 437 of file /home/retropikzel/.scman/chibi/share/chibi/meta-7.scm
  called from <anonymous> on line 1268 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
  called from <anonymous> on line 800 of file /home/retropikzel/.scman/chibi/share/chibi/init-7.scm
WARNING: exception inside module with no imports - did you forget to (import (scheme base)) in: (scheme base)
</pre>

The SRFI-151 code is basically just the reference implementation and works on Chicken, Gauche (some tests fail), Kawa, Larceny, Loko, Mosh, Racket and Sagittarius. And since it contains cond-expand for Chibi I'm assuming it will work on Chibi too when it can load it.

`chibi-scheme -A .` 

is one workaround, but as I want to use other than implementations SRFIs it's no help for this case.

**Comment by ashinn** [comment]
SRFI 151 is a core library used by many modules, including those needed for the REPL.  Putting a broken implementation of it in your path will of course break things.

That said, if you at least provide a valid library definition, e.g.:

```
echo '(define-library (srfi 151))' > srfi/151.sld
```

you don't get an error but instead warnings about undefined variables (because the core does need a SRFI 151 implementation).

The confusing error you get is because it tried to output an error or warning due to the invalid module, but the standard ports are not bound until _after_ the core language is loaded (because of course it's the core language that defines those parameters).  That's not so easy to work around, so for now just understand that if you want to hack the Chibi core library then debugging is tricky.

Your other message has errors about both circular dependencies and modules without any imports, both of which are self-explanatory.  Are you actually trying to define a new version of `(scheme base)`?  That's quite difficult.

**Comment by Retropikzel** [comment]
> SRFI 151 is a core library used by many modules, including those needed for the REPL. Putting a broken implementation of it in your path will of course break things.
> 
> That said, if you at least provide a valid library definition, e.g.:
> 
> ```
> echo '(define-library (srfi 151))' > srfi/151.sld
> ``

I see. I was confused because the SRFI-151 worked on other implementations and having broken implementation in the path broke code that does not use the SRFI-151 trough imports.

So this breaks, for example:

<pre>
echo "(import (scheme base) (scheme write)) (display "Hello") (newline)" > hello.scm
mkdir srfi
touch srfi/151.sld
chibi-scheme -I . hello.scm
</pre>

> 
> you don't get an error but instead warnings about undefined variables (because the core does need a SRFI 151 implementation).
> 
> The confusing error you get is because it tried to output an error or warning due to the invalid module, but the standard ports are not bound until _after_ the core language is loaded (because of course it's the core language that defines those parameters). That's not so easy to work around, so for now just understand that if you want to hack the Chibi core library then debugging is tricky.
> 
> Your other message has errors about both circular dependencies and modules without any imports, both of which are self-explanatory. Are you actually trying to define a new version of `(scheme base)`? That's quite difficult.

I am not trying to define new version of `(scheme base)`, just making a portable version of SRFI-151. 

Thanks for your response and sorry about wasting your time. My bad.

**Comment by ashinn** [comment]
(scheme base) imports (chibi string) which imports (chibi char-set base) which imports (chibi iset base) which imports (srfi 151).  So, yes, it's expected that (srfi 151) is indirectly pulled in for your example.

The error messages are really confusing though, I'll see if I can improve them.  I'm busy lately, though, and main.c (where the order of building the initial env and standard ports etc. is) is a total mess.

**Comment by Retropikzel** [comment]
> (scheme base) imports (chibi string) which imports (chibi char-set base) which imports (chibi iset base) which imports (srfi 151). So, yes, it's expected that (srfi 151) is indirectly pulled in for your example.
> 

Thanks for the explanation. Makes sense.

> The error messages are really confusing though, I'll see if I can improve them. I'm busy lately, though, and main.c (where the order of building the initial env and standard ports etc. is) is a total mess.

I think this kind of case is propably rare. I have multiple srfi/N.sld files in same repository so having broken srfi/151.sld broke everything else too. And the proper thing to do is for me to fix the code in there. And anyone who comes accross this from now on propably will find this issue, so I would not use too much time on this.
