### ISSUE TITLE
Difficult to include Chibi libraries in other Schemes

### ISSUE THREAD

**Issue by dleslie** [ashinn/chibi-scheme#250]
This is sort of nit-picky on my part; but I love your work and I'd like to see it used with wider acceptance and greater ease.

What I have in mind is a repository for chibi libraries that have been made R7RS compliant, which is in turn a submodule of chibi-scheme. I'm willing to do the leg work of pulling the libraries out, testing them and modifying them where appropriate, and whatnot; but I'd like to do it with your approval.

Moreover, I'm not certain what the library root should be. I'd like to keep it as 'chibi', but that would conflict with the existing 'chibi' root.

**Comment by ashinn** [comment]
This is snow-fort.org.  Please wait for more documentation and libraries in the next couple of weeks.
