### ISSUE TITLE
SEGV on er-macro-transformer

### ISSUE THREAD

**Issue by ktakashi** [ashinn/chibi-scheme#252]
The following code causes SEGV.

```scheme
(import (scheme base) (scheme write) (scheme cxr) (chibi))

(define-syntax comp
  (er-macro-transformer
   (lambda (form rename compare)
     (let ((a1 (cadr form))
           (a2 (caddr form)))
       `(define-syntax do-it
          (er-macro-transformer
           (lambda (f r c)
             (define (print . args) (for-each display args) (newline))
             (let ((a1 ,(rename a1))
                   (a2 ,(rename a2)))
               (c a1 a2)) ;; SEGV
             '(begin))))))))

(let ((a 1))
  (comp a a)
  (do-it))
```

Environment:
```bash
$ chibi-scheme -V
chibi-scheme 0.7.2 "nitrogen" (chibi r7rs ratios complex threads full-unicode modules dynamic-loading linux little-endian)
```

Not directly related to this issue but I think the bindings _a1_ and _a2_ should raise unbound variable error since the macro `comp` is bound on global environment which doesn't have any binding `a` and _a_ is bound locally.

**Comment by ashinn** [comment]
This is a known limitation that macros in chibi don't close over local temporary variables.
There are complications involved with this, and it's neither widely portable nor so far as
I've seen useful, so I haven't really been interested in supporting it.

It shouldn't segfault though, I'll fix that.
