### ISSUE TITLE
snow-chibi displays poor performance with non-tiny snowballs

### ISSUE THREAD

**Issue by ilammy** [ashinn/chibi-scheme#255]
[Here is a chart of Snow's running time versus snowball size](https://docs.google.com/spreadsheets/d/1PX4RDSYqBS5aQRPjAa7lMIhMaWeypKL3UJ8sDQ8D5tc/edit?usp=sharing). It is not _that_ bad (could be quadratic), but the factor of this O(_n_) is kinda large. It takes about 2.5 minutes on Travis' VMs to install a 1.5 MB snowball. This is sad.

Running Chibi with `-h 512m` does not help very much, slightly shifing the ratio between the user and system times from 1:3 to 1:4. Anyway, we're talking about 1 MB snowballs here, even the default 32 MB should be enough.

Running Chibi under Valgrind gives the following top calls:

<table><tr><th>Time</th><th>Module</th><th>Function</th></tr>
<tr><td align="right">36.75%</td><td>vm.c</td><td>sexp_apply</td></tr>
<tr><td align="right">10.00%</td><td>gc.c</td><td>sexp_allocated_bytes</td></tr>
<tr><td align="right">6.82%</td><td>gc.c</td><td>sexp_sweep</td></tr>
<tr><td align="right">6.53%</td><td>vm.c</td><td>sexp_apply'2</td></tr>
<tr><td align="right">6.03%</td><td>gc.c</td><td>sexp_try_alloc</td></tr>
<tr><td align="right">5.24%</td><td>gc.c</td><td>sexp_finalize</td></tr>
<tr><td align="right">3.94%</td><td>(libc)</td><td>__memset_x86_64</td></tr>
<tr><td align="right">3.93%</td><td>gc.c</td><td>sexp_reset_weak_references</td></tr>
<tr><td align="right">3.31%</td><td>gc.c</td><td>sexp_alloc</td></tr>
<tr><td align="right">3.26%</td><td>sexp.c</td><td>sexp_make_vector_op</td></tr>
<tr><td align="right">2.96%</td><td>eval.c</td><td>sexp_env_cell_loc</td></tr>
<tr><td align="right">2.53%</td><td>sexp.c</td><td>sexp_alloc_tagged_aux</td></tr>
<tr><td align="right">1.75%</td><td>sexp.c</td><td>sexp_buffered_flush</td></tr>
<tr><td align="right">1.49%</td><td>io.c</td><td>sexp_feed_pipe</td></tr>
<tr><td align="right">1.33%</td><td>eval.c</td><td>sexp_make_procedure_op</td></tr>
<tr><td align="right">1.26%</td><td>sexp.c</td><td>sexp_cons_op</td></tr>
</table>

Further study of hot sites in sexp_apply() only leads to the main switch dispatcher eating 25% of user time. Does this mean that what I see is just Chibi's expected performance?.. But wait, where are those 75% of system time going then?

(Oh, right, I forgot the `--collect-systime` flag, I'll bring the updated info back in several minutes.)

After I have added that flag I see that most (80%) of the system call time is spent in gettimeofday() call in sexp_scheduler. But I can't say how reliable is this. IIRC, gettimeofdate() is forwarded via user-space so it should be fast. The next call is sexp_read_raw() with 15% which is somewhat expected.

I am not familiar with Chibi's built-in Scheme profiling tools, but I will see what I can do with them tomorrow.

**Comment by ilammy** [comment]
Well, `(chibi optimize profile)` did not help very much with time profiling itself, but it gave a helpful insight. Most of the time seems to be spent in `package-maybe-digest-mismatches`. I have added time measurements with disabled digest computation to [the chart](https://docs.google.com/spreadsheets/d/1PX4RDSYqBS5aQRPjAa7lMIhMaWeypKL3UJ8sDQ8D5tc/edit?usp=sharing). It is not as fast as I wish it were :) but with x10 speedup it is _much_ better!

First of all, I believe `package-maybe-digest-mismatches` should be as lazy as `package-maybe-signature-mismatches` is and should not compute a digest if the package does not include one for verification. (And it seems that Snow ignores the `checksums` field from [the spec](http://trac.sacrideo.us/wg/wiki/Snow), using digests from `signature` instead.)

However, this does not change the fact that digest computation is stunningly slow. Especially on 32-bit VMs used by Travis due to expected performance degradation in `(chibi crypto sha2)`. So yeah, in the end it _is_ Chibi's expected performance. Number crunching isn't its strength.

**Comment by ashinn** [comment]
snow-chibi currently takes a couple of seconds just to start up since it loads so many libraries.
I plan to address this with pre-compilation.

I hadn't encountered terrible performance for digests in part because I'm only working with small (source-only) packages, and in part because I'm on a 64-bit machine where all digest operations become fixnums.

gettimeofday() comes from the thread scheduler, where a background thread is checking to see if we should look for new leap seconds.  This is expected, and in a quick test I saw only a ~5% speedup on sha2 of a large file when disabling threads altogether.

So I'm seeing very roughly 20s to install a 270k lib, of which 15s is for sha2, 2-3s is for startup, and 2-3s is everything else snow is doing.  I'll see if there's some way I can speed up sha2 in Scheme (e.g. splitting the computations for force fixnum) but may just rewrite it in C.

**Comment by ashinn** [comment]
Closing this since we have native SHA-2 now.
