### ISSUE TITLE
snow-chibi doesn't like multiple includes of same file

### ISSUE THREAD

**Issue by WillClinger** [ashinn/chibi-scheme#266]
When I tried to create a Snow package for my three-file implementation of `(r6rs hashtables)`, I encountered this error:

```
% snow-chibi package --version=0.0.0 --doc=r6rslinks.html \
        --description="Port of (rnrs hashtables) to R7RS." \
        r6rs/hashtables.sld
tar-create: duplicate file: r6rs-hashtables-0.0.0/r6rs/hashtables.atop69.scm
tar-create: duplicate file: r6rs-hashtables-0.0.0/r6rs/hashtables.atop69.scm
tar-create: duplicate file: r6rs-hashtables-0.0.0/r6rs/hashtables.atop69.scm
tar-create: duplicate file: r6rs-hashtables-0.0.0/r6rs/hashtables.atop69.scm
tar-create: duplicate file: r6rs-hashtables-0.0.0/r6rs/hashtables.atop69.scm
tar-create: duplicate file: r6rs-hashtables-0.0.0/r6rs/hashtables.body69.scm
```

This may be harmless, but I haven't used Snow enough to become comfortable with it.

I suspect the problem is caused by multiple `include` declarations for the same file.  They're protected within mutually exclusive `cond-expand` clauses, so the file will be included at most once when the library is imported or compiled.

**Comment by ashinn** [comment]
Thanks, I've seen this before, it's not really an issue but would be good to suppress the warning.

**Comment by ashinn** [comment]
This was fixed in an earlier commit.
