### ISSUE TITLE
Steele's three-part test

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#269]
See http://www.dreamsongs.com/Files/HOPL2-Uncut.pdf (p. 79) for details.

Chibi passes the first part, which is #t => #t.  It also passes the third part, which is (atanh -2) => -0.549306144334055+1.5707963267949i, where (define (atanh z) (/ (- (log (+ 1 z)) (log (- 1 z))) 2)).

Unfortunately, it fails the second part:

$ chibi-scheme
> (define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
> (/ (fact 100) (fact 99))
100/0       ;WTF?
> (fact 100)
93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000
> (fact 99)
933262154439441526816992388562667004907159682643816214685929638952175999932299156089414639761565182862536979208272237582511852109168640000000000000000000000
> (define x (fact 100))
> (define y (fact 99))
> (/ x y)
100/0
> (+ (/ x y) 20)
Segmentation fault (core dumped)
$

$ chibi-scheme -V
chibi-scheme 0.7 "nitrogen" (chibi r7rs ratios complex threads full-unicode modules dynamic-loading cygwin little-endian)

**Comment by ashinn** [comment]
Thanks!  I had checked these tests before and they passed (at least in 0.6)
This is a regression probably related to the recent move to karatsuba and
related division optimizations.

**Comment by ashinn** [comment]
Just pushed a 1 character fix, but I need to double check against a wider range of inputs.
