### ISSUE TITLE
chibi-ffi ignoring struct type modifier

### ISSUE THREAD

**Issue by polyglotCipher** [ashinn/chibi-scheme#270]
I am attempting to use chibi-ffi to wrap a library I made in C to use in scheme. One of my functions returns a `struct my_type` type so I used `(define-c (struct my_type) func (other_type other_type))` to define it. chibi-ffi is ignoring the `struct` type modifier that is supposed to waiver the default of returning a struct pointer so when I try to compile it I get an incompatible type error in the third argument of `sexp sexp_make_cpointer (sexp ctx, sexp_uint_t type_id, void* value, sexp parent, int freep);` where in my function is not returning a `void* value`.

**Comment by ashinn** [comment]
Hi, sorry, this got lost in my mail, I'll take a look.
