### ISSUE TITLE
sort incorrect on lists of both exact and inexact numbers

### ISSUE THREAD

**Issue by kevinwortman** [ashinn/chibi-scheme#271]
The SRFI 95 sort does not seem to compare exact and inexact numbers correctly. For example, on the REPL:

> (import (srfi 95))
> (sort '(1 2 3 1.5))
(1 2 3 1.5)

This should yield '(1 1.5 2 3) .

**Comment by ashinn** [comment]
The default comparator is not < but a generic object comparator that sorts first by type.  I'm not sure I want to change that.  However, we special case (sort ls <) to use the default comparator as an optimization, so I guess it's easiest to make them agree.  Note bypassing this with:

```scheme
(sort '(1 2 3 1.5) (lambda (a b) (< a b)))
```

works.

**Comment by kevinwortman** [comment]
The default comparator behavior sounds OK, but I get the same behavior even when specifying < explicitly:

> (sort '(1 2 3 1.5) <)
(1 2 3 1.5)

It seems to me like when < is passed, the sort should obey the ordering semantics of < .

**Comment by ashinn** [comment]
Yep, that's what I said, we special case (sort ls <) to the default comparator, sorry if that wasn't clear.

This is easy to fix but I'm really busy, will get to it sometime this weekend.

**Comment by kevinwortman** [comment]
No problem, thanks!
