### ISSUE TITLE
file-position on files opened for output with open + open-output-file-descriptor not reflecting position changes after writes

### ISSUE THREAD

**Issue by tizoc** [ashinn/chibi-scheme#273]
If I open a file through `open` + `open-output-file-descriptor` (to be able to open the files in append mode), the result of calling `file-position` on the result handle is 0 every time, even though the actual position in the stream has changed because of writes.

Note that each write keeps appending to the file as expected, it is the output of `file-position` that is different from what one would expect. When the file is opened with `open-output-file`, then `file-position` behaves as expected.

Example test program:

```scheme
(import (scheme small) (chibi io) (chibi filesystem))

(define mode (+ open/create open/write open/append open/non-block))
(define fd (open "/tmp/append-test" mode))
(define out (open-output-file-descriptor fd))

(display (file-position out))
(newline)
(display "1234" out)
(display (file-position out))
(newline)
(display "5678" out)
(display (file-position out))
(newline)
(close-output-port out)
```

**Comment by tizoc** [comment]
This is with version 0.7.3 btw.

**Comment by ashinn** [comment]
Thanks for the report!  It works if you call (flush-output-port out) after each display.
It's just that it's not adding in the buffered offset.  I'll fix this soon.

**Comment by ashinn** [comment]
Sorry for the delay, I had forgotten about this.
