### ISSUE TITLE
`sexp_flush_output_op` is not defined

### ISSUE THREAD

**Issue by edw** [ashinn/chibi-scheme#275]
Attempting to compile and link this:

```c
sexp_display(ctx, result_obj, sexp_current_output_port(ctx));
```

Produces this:

```
cc -L/Users/edw/local/lib -lchibi-scheme -o ring-demo ring.o ring-demo.o
Undefined symbols for architecture x86_64:
  "_sexp_display_op", referenced from:
      _feed_ring in ring-demo.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ring-demo] Error 1
```

A quick search of the source repository reveals that sexp_display_op is indeed not defined anywhere.

**Comment by ashinn** [comment]
Yes indeed, sorry about that.  `display' is implemented in Scheme now.
I've removed the declaration.  You can use sexp_write_{char,string} and sexp_write.
