### ISSUE TITLE
SRFI-33 doesn't work in certain situation

### ISSUE THREAD

**Issue by ktakashi** [ashinn/chibi-scheme#279]
It seems SRFI 33 procedures fails in certain situation (not sure exactly which). I've created [R7RS cryptographic library](https://github.com/ktakashi/aeolus) and run on Chibi with following command:

```
$ chibi-scheme -Ilib -Itest-lib tests/test-aes.scm
```

Then, on 32 bit Cygwin all tests failed, on 64 bit Ubuntu most of them failed (some passed). The library uses SRFI-33 if exists and if I remove that part, all the tests passed.

**Comment by ashinn** [comment]
Strange, I use SRFI-33 extensively, including for the sha2 and md5 implementations.  I'll take a look.

**Comment by ktakashi** [comment]
Seems right shift isn't doing right
```scheme
(import (scheme base) (srfi 33)
	(scheme write))

(number->string (arithmetic-shift #x2b7e151628aed2a6abf7158809cf4f3c -32) 16)
;; -> 2b7e1516542ce7bcd4a5e82e

;; but must be 2b7e151628aed2a6abf71588
```
This only happens when the minus shift is 32 or 64 (maybe 32 bit boundary?)

**Comment by ashinn** [comment]
Yes, it's an off-by-one error specific to a negative multiple of word size
boundary.
Strange it never triggered.  I've fixed this, will push later.

Note test-equal in (chibi test) is not a bug, it just has different
semantics from SRFI 64.  I will rename it to test-with-equal to avoid
confusion.

**Comment by ashinn** [comment]
Fix pushed.
