### ISSUE TITLE
libchibi-scheme.so.0 not found when using a prefix build/install on Linux

### ISSUE THREAD

**Issue by mcalan** [ashinn/chibi-scheme#280]
When building/installing with PREFIX=/opt/chibi I get the following linker errors:

    $ chibi-scheme
    chibi-scheme: error while loading shared libraries: libchibi-scheme.so.0: cannot open shared object file: No such file or directory
    $ ldd /opt/chibi/bin/chibi-scheme 
	     linux-vdso.so.1 (0x00007ffd5502f000)
	     libchibi-scheme.so.0 => not found
	     libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f71b856b000)
	     /lib64/ld-linux-x86-64.so.2 (0x00007f71b8914000)
    $ ldd /opt/chibi/lib/chibi/chibi/net.so 
	     linux-vdso.so.1 (0x00007ffec7335000)
	     libchibi-scheme.so.0 => not found
	     libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f792c330000)
	     /lib64/ld-linux-x86-64.so.2 (0x00007f792c8df000)

**Comment by mcalan** [comment]
Proposed fix in pull request #281.

**Comment by ashinn** [comment]
Thanks for the report and patch!  However, this has been brought up before.  I've always used LD_LIBRARY_PATH when working with non-standard install paths.  It offers more control, avoiding hard-coding paths which could break when files are moved, or from chroot, etc.

Moreover Debian advises against using rpath: https://wiki.debian.org/RpathIssue

**Comment by mcalan** [comment]
Fair enough, as you say it's easy enough to work around with an alias. Thanks for the link it was a good read.

**Comment by cipriancraciun** [comment]
I've started a thread on the Chibi mailing list about this issue, with the subject `Regarding '-rpath' during build, or how it enables usability (and in relation with issue #280 on GitHub)`

  https://groups.google.com/d/topic/chibi-scheme/B8KpwuVOH48/discussion
