### ISSUE TITLE
No error message is printed when loading a shared object fails.

### ISSUE THREAD

**Issue by truecolour** [ashinn/chibi-scheme#282]
For example:
    
    > (load "does-not-exist.so")
    #<undef>

    > (call-with-output-file "not-an-elf.so" newline)
    > (load "not-an-elf.so")
    #<undef>

    > (load "does-not-exist.scm")
    ERROR in "open-input-file": couldn't open input file: "does-not-exist.scm"

I tested this on a 64-bit Linux system with the latest Git commit (23ac772e3ac347d01647952621fbc83b4293448b).

**Comment by truecolour** [comment]
By the way, is it possible to unload a shared object, so it can be recompiled and loaded again?

**Comment by ashinn** [comment]
Thanks!  Fixed.  The gc will unload shared objects when all references are reclaimed.
