### ISSUE TITLE
Redefinitions create a new binding instead of mutating the current one

### ISSUE THREAD

**Issue by truecolour** [ashinn/chibi-scheme#285]
R7RS specifies this (Page 26):

> ### 5.3.1. Top level definitions ###
> At the outermost level of a program, a definition
>
>     (define variable expression)
>
> has essentially the same effect as the assignment expression
>
>     (set! variable expression)
>
> if `variable` is bound to a non-syntax value. However, if
> `variable` is not bound, or is a syntactic keyword, then
> the definition will bind `variable` to a new location before
> performing the assignment, whereas it would be an error
> to perform a `set!` on an unbound variable.

However, Chibi currently does this:

    > (define x 1)
    > (define (f) x)
    > (f)
    1
    > (set! x 2) 
    > (f)
    2
    > (define x 3)
    > (f)
    2
    > x
    3

Looks like a bug to me. (Or am I misinterpreting the standard?)

**Comment by ashinn** [comment]
This was probably an incorrect resolution of: https://groups.google.com/d/msg/chibi-scheme/-am8Xrr52Hc/lcVXg49-AgAJ in commit 7c333f43dae25387f3e7071aa84e2551756d3969.

You're always going to have issues with redefinition, especially when types and syntax are involved.  Plus chibi has no option to disable inlining.  I'll have to think about what the best thing here is (though as you say I don't think the standard gives us any leeway).
