### ISSUE TITLE
Autocompletion at the repl not working with internal macro defines 

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#292]
Enter

    (define-syntax foo
      (syntax-rules ()
        ((foo) (define bar 'fred))))
    (foo)

at the `chibi-scheme -R` prompt. Typing `tab` for autocompletion now yields an error: `ERROR in "symbol->string": invalid type, expected Symbol: #<SC 140309608199360 bar>`.

**Comment by ashinn** [comment]
Sorry for the late reply, just back back from a business trip.  I had already noticed and fixed it locally, will push the fix this weekend.

**Comment by ashinn** [comment]
Actually, this was a different and simpler issue than what I was referring to.
Fixed.  Note you'll now get "bar" as a completion option, however there is no
binding for bar, just for an inaccessible syntactic closure named bar.
