### ISSUE TITLE
Lint Warnings from Xcode - NULL ptr ref, etc

### ISSUE THREAD

**Issue by cwds** [ashinn/chibi-scheme#296]
The "Analyze" feature from recent Xcode distributions has gotten quite good at performing a static analysis on C code.  The Chibi code base is remarkably clean, but there are a handful of warnings that should probably be addressed - NULL pointer, divide by zero, that sort of thing.  Simply loading up the Chibi source into Xcode and hitting Product/Analyze will show these issues, along with a fairly verbose description of why the tool thinks there is a problem at that location.

A first-pass attempt to fix up the warnings can be found under the 'issue_296' branch of the 'cwds' fork of the repository, at https://github.com/cwds/chibi-scheme, plus and related pull request to create an easy to browse diff.  The proposed fixes silence all warnings and pass the regression, but they should be reviewed and modified by the author to capture the correct intent of the code at those sections.

**Comment by ashinn** [comment]
These have been merged from your branch.
