### ISSUE TITLE
Guard does not accept a body, just a sequence of expressions

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#301]
By the R7RS, the syntax of the guard special form is `(guard (<identifier> <cond clause>*) <body>)`. However, Chibi does only support a sequence of `<expression>`s instead of a more general `<body>`:

https://github.com/ashinn/chibi-scheme/blob/master/lib/scheme/misc-macros.scm#L28

**Comment by ashinn** [comment]
Fixed in 557b31e.
