### ISSUE TITLE
Reader generates a core dump with certain datum labels

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#308]
The `(read)` procedure in `(scheme read)` crashes when presented the input:

`#125=#(#213=(1 2 #125# 4 . #213#) (#125#) #213#)`

The reader at the repl gives the following error: https://github.com/ashinn/chibi-scheme/blob/3e9092cfccbc6ee4e299fd0bf92b8e0417d177cf/sexp.c#L2874

The self-referencing datum above is from: https://github.com/larcenists/larceny/blob/master/test/R7RS/Lib/tests/scheme/read.sld#L307

**Comment by ashinn** [comment]
You need to quote the literal.  Per R7RS section 2.4, "it is an error [...] to include circular references except in literals."  Quoting it works fine.

The error in the core repl is working as intended.

**Comment by mnieper** [comment]
I actually quoted the above literal when I entered it at the repl. The session looked like this:

   $ chibi-scheme 
   > '#125=#(#213=(1 2 #125# 4 . #213#) (#125#) #213#)
   
   ERROR on line 1: reader label out of order: 125
   > ERROR on line 1: reader label out of order: 213
   > ERROR on line 1: unknown reader label: 125
   > 4
   > ERROR on line 1: unexpected '.'
   > ERROR on line 1: unknown reader label: 213
   > ERROR on line 1: too many ')'s
   > ERROR on line 1: unknown reader label: 125
   > ERROR on line 1: too many ')'s
   > ERROR on line 1: unknown reader label: 213
   > ERROR on line 1: too many ')'s
   > 

I got the core dump by feeding the quoted literal to (read) at the repl. Funnily, I don't get the errors when executing a top-level program.

**Comment by ashinn** [comment]
The default repl isn't R7RS, you need -R.  With -R there's no error.
