### ISSUE TITLE
Nested ‘define-syntax’ does not work as expected

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#311]
The program below does not work with Chibi. The identifier ‘baz’ remains unbound in the top-level-environment. (I tested the same program with Gauche, which does not exhibit the error, so displays ‘42’, which looks like the expected behaviour as defined by R7RS.)

    (import (scheme base)
	        (scheme write))
    
    (define-syntax foo
      (syntax-rules ()
        ((foo x)
         (begin
           (define-syntax bar
	     (syntax-rules ()
	       ((bar)
	        (define-syntax x
	          (syntax-rules ()
		    ((x) 42))))))
           (bar)))))
    
    (foo baz)
    
    (display (baz))
    (newline)

**Comment by ashinn** [comment]
This is the correct behavior.  If you want to prevent renaming you have to pass the identifier through every expansion:

```
(define-syntax foo
  (syntax-rules ()
    ((foo x)
     (begin
      (define-syntax bar
        (syntax-rules ()
          ((bar y) (define-syntax y (syntax-rules () ((y) 42))))))
       (bar x)))))
```
Some implementations strip renamed definitions at the top-level, but thats non-standard and has problems of its own.  It's common to want to define, e.g. "tmp" top-level variables to support things like define-record-type.  If these were stripped they'd all overwrite each other, and you couldn't have multiple define-record-types in the same scope.

**Comment by mnieper** [comment]
Got it, thanks. After thinking of how my example would be expanded in terms of the ‘er-macro-transformer’ I have to agree with you. :-)

And checked with Gauche again. Outside of top-level it does the same as Chibi.
