### ISSUE TITLE
Hygiene of SRFI-46/R7RS ellipsis

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#313]
The following program yields the error `too many ...'s`:

    (import (scheme base))

    (define-syntax foo
      (syntax-rules ... ()
        ((foo body)
         (define-syntax bar
           (syntax-rules ...1 ()
             ((bar) body))))))
    
    (foo
     (define-syntax baz
       (syntax-rules ...1 ())))

If we substitute the second occurrence of the ellipsis `...1` (in the macro-use of `foo`) be something different, e.g. `...2`, the error disappears. This smells like violation of the hygiene rules.

SRFI-46 says: 

> Specification
> 
> Syntax-rules syntax is extended so that there is an extra possible token before the literal identifier list:
> 
>       (syntax-rules [<ellipsis-identifier>] (<literal-identifier> ...)
>         (<pattern> <template>)
>         ...)
> 
> Ellipsis-identifier specifies the token used for ellipsis. It defaults to the usual R5RS1 ellipsis identifier, ..., but it can be specified to be any identifier, such as :::. This identifier's specification is considered to be a binding whose scope is the rules of the transformer. The macro system implementation must make the hygienic arrangements described in R5RS's section 4.3 to preserve the lexical scope of these bindings.

Without these hygienic arrangements, it is hard to write fool-proof macro-combinators that use the ellipsis feature.

**Comment by mnieper** [comment]
This snippet that exhibits the error is even simpler:

```
(import (scheme base))

(define-syntax foo
  (syntax-rules ... ()
    ((foo body)
     (define-syntax bar
       (syntax-rules ...1 ()
         ((bar) body))))))

(foo (a ...1))

```

My guess is that the ellipsis `...1` inside the definition of `bar` has to be bound to a fresh denotation for the lexical scope of `bar`'s syntax-rules so that it doesn't `identifier=?` with the unbound `...1` at the macro use of `foo`. (The error disappears as soon as `foo (a ...1)` is changed into something like (`let ((...1 'quux)) (foo (a ...1)))`.)

**Comment by ashinn** [comment]
Thanks!  Fixed.
