### ISSUE TITLE
`number->string` cannot output rational numbers in radix other than 10

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#317]
Does chibi's behaviour, namely that `(number->string 1/4 16)` returns `ERROR in lp on line 399 of file ./lib/init-7.scm: invalid type, expected Integer: 1/4`, agree with section 6.2.7 of R7RS?

**Comment by ashinn** [comment]
It looks ambiguous, and probably not required, but it also seems to be supported by most major implementations so chibi should too.
