### ISSUE TITLE
Improper list in macro invocation within r7rs-test.scm

### ISSUE THREAD

**Issue by shirok** [ashinn/chibi-scheme#318]
tests/r7rs-tests.scm has this entry to test macro call `part-2x`:

    (part-2x 10 (+ 21 22) (31 32) (41 42) (51 52) (+ 61 2) 77 . "tail")

Is this allowed in R7RS?   R7RS 4.3 says the macro call is in the following syntax, which doesn't seem to include improper lists:

    (<keyword> <datum> ...)

**Comment by ashinn** [comment]
Thanks!
