### ISSUE TITLE
More compiler warnings

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#321]
```
sexp.c:1970:37: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
      if (sexp_complex_imag(obj) == SEXP_NEG_ONE)
                                    ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
sexp.c:2326:25: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
      real = (c=='-') ? SEXP_NEG_ONE : SEXP_ONE;
                        ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
sexp.c:3122:36: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
            res = sexp_fx_mul(res, SEXP_NEG_ONE);
                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                                           ^
include/chibi/sexp.h:1281:87: note: expanded from macro 'sexp_fx_mul'
#define sexp_fx_mul(a, b) ((sexp)((((((sexp_sint_t)a)-SEXP_FIXNUM_TAG)*(((sexp_sint_t)b)>>SEX...
                                                                                      ^
sexp.c:3163:49: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
        res = sexp_make_complex(ctx, SEXP_ZERO, SEXP_NEG_ONE);
                                                ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
4 warnings generated.
/home/mnieper/emsdk_portable/emscripten/master/emcc -c -DSEXP_USE_STRICT_TOPLEVEL_BINDINGS=1 -DSEXP_USE_ALIGNED_BYTECODE=1 -DSEXP_USE_STATIC_LIBS=1 -Iinclude  -Wall -DSEXP_USE_DL=0 -g -g3 -O3 -O2  -o bignum.o bignum.c
bignum.c:783:58: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    q = sexp_add(ctx, q, (sexp_positivep(q) ? SEXP_ONE : SEXP_NEG_ONE));
                                                         ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
bignum.c:789:60: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
      q = sexp_add(ctx, q, (sexp_positivep(q) ? SEXP_ONE : SEXP_NEG_ONE));
                                                           ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
bignum.c:804:26: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    q = sexp_add(ctx, q, SEXP_NEG_ONE);
                         ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
bignum.c:1775:32: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
        r = f > 0 ? SEXP_ONE : SEXP_NEG_ONE;
                               ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
bignum.c:1791:32: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
        r = f > 0 ? SEXP_ONE : SEXP_NEG_ONE;
                               ^~~~~~~~~~~~
include/chibi/sexp.h:798:22: note: expanded from macro 'SEXP_NEG_ONE'
#define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
include/chibi/sexp.h:795:60: note: expanded from macro 'sexp_make_fixnum'
#define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^

```

**Comment by ashinn** [comment]
Does the emscripten compiler actually _not_ do the obvious thing for left shifting a negative signed value?  For any compiler for which this was the case, I seriously doubt chibi would work.

I will accept a patch to either suppress this warning (-Wnoshift-negative-value) or fixing through an equivalent computation that causes no performance loss (e.g. (n*2)+SEXP_FIXNUM_TAG), but the burden is on the patch maker to show the generated assembly is the same.  I will not spend any time on this myself.

**Comment by mnieper** [comment]
Emscripten's emcc uses clang to do the compilation. So the warnings probably come from clang.

**Comment by mnieper** [comment]
clang does seem to be right here. ISO C says it is undefined behaviour to left shift negative signed values. So a conforming compiler may decide to optimize away those code paths that exhibit this undefined behaviour.

https://www.securecoding.cert.org/confluence/display/c/INT34-C.+Do+not+shift+an+expression+by+a+negative+number+of+bits+or+by+greater+than+or+equal+to+the+number+of+bits+that+exist+in+the+operand

says something about it under the heading  "Noncompliant Code Example (Left Shift, Signed Type)" .

**Comment by ashinn** [comment]
Yep, I know it's clang, I was just trying to imagine a compiler where it could possibly fail.  Especially since the only left shift it's complaining about is the one with a _constant_ value, whereas it doesn't warn for any of the other left shifts of possibly negative values.

Basically, left shift of a negative value in on a twos complement architecture has the risk of overflow, where a zero gets shifted to the leftmost bit making the result positive.  But _all_ fixnum operations can potentially overflow, which is why chibi explicitly checks and avoids these cases.

Now, on a ones complement machine left shift of a negative would be broken even without overflow, unless the implementation specifically accounted for this.  Basically no ones complement machines exist anymore, but one could imagine (e.g. in javascript which has doubles but no fixnums) using a double to represent a 32-bit signed number.  Most likely even in this case it would make non-overflowing shifts behave normally, e.g. by multiplying by 2^x.

These are the cases that the C standard cares about.

This shifting behavior is used extensively throughout the code, and chibi already runs on many compilers and many platforms.  When and if a compiler comes out that breaks because of this warning I can look at it. Until then I'm far too busy.

**Comment by mnieper** [comment]
In JavaScript, the bitwise operators are fully specified, and they work as one would expect from two-complement machines (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators), so the Emscripten backend won't make any problems here.

My point was a different one: When a standard-conforming optimizing C compiler sees a construct like `a << 2` in a lexical context where `a` is of signed type, it may infer that `a` has a non-negative value and use that information for optimization purposes (like an optimizing Scheme compiler may infer that `a` denotes a pair as soon as `(car a)` is in the code path). Thus, the problem is architecture independent (e.g. whether the machine is one- or two-complement).

The reason why clang only warns about shifting a constant is most likely due to the fact that it cannot prove in the other cases that the signed value is actually negative.

As rewriting Chibi's code base in order to make it conform to the C standard seems like a huge task, it is probably best to leave everything as it is for the moment, and excepting the warning of clang as a reminder that there is still something to do.

**Comment by ashinn** [comment]
Sure, I understood your point exactly, I just think it's being paranoid.  And I think the warning is bogus, because it only warns on the cases _known_ to work, and fails to warn on the cases that might actually fail.
