### ISSUE TITLE
Documentation for defining new record types

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#323]
In http://synthcode.com/scheme/chibi/#h3_Types, the documentation seems to imply that the various procedures accept numerical indices instead of symbols to access record fields.

However, https://github.com/ashinn/chibi-scheme/blob/3dcac282ad76ea0e845d340bd2bdcea03d80e73c/lib/srfi/9.scm#L25 implies that the low-level record-type facility works with symbols instead of numerical indices.

**Comment by ashinn** [comment]
The documentation is correct.  Note that srfi/9.scm uses type-slot-offset to determine the field index.

**Comment by ashinn** [comment]
From your description I was looking at the procedures taking indices, but register-simple-type was incorrectly documented as taking a number instead of a list of field names.  Fixed, and added documentation for type-slot-offset.
