### ISSUE TITLE
(chibi modules): (containing-module +) errors

### ISSUE THREAD

**Issue by ecraven** [ashinn/chibi-scheme#326]
(import (chibi modules))
    (containing-module +)

=>

    ERROR in final-resumer: non procedure application: #<undef>

**Comment by ashinn** [comment]
Fixed, but note this is all undocumented for a reason - it's not really well supported.  Also, you can't get any lambda param names for + since it's an opcode.  The best you can get is procedure-signature from (chibi type-inference).

**Comment by ecraven** [comment]
If there's a supported way for doing this, I'd gladly use that, but I haven't been able to find one so far :-/
