### ISSUE TITLE
‘string->number’ does not detect all syntactically invalid numbers with certainty

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#327]
For example, `(string->number "1i")` returns `0+i`, not `#f`.

**Comment by ashinn** [comment]
This is valid numeric syntax.

**Comment by mnieper** [comment]
Looking on page 62 of the R7RS report, all production rules of complex numbers involving an `i` also have an explicit sign. I don't see how to produce `1i` with these rules.

(I also checked with Larceny, which does not parse `1i`.)

**Comment by ashinn** [comment]
Ah, sorry, looks like that's non-portable.  It's still not a bug.

**Comment by mnieper** [comment]
I filed the bug report because in 6.2.7 it says that `string->number` has to return `#f` when given a syntactically invalid notation for a number. 6.2.5 defines the syntax of numbers by what 7.1.1 says.

**Comment by ashinn** [comment]
Yes, but implementations are allowed to make their own extensions to the numeric syntax, and 1i is valid in chibi.
