### ISSUE TITLE
Exactness of complex numbers expressed in polar coordinates

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#329]
By section 6.2.5 of the R7RS, numerical constants that have no exactness prefix are exact if they neither contain a decimal point or an exponent. Taking this literally, `1@0` is an exact complex number.

Chibi, however, evaluates `(exact? 1@0)` to `#f`. Maybe, the indented meaning of 6.2.5 was that a numerical constant with no exactness prefix is exact if it does not contain a decimal point, an exponent _or the `@` sign_. But even if this was the case, `#e1@0` would denote an exact complex number.

In Chibi, evaluation of `(exact? #e1@0)` still returns `#f`.

Im am wondering whether Chbi's behaviour is against the intended spec or whether the report as written is overly constrictive. Note that the report says that `make-polar` may return an inexact number even when exact arguments are given but the section on numerical constants is not based on the semantics of `make-polar` as written.

Also, the report allows an implementation to silently represent an exact number as an inexact one if it cannot represent it as an exact one. However, `1@0` is easily represented as an exact number, namely `1`.

**Comment by mnieper** [comment]
P.S.: An implementation conforming strictly to the report would have to be able to decide whether `(= x+yi m@p)` is `#f` or `#t` for (representations of) rational numbers `x`, `y`, `m`, `p`. In fact this is possible by using some hard mathematics. By the Lindemann-Weierstraß theorem, the cosine (and sine) of a rational number `p` is a rational number (in fact, an algebraic number) if and only if `p` is zero. Thus the above comparison will always yield `#f`except for the cases when `m` or `p` are zero.

**Comment by ashinn** [comment]
Technically, _nothing_ is required to have an exact representation, and pretty much the whole numeric tower is optional.  For example, if an implementation doesn't support bignums, exact operations that overflow the fixnum range may return flonum results.  I don't believe there is any existing implementation which uses a polar representation for complex numbers, so in practice 1@0 will always be coerced to rectangular.  It's of course better if the implementation can optimize and preserve exactness here, but I think something of a gray area.

The #e prefix, however, should always return an exact result, even if it has to round aggressively.  I'll fix that.

**Comment by ashinn** [comment]
FYI, you can see here that many implementations, including Gauche and Guile, don't have any exact complex numbers at all: http://trac.sacrideo.us/wg/wiki/ComplexRepresentations

**Comment by mnieper** [comment]
Personally, I think the concept of an exact complex number does not make much sense without talking about algebraic numbers. Taking the polar representation aside, the only exact complex numbers that can be denoted are the numbers of the form a+bi with a and b being rational, in other words the elements of Q(i), the quotient field of the Gaussian integers. However, contrary to C = R(i), this field is not distinguished. While C is the only finite extension of R (and thus algebraically closed), Q(i) is just one finite extension of Q. For example, taking a primitive third root of unity w instead of the fourth root of unity i yields the quotient field Q(w) of the so-called Eisenstein integers which are as interesting as the Gaussian integers.

So supporting exact complex numbers would only make sense from the mathematical perspective (and, I daresay, of any use) if one is able to express any algebraic number (any complex number which is a root of a non-trivial polynomial with rational coefficients) as such an exact complex number. This would work because the arithmetic of algebraic number is no less exact than the arithmetic over the rationals. And such a Scheme implementation would be able to carry out all calculations involving only rationals, addition, multiplication, arbitrary roots, solutions of polynomial equations exactly.

Thus I would suggest for the numeric tower of R7RS large not to demand exact complex numbers without also demanding algebraic numbers (6.2.3 of R7RS small speaks of a _coherent_ subset).

Better yet, the concept of a linear numeric tower could be re-thought. Finite fields, for example, while interesting in coding theory or cryptography, have no place in a linear tower (but we have coercion maps from the integers to the finite fields, etc.). Polynomial rings and quotient fields thereof could also extend the numeric tower.

**Comment by ashinn** [comment]
As I said, the standard does not demand exact complex numbers at all.  Exact representations of algebraic numbers often comes up in these discussions, but have yet to be implemented by any Scheme.  The standard therefore specifies the de-facto standard while allowing room for extensions.

Implementations are also allowed to extend beyond a tower, but the range of numeric types specified the standard only follow a linear order.
