### ISSUE TITLE
`(string->number "1/2@1")' yields `#f'

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#333]
Likewise, typing `1/2@1` at the prompt of the repl gives an error.

**Comment by ashinn** [comment]
Currently the parser is very simple: if it sees "<number> /", parses the remainder as a denominator.  There's no lookahead _or_ backtracking.  If the denominator is complex, it assumes it was rectangular, and can recover the real part as the denominator.  This clearly doesn't work for polar notation.

The weirdness you see in "<number> e" handling is the same - it just reads the trailing portion as a single number, and recovers the real part in the complex case.

**Comment by mnieper** [comment]
I see, thanks for the explanation why it would be hard to correct the problem with the current parser.

BTW, I am currently writing a reader for the R7RS syntax in C with Flex/Bison (that's why I have been doing a lot of tests and reported my findings here). Would you be interested in it for Chibi?

**Comment by ashinn** [comment]
I like keeping the core C part of Chibi completely standalone - no external libraries or tools required.

What I'll probably due is leave these corner cases unsupported in the C reader, but implement them in the Scheme reader.

**Comment by mnieper** [comment]
The flex and bison tools are just needed to compile the language description to standard C code. There's no runtime dependency. What one usually does is to distribute the intermediate C files together with the grammar source files so that people can perform a build even if they lack flex and bison.

**Comment by ashinn** [comment]
Yep, I'm well aware of how flex and bison work, which is why I said no external libraries "**or tools**."  Everything about chibi should be completely standalone.

But more practically, I suspect the generated code would be huge (by chibi standards) and unacceptably increase the library size.  I like the tight, hand-coded recursive-descent parser.

I'm more than willing to fix the Scheme reader, though, and in fact this has been on my TODO list for a while.

**Comment by mnieper** [comment]
I cannot yet tell how large the generated object code will be because the reader is not yet ready. As both tools are from an era 40 years ago, they should know how to cope with limited space. :-)

**Comment by johnwcowan** [comment]
The syntax `1.0@2.0` doesn't work either as of 0.9.0, though `1@2.0` does.  This is a much more serious problem for anyone wanting to use polar notation: it is basically broken, although you can work around it in code with (make-polar 1.0 2.0).

**Comment by ashinn** [comment]
Oops, it was only supporting 1@2 before.  This is a different code path though and easy to fix.

**Comment by ashinn** [comment]
Actually, the original problem had a small fix with a little piece of inference.

Chibi will still sometimes return valid numbers for invalid syntax, but this is allowed.
