### ISSUE TITLE
SRFI-130: problematic call to %string-contains

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#335]
`130.scm` calls `%string-contains` with three arguments, `(s1 s2 start1)`, which is fine when `string-contains` in `string.sld` is mapped to SRFI 13 `string-contains`.  But the fallback definition if you *don't* have SRFI 13 is the two-argument version of `string-contains` defined in `string.sld`.  The Chicken compiler caught this one when I tried to port `(srfi 130)` and `(chibi string)` after disabling the reference to `(srfi 13)`.

**Comment by ashinn** [comment]
You forgot to recompile.  string-contains is an opcode defined in (chibi ast) which was updated to take an optional third argument.

**Comment by johnwcowan** [comment]
Which makes it not portable, since it's written in C.  Fortunately it's trivial to add the third argument to the definition given in `string.sld`.

**Comment by ashinn** [comment]
I see what you mean, sorry, I completely forgot there was a non-chibi, non-SRFI-13 string-contains definition at all.  I've updated this.  Hopefully noone ever uses it.
