### ISSUE TITLE
Redefinition of datum labels can force the reader into an infinite loop

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#337]
The following datum (?) entered at the repl (`chibi-scheme` and `chibi-scheme -R`)
```
'#1=(#1# #1=42 #1#)
```

makes Chibi's reader loop forever (eventually yielding a segfault with `chibi-scheme`). It is unclear whether the standard allows such a datum because the datum label `#1` is redefined, and R7RS does not seem to say anything about the redefinition of datum labels. It is probably undefined behaviour.

In any case, it would be nice if Chibi did not fail here: either by allowing any redefinition of a datum label or by reporting an error.

**Comment by mnieper** [comment]
P.S.: More seriously, the example of section 2.4 of the report does not work (anymore?) :

```
#0=(a b c . #0#)
```

**Comment by ashinn** [comment]
The example #0=(a b c . #0#) works fine for me.

**Comment by mnieper** [comment]
With the latest patches, I get:

```
$ chibi-scheme -R
> '#0=(a . #0#)
ERROR: read error: duplicate label: "0"
```

On the other hand:

```
$ chibi-scheme
> '#0=(a . #0#)
(a a a a a ...
```

This seems to work (except with the caveat that the writer does not write the shared structure with datum labels in a finite way.)

**Comment by ashinn** [comment]
Oops, fixed (the former case - the non-R7RS repl always went into an infinite loop there).
