### ISSUE TITLE
Invalid self label reference error

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#338]
I think I have found one more issue:

```
$ chibi-scheme -R
> '#1=#(#2=#1#)
ERROR: read error: self label reference: 2
```

The following does work as expected:

```
$ chibi-scheme -R
> '#1=#(#1#)
#0=#(#0#)
```

**Comment by ashinn** [comment]
Not a bug - that's an invalid self-reference as the error says.

**Comment by mnieper** [comment]
Could you explain why this counts as a self-reference? In my example, `#2` is not referencing itself, directly or indirectly, is it? It is referencing `#1`, but `#1` in turn is not referencing `#2`. (The standard says: "In addition, it is an error if the reference appears as the labelled object itself (as in `#<n>= #<n>#`), because the object labelled by `#n#=` is not well defined in this case.")

**Comment by ashinn** [comment]
It's meaningless.  No one would ever write this by hand, and no code would generate it.

**Comment by mnieper** [comment]
My example is certainly overly simplistic, but I wouldn't say that any sane code would never generate such a construct: Imagine code that wants to write a vector, of which it knows a priori that the first and second entry are shared. It could use the static template `#(#N=<entry> #N# ...)` to output the vector (with a fresh label `N`, of course). Now other code that is responsible for writing `<entry>` (and whose output goes into the template) may very well substitute `#M#` for `<entry>`...

(The Scheme writer is, of course, more sophisticated. But any one-pass writer that (for whatever reasons) does not or cannot build the datum in a left-to-right, top-to-bottom fashion may have to produce labels that reference other labels in a non-circular fashion).
