### ISSUE TITLE
#0=(#0#) gives strange results

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#339]
Try:

```
$ chibi-scheme -R
> (define a '#0=(#0#))
> a
```

Or type '#0=(#0#) directly at the prompt.

On the other, this works:
```
$ chibi-scheme -R
> (define a (cons #f '()))
> (set-car! a a)
> a
#0=(#0#)
```

**Comment by ashinn** [comment]
This is not a problem with the reader, but a limitation of the macro expander, trying to parse cyclic source code.
