### ISSUE TITLE
The `snow-chibi` binary doesn't find `snow.img`

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#345]
When I start `snow-chibi` through the wrapper with this name, I just get:
```
$ snow-chibi
-:i <file>: couldn't open file for reading: snow.img
            dlopen failure: lib/chibi/net.so
```

The contents of `snow-chibi` in `/usr/local/lib` (on my system) are as follows:
```

#!/bin/sh

CHIBI=${CHIBI:-chibi-scheme}
if [ -x ./chibi-scheme ] && ! type $CHIBI 2>/dev/null; then
    # convenience for running from dev, notable "make test-snow"
    CHIBI="./chibi-scheme"
    export LD_LIBRARY_PATH=".:${LD_LIBRARY_PATH}"
    export DYLD_LIBRARY_PATH=".:${DYLD_LIBRARY_PATH}"
fi
SCRIPT_DIR=$(dirname $0)
SNOW_SCRIPT=${SNOW_SCRIPT:-$SCRIPT_DIR/snow-chibi.scm}

exec "${CHIBI}" -isnow.img "${SNOW_SCRIPT}" "$@"
```
What is the algorithm to locate image files?

**Comment by Kipples** [comment]
This looks like a problem with opening the .img file, if you do `chibi-scheme -mchibi.snow.commands -mchibi.snow.interface -mchibi.snow.package -mchibi.snow.utils /usr/local/bin/snow-chibi.scm help` does it work? I have the same issue

**Comment by mnieper** [comment]
You are right; I do get a different error message if I rename `/usr/local/share/chibi/snow.img`. Starting `snow-chibi.scm` works here by invoking the script directly with the shebang mechanism.

**Comment by ashinn** [comment]
Yes, it's a bug in the image loading (important to speedup snow-chibi).  I should have time to take a look this weekend.

**Comment by ashinn** [comment]
When we create an image, we preserve the exact path of loaded dynamic libraries.  If we generate the image from the build dir then install it, the installed path is different.

We could fix this by first installing then generating the image files, but it's probably better to make this robust and research for the library.
