### ISSUE TITLE
Case sensitivity in <inline hex escape>'s 

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#347]
In section ‘2.1. Identifiers’, R7RS says: “However, it does not distinguish between upper and lower case
in numbers, nor in `<inline hex escapes>` used in the syntax of identifiers, characters, or strings.”.

Interpreting this strictly, this would mean that `"\X41;"` evaluated to `"A"` and not to `"X41;"` as it currently does (Larceny shows the same behaviour).

What is the intended behaviour? Are the implementations simply sloppy or was the intention of section 2.1 in R7RS that upper and lower case are not distinguished in `<hex scalar value>`'s?

**Comment by ashinn** [comment]
2.1 is not normative - you should check 7.1 for the formal syntax when unsure.

I think 7.1 is fairly unambiguous that case shouldn't matter here.
