### ISSUE TITLE
`0.0-0.0i` is not written in a valid way

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#352]
```
$ chibi-scheme
> 0.0-0.0i
0.0+-0.0i
```

The output is not a valid, portable way to write a number, although Chibi is able to parse it.

(In fact, Chibi is able to parse even more funny ways to write a number,  for example `(string->number "0.0+++---+++0.0i")` yields `0.0+0.0i`, which does make mich sense mathematically.)

**Comment by ashinn** [comment]
Fixed.  The funny reading doesn't bother me.
