### ISSUE TITLE
Feature request: Allow setting of addition *features*

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#356]
As `cond-expand` is partly to R7RS what `#ifdef` is to C (or rather its preprocessor), it would be nice if `chibi-scheme` accepted arguments like `-D foo`, so that the symbol `foo` would appear amongst the other symbols in `*features*` and `(features)`.

One way I could use this is for cross-compiling the Emscripten version. Other use cases may consist in having conditionals for debugging or logging purposes.
 
At the moment, `*features*` is set in `sexp_load_standard_env`. What would the way to go be? Make `*features*` a parameter?

**Comment by ashinn** [comment]
This has been on my mental TODO list for a while.

**Comment by mnieper** [comment]
Thanks a lot. This is a great feature!

However, could you reopen the bug? Probably due to the `load_init(1)` in the patch, programs aren't started with an empty environment anymore, but with the standard one.

**Comment by ashinn** [comment]
This should do the right thing now.
