### ISSUE TITLE
Warning when building on Cygwin64

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#358]
gcc -c -DSEXP_USE_STRING_STREAMS=0 -DSEXP_USE_INTTYPES -Iinclude  -Wall -g -g3 -O3   -o gc_heap.o gc_heap.c
gc_heap.c: In function ‘sexp_load_image’:
gc_heap.c:611:45: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘off_t {aka long long int}’ [-Wformat=]
     snprintf(gc_heap_err_str, ERR_STR_SIZE, "couldn't seek to image offset: %s -> "PRIoff": %s\n", filename, offset, strerror(errno));
                                             ^
gc_heap.c:611:45: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘off_t {aka long long int}’ [-Wformat=]

This happens because Windows (including Cygwin) is an LLP64 system, and off_t is not long but long long.  Therefore, the %ld has to be changed on this platform to %lld.

**Comment by mnieper** [comment]
Issue #320 is about the other way round. On my system, `off_t` is a `long` (which is 64 bits), and `%lld` would raise a warning.

http://stackoverflow.com/a/5251918/255577 shows a portable way around this problem.

**Comment by johnwcowan** [comment]
Yes, most 64-bit systems are LP64 (long is 64 bits), but Win64/Cygwin64 are exceptions.  The problem is not with the type, it's with the sprintf format directive, which has to be made conditional on whether off_t is a long or a long long.  The reason you can't safely use %lld everywhere is that gcc's sprintf warning system doesn't know whether long and long long are the same or not, even on machines where they are.  Unfortunately there is no directive to portably output an off_t.

Cygwin64 can be detected by its $(uname -o) of "Cygwin" and its $(uname -m) of "x86_64".

**Comment by mnieper** [comment]
Another idea: On gcc, there is off64_t, isn't it? This should be portable
between Linux, Cygwin64, and so on.

(One could also take a look into the autoconf macro AC_SYS_LARGEFILE from
here
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/System-Services.html,
which wants to portably enable 64 bit file pointers. Maybe its source shows
a way how to ensure that Chibi is compiled with large file support on all
supported systems, so that off_t is always a uint64_t.)

johnwcowan <notifications@github.com> schrieb am Mo., 6. Juni 2016 um
22:54 Uhr:

**Comment by johnwcowan** [comment]
That won't help.  It's all about the sprintf format directive, _not_ the type.  There is no way to make format directives portable.

**Comment by ashinn** [comment]
Can you check if that works?

**Comment by johnwcowan** [comment]
No, it doesn't, because _WIN64 is not defined on Cygwin (and rightly so, because programs assume it means this is a non-Posix environment).  Your change correct as far as it goes, because pure Win64 is also an LLP64 environment, but it doesn't solve the present issue.

The Right Thing seems to be to add `|| (defined(__CYGWIN__) && __SIZEOF_POINTER__ == 8)` as a third alternative on line 259 of `sexp.h`.  This tests for Cygwin64; there is no predefine for it that I can discover.

Note that the warning is _not_ false: on Cygwin64 as on Win64, long = 32 bits and long long = 64 bits, so you get the wrong error message without this patch.  `__SIZEOF_POINTER__` is defined by both gcc and clang.  I've successfully compiled this patch on Cygwin64 and on 64-bit Linux.

While you are at it, adding the following to the definition of `sexp_initial_features` in `eval.c` would be handy:

```
#elif __SIZEOF__POINTER == 4
"ilp32",
#elif defined(_WIN64) || (defined(__CYGWIN__)
"llp64",
#else
"lp64",
```
Note that APPLE is omitted here, because even though it has a different definition of off_t, it is still basically an LP64 platform (ints are 32 bits, longs and pointers are 64 bits).

**Comment by ashinn** [comment]
I don't add features lightly... what do you need these for?  The pointer size shouldn't be needed for Scheme, and should use C macros for FFI code.
