### ISSUE TITLE
complex `asin` gives wrong results

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#359]
```
> (sin (asin 0.5))
0.5
> (sin (asin 0.5+0.0i))
-1.26591883761898e-16-0.54785347388804i
```

The second result is clearly wrong.

**Comment by ashinn** [comment]
Also for acos.

**Comment by mnieper** [comment]
I don't understand the lines following https://github.com/ashinn/chibi-scheme/blob/master/bignum.c#L1035.

These don't calculate res = -i * tmp, do they?

**Comment by mnieper** [comment]
The other arithmetical involved work fine:
```
> (define (a z) (* -i (log (+ (* +i z) (sqrt (- 1 (square z)))))))
> (sin (a 0.5))
0.5+9.61481343191782e-17i
> (sin (a 0.5+0.0i))
0.5+9.61481343191782e-17i
```

**Comment by ashinn** [comment]
I was hacking multiplication by -i as swapping real/imag then negating, but got it wrong, and this is no place to be micro-optimizing.
