### ISSUE TITLE
Child fields of SRFI 99 records have to shadow parent fields

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#361]
SRFI 99 says: "Fields in derived record-types shadow fields of the same name in a parent record-type."

Chibi's current implementation doesn't follow this requirement.

```
 (let ()
  (define-record-type <parent>
    #f
    parent?
    (field parent-field parent-set-field!))
  (define-record-type (<child> <parent>)
    (constructor field)
    child?
    (field child-field))
  (let ((record (constructor 'a)))
    (parent-set-field! record 'b)
    (vector
     (child-field record)
     (parent-field record)))))
```
currently evaluates to `#(b b)` and not to `#(a b)` as demanded by SRFI 99.

**Comment by ashinn** [comment]
Definitely not something to fix before 0.8.

**Comment by mnieper** [comment]
It is then probably a good idea to rename (srfi 99) for the release until it is fixed. Otherwise programs that (conditionally) import it may break. (This actually happened here, which is why I noticed the discrepancy. )

**Comment by ashinn** [comment]
Did you shadow fields in a real program, or was this just a unit test?

**Comment by mnieper** [comment]
In my case it was a unit test, which I wrote for my own implementation of SRFI 131 on top of R7RS records because I want to use SRFI 131 in my own program on systems that neither support SRFI 99 nor SRFI 131.

Nevertheless, the problem is not just academic. Without shadowing fields, one cannot implement an object system on top of SRFI 99 records that has a notion of private fields (without resorting to hacks like prefixing field names).

**Comment by ashinn** [comment]
1. Of course you can implement an object system with private fields, just don't export the introspection.
2. You shouldn't implement private fields.  Scheme security should be based around access to exported bindings.
3. It's not worth breaking existing chibi programs that depend on SRFI 99 for a corner case.
4. In the time it took me to verify this I realized the fix was trivial and pushed it, oh well :/

**Comment by mnieper** [comment]
Some exported procedure that works on records of type `parent?` may depend on some inner state of the record object, say a field `field`, which is not part of the external interface. If another record type `child` with parent `parent?` that only makes use of the exported interface, adds another field named `field` by chance, the thing will break.

I don't see how this relates to your comments 1. and 2., and how these would solve the problem.

**Comment by mnieper** [comment]
Anyway, thanks for fixing. Now all my unit tests go through with Chibi's SRFI 99 instead of my own layer on top of R7RS.

What is strange, though, is that my program, which makes heave use of it SRFI 99/131 records, runs significantly faster with my implementation (which is just Scheme code) on top of Chibi's R7RS records than with Chibi's SRFI 99 native records, which I don't quite understand.

**Comment by ashinn** [comment]
Without introspection field names have no meaning - all you have is getters and (optionally) setters, which you export at your own discretion.

**Comment by mnieper** [comment]
With shadowing, field names have in fact no meaning. But without shadowing, field names may become inadvertently meaningful, namely when the code responsible for the child chooses to add a field that is accidentally named like a field the code responsible for the parent chose.

**Comment by ashinn** [comment]
Ah, sorry, I was making the presupposition that you never introduce any name conflicts - you can in fact use hygiene to ensure all field names are unique.

**Comment by mnieper** [comment]
Is this compatible with SRFI 99's procedural layer? In `(make-rtd name fieldspecs parent)`, the argument `fieldspecs` is "a vector of field specifiers, where each field specifier is one of: a symbol naming the (mutable) field, ...".

In order to introduce hygiene, the vector would have to be a vector of syntactic closures or syntax objects and not of symbols, wouldn't it?

**Comment by mnieper** [comment]
This program prints `bar` in both Chibi and Larceny, so field names are match by the underlying symbol name, not hygienically:
```
(import (except (scheme base) define-record-type)
	(scheme write)
	(srfi 99))

(define-syntax define-parent
  (syntax-rules ()
    ((define-parent <parent> parent-field)
     (define-record-type <parent>
       #f
       #f
       (field parent-field)))))

(define-parent <parent> parent-field)

(define-record-type (<child> <parent>)
  (make-child field)
  #f)

(define foo (make-child 'bar))

(display (parent-field foo))
(newline)
```

**Comment by ashinn** [comment]
It may not be compatible with the SRFI 99 procedural layer, for which you'd need gensym.  The current syntactic layer could otherwise be fixed to avoid stripping hygiene.

Anyway, my point is my general philosophy for Scheme security is to restrict at the binding level.  Any kind of introspection feature is equivalent to giving root access.

**Comment by mnieper** [comment]
I agree with you that it is best to handle this at the binding level. And thanks for the input. I just noticed that Chibi's R7RS small `define-record-type` match the field names hygienically (and not by their symbol names), which makes possible what you have been proposing here.

One the other hand, Chibi's SRFI 99 implementation does matching by symbol name (which my example program from above demonstrates). This makes it incompatible to R7RS small. On the other hand, the basic assumption of R7RS small seems to be that identifiers are matched hygienically, which means Chibi's R7RS small implementation is correct, and the claim in the SRFI 99 document that it is compatible with R7RS small records false.

Larceny, in turn, does not match field names of R7RS small records hygienically, but does what is written in SRFI 99. So in Larceny, the record systems are compatible, but it does not seem to implement R7RS small.

This should probably be discussed in WG 2 as accepting SRFI 99 or SRFI 131 into R7RS large will introduce a conflict with R7RS small.
