### ISSUE TITLE
SRFI 99: Child doesn't set parent field

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#363]
The following test fails with Chibi's implementation of SRFI 99:

```
      (test-equal "Child constructor sets parent field"
		  'a
		  (let ()
		    (define-record-type <parent>
		      #f
		      parent?
		      (field1 parent-field))
		    
		    (define-record-type (<child> <parent>)
		      (constructor field1 field2)
		      child?
		      (field2 child-field))
		    
		    (let ((record (constructor 'a 'b)))
		      (parent-field record))))
```
The reason is that the parent field is apparently not set by calling the constructor defined in the child record type. The error does not show up if the children does not define its own fields (i.e. field2 in this example).

NB: This is completely orthogonal to the question of hygiene currently being discussed, and seems to be a real bug.

**Comment by ashinn** [comment]
Added tests for confirmation but was unable to reproduce.

**Comment by mnieper** [comment]
The latest patch to SRFI 99 must have somehow fixed it. When I reported the test, I had missed the latest changes.
