### ISSUE TITLE
Embedded-friendliness

### ISSUE THREAD

**Issue by jimon** [ashinn/chibi-scheme#365]
So if one reads the title in readme - one will find ```Minimal Scheme Implementation for use as an Extension Language```, which is great. And than one will try to "embedded" chibi in something like game-engine/microcontroller/etc and will find ... that it's not very integration friendly:

- [ ] sexp.c relies on POSIX functions ... many environments will simply not have POSIX or will not have time/resources for it, like video game consoles. Most of it is disabled by ```SEXP_USE_GREEN_THREADS``` but there is still ```shutdown``` calls in the beginning.
- [ ] Windows unfriendly features.h, by default there is some stuff like :

```
#define snprintf(buf, len, fmt, val) sprintf(buf, fmt, val)
#define strcasecmp lstrcmpi
#define strncasecmp(s1, s2, n) lstrcmpi(s1, s2)
#define round(x) floor((x)+0.5)
#define trunc(x) floor((x)+0.5*(((x)<0)?1:0))
#define isnan(x) (x!=x)
#define isinf(x) (x > DBL_MAX || x < -DBL_MAX)
```

which is not really needed with MSVS 2015 (though looks like strcasecmp and strncasecmp are still needed).
- [x] Default features.h are not compile and forget (at least not for non POSIX environment), see Lua where you can just compile it as bunch of C files and everything will "just work" on most environments.
- [x] clibs.c is generated by a tool written in schema, which means you need working chibi to build chibi :(
- [x] No way to embedded scheme lib in binary blob (maybe just haven't found yet), usually you simply don't have ability to bring files along, so everything must be embedded in code, as well as resources, images, etc (this is what Qt does to bring resources in a cross-platform fashion).
- [x] No amalgamated build option. In general multiple source files distribution is great for maintainers convenience, but it's very unpractical outside of *nix world. Another great alternative is to provide amalgamated builds (basically one header and optionally one C file), see sqlite, https://github.com/nothings/stb and many others

In general making chibi more plug-and-play kind of lib will enable much broader interest in all kind of strange places ... :)

**Comment by ashinn** [comment]
All of the POSIX stuff is optional.
I got it to run on VC++ a while back, shouldn't need much to get it working again.
Alas, I don't have access to a Windows machine - patches welcome!

clibs.c is entirely optional.  Build without it first if you want to use it.
This is standard bootstrapping and explained in the manual.

You can build a binary blob with image files.  It's a fairly manual process at the moment though.

The amalgamated build is just all the .h and .c files concatenated together, should work fine.

**Comment by jimon** [comment]
Might be good idea also to add https://www.appveyor.com/ (very similar to travis) so we can make sure that Windows support is still intact :)

**Comment by ashinn** [comment]
I added this, and it indeed would be very handy if the build were currently working since I could then maintain windows support without a windows machine of my own.

As is, it currently doesn't understand .vcproj files, so even if that build were still working I couldn't test this.  It would require a windows user to update this and make any other changes needed (I am sure some work is necessary, but should be quite easy).  I repeat, **patches welcome**! :)

As for the other topics in the issue, most seem non-issues and the others too vague to be actionable, and it's hard to track everything together.  I'll close this issue.  If there is some specific build feature you want please open a separate issue for it.
