### ISSUE TITLE
Wrong `bitwise-ior` result on 32bit host/bignum

### ISSUE THREAD

**Issue by okuoku** [ashinn/chibi-scheme#375]
`bitwise-ior` procedure in `(srfi 33)` returns wrong result on bignums.

```scheme
(import (chibi) (chibi bytevector) (srfi 33))

(define bits (- -1 #xffffffff))
(define r (bitwise-ior bits 1))

(display bits) (newline)
(display r) (newline)
```

The last line results `-4294967297` on 32bit linux. It is `FFFF FFFE FFFF FFFF`.
Expected result is `-4294967295` which is `FFFF FFFF 0000 0001`.

Tested at https://github.com/ashinn/chibi-scheme/commit/57c6d7c1ec091b6013d09f897e432fbb79b92e39

`Linux ubuntu32 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:06:14 UTC 2016 i686 i686 i686 GNU/Linux`

`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1)`

**Comment by ashinn** [comment]
Thanks!  Verified fails on 64bit hosts as well with:

`(test -18446744073709551615 (bitwise-ior 1 (- -1 #xffffffffffffffff)))`

**Comment by ashinn** [comment]
Basically bignums are not stored as twos complement, so this isn't working as you expect.  At least gambit does what you expect though, so I should probably fix this.  I need to double check the other bitwise ops on negative bignums as well though.
