### ISSUE TITLE
Porting Chibi to Golang

### ISSUE THREAD

**Issue by turbopape** [ashinn/chibi-scheme#376]
Hi,

In my job I have to write Golang and I want to script some stuff in scheme( when I need power of expression)

I saw that this is planned in the Readme, though I haven't been able to see if it has already been done.

If not,.  Can someone explain the general structure of Chibi and how can I port it to Golang?

Cheers

**Comment by ashinn** [comment]
The idea was actually to implement a Golang interpreter in Scheme, not the other way around.

For Scheme in Go, maybe check out https://github.com/zfjagann/gamma

**Comment by lassik** [comment]
Another Scheme in Go: https://github.com/weinholt/conscheme. Testable via `docker run -it schemers/conscheme:head`.
