### ISSUE TITLE
Using chibi in C++ projects

### ISSUE THREAD

**Issue by ecraven** [ashinn/chibi-scheme#378]
When trying to include sexp.h (or anything that includes sexp.h) and compiling with a c++ compiler, there are errors about 
````
sexp data[];
````
not being valid in C++ (which is correct, it is only valid in C).

GCC 6.2.1:
````
In file included from foo.cpp:1:0:
/usr/include/chibi/sexp.h:387:17: error: flexible array member ‘sexp_struct::<anonymous union>::<anonymous struct>::data’ not at end of ‘struct sexp_struct’
       sexp data[]; // []
````

For GCC, changing every occurrence of such unspecified arrays to `sexp data[0]` does work, but I'm not sure whether that's portable...

As it is, I think you cannot include chibi directly in any C++ project, unless you completely wrap it in a C layer (which doesn't use [] directly).

**Comment by ecraven** [comment]
http://stackoverflow.com/questions/4412749/are-flexible-array-members-valid-in-c suggests sizing such arrays as [1], not [] or [0] (which would work in GCC, but maybe not in other compilers).

**Comment by Jasu** [comment]
At least Clang supports chibi-scheme as is. I just had to switch to Clang because of this. Interestingly, GCC 5 works just fine.

**Comment by ashinn** [comment]
Pushed a fix, try it and let me know if you have any problems.
