### ISSUE TITLE
External representation of circular list

### ISSUE THREAD

**Issue by phamhathanh** [ashinn/chibi-scheme#380]
In the repl, typing
````
#0=(1 2 3 . #0#)
````
results in an infinite loop of 1 2 3 1 2 3...

I think some loop detection method should be implemented.

**Comment by ashinn** [comment]
The default repl is extremely minimal.  Use "chibi-scheme -R" to get an R7RS repl which will handle this properly.  You still need to quote the list of course - circularity in a program outside of quoted values is undefined.
