### ISSUE TITLE
Midnight commander cannot enter directories in tgz-files created by snow-chibi

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#384]
This is probably an issue of the code that creates tgz-files in Chibi:

When I create a package with snow-chibi and try to view the tgz-file with Midnight Commander, the integrated tar-viewer cannot enter directories inside the tgz-file because they look like socket files to it. Emacs and GNU tar have no problems to work with Chibi-created tar-files. Midnight Commander has no problems with tar files created by all other programs I tested.

Is there something unusual with Chibi's tar-files?

**Comment by ashinn** [comment]
Chibi has its own tar implementation in (chibi tar), using the ustar extensions.  The type is set to 5 for directories, which should be correct.  I'll take a look at why mc might be confused.

**Comment by mnieper** [comment]
mc seems to use its own custom implementation of the tar format: https://midnight-commander.org/browser/src/vfs/tar/tar.c

ustar extensions seem to be supported.
