### ISSUE TITLE
"snow-chibi reg-key" segfaults

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#385]
Valgrind says there is a null-pointer access:

```
==16877== Command: chibi-scheme -isnow.img /usr/local/bin/snow-chibi.scm reg-key
==16877== 
==16877== Invalid read of size 4
==16877==    at 0x6DAAF96: sexp_rs_random_integer (rand.c:56)
==16877==    by 0x4E5F8A1: sexp_apply (vm.c:1266)
==16877==    by 0x10C885: run_main (main.c:568)
==16877==    by 0x109769: main (main.c:623)
==16877==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

**Comment by mnieper** [comment]
When I run the same command directly, not using the image file, there's no segfault. (Just a 500 internal server error from snow-fort, but this is another problem.)

(I did a clean install from freshly compiled sources to have a recent snow.img.)

**Comment by ashinn** [comment]
Must be a bug in the image file support.  I'll take a look, and stop using the image if I don't have time to work it out.

**Comment by ashinn** [comment]
Simple bug: (srfi 27) pre-dated multi-vms (and images), and was still using a static C global.  Fixed.
