### ISSUE TITLE
Chibi does not convert identifiers into symbols in vector literals

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#389]
The following program exhibits the error: `b`, which becomes renamed and thus wrapped in a syntactic closure is not converted back to the symbol `b` when the expansion of (foo) is evaluated.

```scheme
(import (scheme base)
	(scheme write))

(define-syntax foo
  (syntax-rules ()
    ((foo)
     #(b))))

(display (foo))
(newline)
```

The output of the above program is similar to `#({Sc #22 #<Environment 140638497779360> () b})
`.

**Comment by mnieper** [comment]
It seems as if `sexp_strip_synclos_bound` in `eval.c` fails to handle the vector case. Implementing it correctly is not completely straightforward because simply traversing through the vector's elements may lead into an infinite loop (because of possible cycles in the traversed graph).

(Using `SEXP_STRIP_SYNCLOS_BOUND` to limit the recursion depth is only an approximation to the exact behavior. However, the list case does seem to use the same approximation.)

**Comment by ashinn** [comment]
Fixed, though you have to use quote - a raw unquoted vector remains unstripped, which I think is a good feature.  It does use the same bound hack.

**Comment by mnieper** [comment]
Thanks for fixing; however, not stripping unquoted vector constants is a violation of R7RS if I am not mistaken. By 4.1.2, vector constants need not be quoted, so `'#(...)` has to evaluate to the same value as `#(...)`, which is doesn't if `#(...)` remains unstripped, and `'#(...)` becomes unstripped.

**Comment by ashinn** [comment]
As discussed before, whether quoted identifiers have hygiene stripped is actually a grey area.  It's assumed (and kind of broken otherwise), but not made explicit.  I'm taking advantage of this and the fact that I consider unquoted vectors a mistake to encourage the explicit quote.

**Comment by mnieper** [comment]
I am not so sure anymore whether it is compatible with R7RS that hygiene remains unstripped in quoted identifiers. In 6.5 it says: 

> It is guaranteed that any symbol that has been returned as part of a literal expression, or read using the read procedure, and subsequently written out using the write procedure, will read back in as the identical symbol (in the sense of eqv?).

If `#(b)` in the above example does not get its hygiene stripped, the write/read invariance of the symbol `b` is violated.

Is there also a technical reason for your choice and is stripping hygiene in unquoted vector constants much more complicated to implement?

**Comment by ashinn** [comment]
It would be one line of code to also support the unquoted case.

**Comment by ashinn** [comment]
I changed my mind and stripped hygiene from unquoted vector literals as well - it's less work than documenting the difference.
