### ISSUE TITLE
chibi-doc shows warnings about already defined bindings

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#390]
When creating documentation for a module that defines an identifier with the same name as an identifier exported by the base library, chibi-doc shows a warning that an already defined binding is imported.

**Comment by ashinn** [comment]
Hardly a bug, since it does the right thing anyway.  It tries to guess what imports you need for your examples.  I've made this lazy, so there's no warning if you don't use examples at all.  Otherwise, I added a new \example-import-only command to import only needed libraries.
