### ISSUE TITLE
Speed up GC allocation

### ISSUE THREAD

**Issue by justinethier** [ashinn/chibi-scheme#392]
This change from Cyclone caches the last page that had an allocation and starts from that page next time, if possible. This speeds up allocation on large heaps because for many requests we can avoid searching through heap pages that do not have a free slot:

https://github.com/justinethier/cyclone/commit/391051ba7bdc6e9f33dbcb13dda513b6996bf129

A similar change should be possible in Chibi.

**Comment by ashinn** [comment]
Did you benchmark this?  I ran the gabriel benchmarks distributed with chibi and saw no improvement.

**Comment by justinethier** [comment]
That's unfortunate :(

Not on Chibi, no. There was a dramatic improvement for Cyclone on these benchmarks though: https://github.com/ecraven/r7rs-benchmarks

But Cyclone's heaps are organized a bit differently, with some being dedicated to fixed-sized objects. It must be more amenable to the change.

**Comment by justinethier** [comment]
Did you try it with the `>=` fix (sorry about that, looking back maybe I should have ported this change to Chibi before contacting you)?

https://github.com/justinethier/cyclone/blob/master/gc.c#L538

**Comment by ashinn** [comment]
Yes, I applied the >= fix.  I also measured and saw that in almost all cases there were one or few heap chunks, so I instead implemented the logic for the next available free node (per heap chunk).

Performance has never had a high priority for Chibi, so I don't have a lot of time to spend tuning this :/

**Comment by justinethier** [comment]
No worries, sorry this wasn't more helpful. Thanks for your time.
