### ISSUE TITLE
chibi-doc doesn't parse Scribble table syntax

### ISSUE THREAD

**Issue by kozross** [ashinn/chibi-scheme#396]
[This example](https://github.com/ashinn/chibi-scheme/files/743603/table.txt) is based on [the sample table code from the Racket Scribble docs][1], with ``@`` replaces with ``\`` as per Chibi's parser rules. However, this fails to process with ``chibi-doc``, instead emitting an unknown syntax error. Am I missing something, or does Chibi's subset of Scribble not support tables?

[1]: https://docs.racket-lang.org/scribble/getting-started.html#%28part._.Tables%29

**Comment by ashinn** [comment]
The error you get should be clear enough - #:sep is not valid syntax.  Chibi doesn't use a separate keyword type, preferring 'sep: as supported in let-keywords and friends from (chibi optional).

Also there is no special syntax for tables - Racket's tabular is a function which translates a list of lists into a table.  Chibi doesn't provide this utility, and I don't like how it handles the separator (it actually introduces extra dummy columns, which will break if you cut&paste into a spreadsheet).

So currently in Chibi you just use table directly, and can provide style overrides with a first argument which is an sxml-style attribute list.  See, for example, [this table in (chibi config)](https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/config.scm#L58-L65).  I'm open to a tabular-like utility, but not with the separator semantics.
