### ISSUE TITLE
Fully support unknown implementations in snow-chibi

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#400]
snow-chibi currently has limited support for unknown implementations. Two things, however, do not yet seem to be customizable in order to work for unknown implementations:

In https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/snow/commands.scm#L1345 the selected command is always "scheme-script" with no arguments. It would be nice if there was a command-line argument so that this can be overwritten with a program name together with arguments.

"scheme-program-command" in https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/snow/commands.scm#L1356 isn't set for unknown implementations so that testing in https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/snow/commands.scm#L1424 is skipped. It would be nice if there was a command-line argument so that this command can be set explicitely for unknown implementations.

**Comment by ashinn** [comment]
I've added some options for this.  You'll need to specify to search "." for libs if this isn't done already, let me know if it works for you.
