### ISSUE TITLE
Symbol conflict in stty module

### ISSUE THREAD

**Issue by jonruttan** [ashinn/chibi-scheme#402]
I've run into a symbol name conflict in the _stty-lookup-table_ in the [stty.scm](https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/stty.scm) file.

```scheme
;; input settings
…
(ixon     input    ,IXON)    ; enable XON/XOFF flow control
…
```

clashes with

```scheme
;; combination settings
…
(ixon     combine  (ixoff ixany imaxbel opost isig icanon)) ;; xcase iuclc
…
```

**Example code:**
```scheme
(import (chibi stty)
            (chibi process))
(system "stty" "-a")
(with-stty '(not ixon)
                (lambda () (system "stty" "-a")))
```
Ignoring the messed up formatting (due to _opost_ having been shut off), _ixon_ is still on within the _with-stty_ block, while _ixoff, ixany, imaxbel, opost, isig, and icanon_ have all been turned off.

To temporarily fix it locally, I've renamed the _ixon_ combination setting symbol to _xon_ instead. If this is an acceptable solution I'm happy to commit the code and do a pull request.

Thanks in advance for looking into this, and for sharing chibi-scheme with everyone.

**Comment by ashinn** [comment]
Let me know if that works for you.
