### ISSUE TITLE
snow-chibi segfaults

### ISSUE THREAD

**Issue by petercrlane** [ashinn/chibi-scheme#404]
snow-chibi reg-key and upload segfault  (commit 37178ea)

My platform is:

NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"

**Comment by ashinn** [comment]
Works on OSX, this appears to be a recent regression on Linux, will fix shortly.

**Comment by ashinn** [comment]
This is from the string-cursor API refactoring, the server-side error is:

`2017-04-23 12:37:32 E internal error: {Exception #19 user "string-cursor-ref: not a string-cursor" (0) #<procedure lp> ("./lib/chibi/string.scm" . 63)}
`

I'm unable to reproduce the segfault on the client side, however.  I get:

`ERROR: couldn't retrieve url
    "http://snow-fort.org/pkg/reg"
    ("HTTP/1.1" 500 "Internal server error")
  called from <anonymous> on line 252 of file /usr/local/share/chibi/chibi/net/http.scm
  called from <anonymous> on line 804 of file /usr/local/share/chibi/chibi/snow/commands.scm
  called from <anonymous> on line 135 of file ./lib/chibi/app.scm
  called from <anonymous> on line 1067 of file /usr/local/share/chibi/init-7.scm
  called from <anonymous> on line 558 of file /usr/local/share/chibi/init-7.scm
  called from <anonymous> on line 638 of file /usr/local/share/chibi/init-7.scm
`

Note with recent versions of snow-chibi you can always use --noimage to disabled image loading, which I may make the default at this point.

**Comment by petercrlane** [comment]
snow-chibi --noimage upload PACKAGE 
seems to work with the latest version.

I don't get any other message if I leave out --noimage, only:
Segmentation fault (core dumped)

**Comment by ashinn** [comment]
I've added a note about --noimage to the docs, and also made failure to find/load an image non-fatal (it's just intended as speedup, so shouldn't be required).

Regarding segfaults, you will generally get one if you have an image in your path compiled with a different version of chibi, or if tracking head, anything a binary incompatible change (most changes).

Aside from that case, I've been unable to reproduce a segfault on either mac or linux, 32 or 64 bit.  If you grab head and do a clean reinstall (to be safe only one snow.img in your filesystem), please let me know if you can still reproduce this.

**Comment by arichiardi** [comment]
Just wanted to add a voice:

Ubuntu 16.04

```
$ sudo make PREFIX=~/.local install
...
echo "Generating images"
Generating images
cd / && LD_LIBRARY_PATH="/home/arichiardi/.local/lib:" DYLD_LIBRARY_PATH="/home/arichiardi/.local/lib:" /home/arichiardi/.local/bin/chibi-scheme -d /home/arichiardi/.local/share/chibi/chibi.img
cd / && LD_LIBRARY_PATH="/home/arichiardi/.local/lib:" DYLD_LIBRARY_PATH="/home/arichiardi/.local/lib:" /home/arichiardi/.local/bin/chibi-scheme -xscheme.red -d /home/arichiardi/.local/share/chibi/red.img
Segmentation fault (core dumped)
```

**Comment by arichiardi** [comment]
Disabling the image generation step does not solve either because probably `chibi-scheme` expects them:

```
$ chibi-scheme -V
chibi-scheme 0.8.0 "oxygen" (chibi r7rs ratios complex threads full-unicode modules dynamic-loading linux little-endian)

$ chibi-scheme 
Segmentation fault (core dumped)
```

**Comment by ashinn** [comment]
This is not snow-chibi so is unrelated.  chibi-scheme doesn't expect or even attempt to use images unless explicitly requested, so you have a different problem.

I can't reproduce your failure.  I regularly run and test chibi on Ubuntu 16 (64 bit).  It's most likely a problem with your environment.  Do you already have chibi installed on your system?  It may be picking up the wrong shared library?  After you install into ~/.local (why with sudo?), are you setting LD_LIBRARY_PATH to ~/.local/lib?

**Comment by arichiardi** [comment]
Ok thanks for the answer!

So  yes I install under `.local` these things and I do have proper setup:

```
$ echo $LD_LIBRARY_PATH 
/home/arichiardi/.local/lib

$ ll .local/lib/libchibi-*
lrwxrwxrwx 1 root root      24 Jan 17 14:52 .local/lib/libchibi-scheme.so -> libchibi-scheme.so.0.8.0*
lrwxrwxrwx 1 root root      24 Jan 17 14:52 .local/lib/libchibi-scheme.so.0 -> libchibi-scheme.so.0.8.0*
-rwxr-xr-x 1 root root 1083504 Jan 17 14:52 .local/lib/libchibi-scheme.so.0.8.0*
```

The `sudo` is written in the README so I just followed it, I will try without it.

**Comment by arichiardi** [comment]
So I tried it and it works fine in the shell, however in emacs it is a mess to set the `LD_LIBRARY_PATH` env var so I gave up and ended up installing in `/usr/local`.

**Comment by jordydickinson** [comment]
I was also having this issue. I had installed chibi 0.8.0 via Homebrew on macOS. The problem went away after running `chibi-scheme -mchibi.snow.commands -d/usr/local/opt/chibi-scheme/share/chibi/snow.img`, based on the make rule for `lib/snow.img` I found in the chibi-scheme Makefile. The [formula for Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/chibi-scheme.rb) appears to simply run `make PREFIX=...` and `make install PREFIX=...`, if that helps at all.
