### ISSUE TITLE
snow-chibi ignores (some) libraries (with numbers?)

### ISSUE THREAD

**Issue by petercrlane** [ashinn/chibi-scheme#405]
e.g. (srfi 60) is ignored when searching, and could not be found to install - installing manually after downloading the tgz worked

$ snow-chibi search srfi
chibi-scheme is /usr/local/bin/chibi-scheme
(chibi iset base)	0.7.3
(postgresql misc bytevectors)	15.07.21
(chibi regexp)	0.7.3
(r6rs hashtables)	0.0.1
(robin text)	1.0.0
(robin statistics)	1.0.0
(chibi net dns)	0.1
(chibi string)	0.7.3
(chibi math prime)	0.7.3
(chibi crypto rsa)	0.7.3
(robin abbrev)	1.0.0
(chibi show base)	0.7.3.1
(chibi net smtp)	0.1
(chibi crypto sha2)	0.7.3
(chibi crypto md5)	0.7.3
(chibi bytevector)	0.7.3
(chibi parse)	0.7.3
(slib string-case)	SLIB-3b5-r7rs
(robin disjoint-set)	1.0.0
(comparators)	1.0.0
(generators)	1.0.2
(in-progress hash tables)	0.0.3
(slib soundex)	SLIB-3b5-r7rs
(chibi sqlite3)	0.6
(macduffie json)	0.9.5
(chibi uri)	0.7.3
(chibi config)	0.7.3
(chibi char-set boundary)	0.7.3
(chibi app)	0.7.3
(rapid vector)	0.1.0
(rapid args-fold)	0.1.0
(rapid comparator)	0.1.1
(rapid set)	0.1.0
(rapid mapping)	0.1.1
(rapid vicinity)	0.1.0
(rapid format)	0.1.0
(rapid generator)	0.1.0
(rapid receive)	0.1.0
(rapid list)	0.1.0
(rapid assume)	0.1.0
(rapid test)	0.1.3
(rapid and-let)	0.1.0
(rapid box)	0.1.1
(in-progress hash bimaps)	0.0.3

**Comment by ashinn** [comment]
If this is a library you just updated, you need to run "snow-chibi-update" to reflect the changes first.  I think it caches the repo for an hour.

**Comment by ashinn** [comment]
... also, chibi historically prefers (srfi 33) which it supported natively, but has just recently updated to (srfi 142).

**Comment by petercrlane** [comment]
Sorry: other libraries were showing more quickly.  It is showing now.
