### ISSUE TITLE
SRFI 1: list= error

### ISSUE THREAD

**Issue by petercrlane** [ashinn/chibi-scheme#407]
Line 32 of srfi/1/predicates.scm should check ls2 is not null, e.g.  `(and (not (null? ls2)) (eq ...`
Without this check, shorter second lists to list= cause an error.

For example:

```
> (list= = '(1 2) '(1 2 3))
#f
> (list= = '(1 2 3) '(1 2))
ERROR in lp2 on line 32 of file /usr/local/share/chibi/srfi/1/predicates.scm: car: not a pair: ()
```

**Comment by ashinn** [comment]
Thanks!  Fixed.
