### ISSUE TITLE
Continuing issue #406

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#408]
The fix to issue #406 disposed of some but not all of the problems with the `bit` library (on 32-bit Cygwin):

```
546 out of 558 (97.8%) tests passed in 0.166078090667725 seconds.
12 failures (2.2%).
FAIL: (copy-bit 64 340282366920938463463374607431768211456 #f)
    expected 340282366920938463463374607431768211456 but got 0
    on line 216 of file "chibi-test.scm"
FAIL: (copy-bit 64 -340282366920938463463374607431768211456 #f)
    expected -340282366920938463463374607431768211456 but got 0
    on line 218 of file "chibi-test.scm"
FAIL: (copy-bit 256 -340282366920938463463374607431768211456 #t)
    expected -340282366920938463463374607431768211456 but got 2135987035920910082279229616932235919179133537346503360456781002605296415371930057602824792965120
    on line 220 of file "chibi-test.scm"
FAIL: (bit-field-rotate 340282366920938463463374607431768211456 128 0...
    expected 340282366920938463463374607431768211456 but got 0
    on line 238 of file "chibi-test.scm"
FAIL: (bit-field-rotate 340282366920938463463374607431768211457 3 0 64)
    expected 340282366920938463463374607431768211464 but got 8
    on line 240 of file "chibi-test.scm"
FAIL: (bit-field-rotate 340282366920938463463374607431768211457 -3 0 64)
    expected 340282366920938463465680450440981905408 but got 2305843009213693952
    on line 242 of file "chibi-test.scm"
FAIL: (bit-field-reverse -2 0 31)
    expected -1073741825 but got 18446744072635809791
    on line 260 of file "chibi-test.scm"
FAIL: (bit-field-reverse -2 0 32)
    expected -2147483649 but got 18446744071562067967
    on line 262 of file "chibi-test.scm"
FAIL: (arithmetic-shift -100000000000000000000000000000000 -100)
    expected -79 but got -78
    on line 368 of file "chibi-test.scm"
FAIL: (arithmetic-shift -100000000000000000000000000000000 -100)
    expected -79 but got -78
    on line 372 of file "chibi-test.scm"
FAIL: (arithmetic-shift -100000000000000000000000000000000 -100)
    expected -79 but got -78
    on line 707 of file "chibi-test.scm"
FAIL: (arithmetic-shift -100000000000000000000000000000000 -100)
    expected -79 but got -78
    on line 711 of file "chibi-test.scm"
```

**Comment by ashinn** [comment]
Yes, sorry, haven't forgotten about this and should be a straightforward fix, just haven't had time.

**Comment by johnwcowan** [comment]
No problem.  Here are the actual tests that fail:

  (test "test-16" -2600468497 (bitwise-ior 1694076839 -4290775858))
  (test "test-160" #t (bit-set? 0 1))
  (test "test-161" #f (bit-set? 1 1))
  (test "test-162" #f (bit-set? 1 8))
   (test "test-163" #t (bit-set? 10000 -1))
  (test "test-167" #t (bit-set? 1000 -1))
  (test "test-168" 0 (copy-bit 0 0 #f))
  (test "test-169" 0 (copy-bit 30 0 #f))
  (test "test-17" -184549633 (bitwise-ior -193073517 1689392892))
  (test "test-170" 0 (copy-bit 31 0 #f))
  (test "test-171" 0 (copy-bit 62 0 #f))
  (test "test-172" 0 (copy-bit 63 0 #f))
  (test "test-173" 0 (copy-bit 128 0 #f))
  (test "test-174" -1 (copy-bit 0 -1 #t))
  (test "test-175" -1 (copy-bit 30 -1 #t))
  (test "test-176" -1 (copy-bit 31 -1 #t))
  (test "test-177" -1 (copy-bit 62 -1 #t))
  (test "test-178" -1 (copy-bit 63 -1 #t))
  (test "test-179" -1 (copy-bit 128 -1 #t))
  (test "test-18" -2604237975 (bitwise-xor 1694076839 -4290775858))
  (test "test-180" 1 (copy-bit 0 0 #t))
  (test "test-181" #x106 (copy-bit 8 6 #t))
  (test "test-182" 6 (copy-bit 8 6 #f))
  (test "test-183" -2 (copy-bit 0 -1 #f))
    (test "test-184" 0 (copy-bit 128 #x100000000000000000000000000000000 #f))
  (test "test-185" #x100000000000000000000000000000000
                 (copy-bit 128 #x100000000000000000000000000000000 #t))
  (test "test-186" #x100000000000000000000000000000000
                 (copy-bit 64 #x100000000000000000000000000000000 #f))
  (test "test-187" #x-100000000000000000000000000000000
                 (copy-bit 64 #x-100000000000000000000000000000000 #f))
  (test "test-188" #x-100000000000000000000000000000000
                 (copy-bit 256 #x-100000000000000000000000000000000 #t))
  (test "test-189" 0 (bit-field 6 0 1))
  (test "test-19" -1865418641 (bitwise-xor -193073517 1689392892))
  (test "test-190" 3 (bit-field 6 1 3))
  (test "test-191" 1 (bit-field 6 2 999))
  (test "test-192" 1 (bit-field #x100000000000000000000000000000000 128 129))
  (test "test-193" #b111 (bit-field-replace #b110 1 0 1))
  (test "test-194" #b110 (bit-field-replace #b110 1 1 2))
  (test "test-195" #b010 (bit-field-replace #b110 1 1 3))
  (test "test-196" 2 (arithmetic-shift 1 1))
  (test "test-197" 0 (arithmetic-shift 1 -1))
  (test "test-175" -1 (copy-bit 30 -1 #t))
  (test "test-176" -1 (copy-bit 31 -1 #t))
  (test "test-177" -1 (copy-bit 62 -1 #t))
  (test "test-178" -1 (copy-bit 63 -1 #t))
  (test "test-179" -1 (copy-bit 128 -1 #t))
  (test "test-186" #x100000000000000000000000000000000 
  (test "test-187" #x-100000000000000000000000000000000 
  (test "test-188" #x-100000000000000000000000000000000 
      (test "test-205" #x100000000000000000000000000000000
            (bit-field-rotate #x100000000000000000000000000000000 128 0 64))
      (test "test-206" #x100000000000000000000000000000008
            (bit-field-rotate #x100000000000000000000000000000001 3 0 64))
      (test "test-207" #x100000000000000002000000000000000
            (bit-field-rotate #x100000000000000000000000000000001 -3 0 64))
  (test "test-220" (bitwise-ior (arithmetic-shift -1 32) #xBFFFFFFF) 
  (test "test-221" (bitwise-ior (arithmetic-shift -1 32) #x7FFFFFFF) 
  (test "test-258" -79 (arithmetic-shift -100000000000000000000000000000000 -100))
  (test "test-285" 99 (first-set-bit (expt -2 99)))

**Comment by ashinn** [comment]
try the latest commit

**Comment by johnwcowan** [comment]
Works!  Thanks for the quick turnaround.
