### ISSUE TITLE
Options for parsing and working with dates and times?

### ISSUE THREAD

**Issue by OpinionatedGeek** [ashinn/chibi-scheme#409]
Hi,

I'm working with some RSS feeds and one of the things I'd like to be able to do is compare publication dates of items. Rather than re-invent the wheel I figured I'd ask here what the common approach would be.

Publication dates are of the form:
    Wed, 17 May 2017 00:00:00 +0100

And I'd like to be able to parse that, compare it with other dates to see which is newer, as well as do some other basic arithmetic on dates.

I've used 'local-time' in Common Lisp before and it covered the sort of things I needed to do.

I looked at chibi time and SRFI 19, and while I can build the functionality on top of either of them I wanted to see if something already existed first.

(I also wasn't too sure of how to use SRFI 19 in chibi, since it's not one of the standard modules and it's not on snow-fort.org.)

**Comment by ashinn** [comment]
I have one-off code for this sort of thing, I just haven't gotten around to implementing SRFI 19.
It should be possible to write a portable version using the time procedures in R7RS.

**Comment by OpinionatedGeek** [comment]
Thanks for that. I've started trying to bring across the standard SRFI implementation.

One issue that has come up: I can't see a standard R7RS way (or a Chibi-specific way) to access the time spent in the current process or thread:

`Implementations are required to implement UTC, monotonic time, CPU time in current process, and time duration.`

Is there such a way?

**Comment by ashinn** [comment]
In Chibi you can use get-resource-usage from (chibi time).

**Comment by OpinionatedGeek** [comment]
Ah! Thanks for that. I'm using that now.

I've taken the [standard implementation](https://srfi.schemers.org/srfi-19/srfi-19.scm) from SRFI19 and ported it across so it should work in Chibi. It's on [Github](https://github.com/OpinionatedGeek/SRFI19). I've also added a lot of tests to exercise the implementation. If you've any comments about it please do let me know.

A couple of questions:
* What license do I apply to this? Most of the code is from the SRFI, so it's license should apply. And I've no desire to introduce restrictions on anything I added. How do I best express that in the package (and on Github, I suppose)?
* Importing (chibi time) doesn't work if I have it inside the `cond-expand`:
```
;; Things work if I import here.
(import (chibi) (chibi time))
(cond-expand
 (chibi
  ;;Things don't work if I import here.
  ;;(import (chibi) (chibi time))
```
Am I doing something wrong there? I'd expect to be able to just import within the `cond-expand` so that I'm not trying to import Chibi stuff outside of where I know I'm using Chibi.

Many thanks.

**Comment by ashinn** [comment]
I would ping Will Fitzgerald, the SRFI 19 author, about the copyright, but generally you would note that you've adapted their code and include their copyright in addition to your own.  It's probably worth putting this on snow-fort.org - the parts that are cond-expanded for Chibi can be extended for other implementations.  Note you should be able to make a fully portable R7RS implementation by storing the time the (srfi 19) library is loaded and taking the difference from the current time to approximate time spent in the process.

I'm unable to reproduce your cond-expand import problem - is this in a program or library?  Do you have a complete example I can try?

**Comment by OpinionatedGeek** [comment]
Hi,

Thanks for that - I'll email Will Fitzgerald about the copyright, and I'll put it on snow-fort once we're happy it's working the way it should, and once I've added the process-time code you mention (thanks for that!)

I suspect the problem is down to me, but the way I reproduced the problem was just to use `make test`. It runs all the tests. If I run `make test` with the current code, it all works, but if I comment out the `(import (chibi) (chibi time))` line and uncomment the `(import (chibi) (chibi time))` in the `cond-expand`, many tests fail.

I moved some of the constants around so that they're defined before the `cond-expand` and that helped. But then I noticed some name collisions, so I tried prefixing (chibi time). That didn't work as expected.

Here's an example of that problem:

```
#!/usr/bin/env chibi-scheme
;; -*- mode: scheme; -*-

(import (scheme small))

(cond-expand
 (chibi
  (import (prefix (chibi time) chibi:))

  (define (make-time value)
    (chibi:seconds->time value))
  )
 (else #f)
 )

(display "Current seconds: ")
(display (chibi:current-seconds))
(newline)
(display "Current time: ")
(display (make-time (chibi:current-seconds)))
(newline)
```
This fails at the invocation of `make-time`. (I'm now worried I've made a typo somewhere and I just can't see it.)

**Comment by ashinn** [comment]
Top-level cond-expand in a program in chibi doesn't support mixing imports and definitions, you need to split them out:

`(cond-expand
 (chibi
  (import (prefix (chibi time) chibi:)))
 (else #f))

(cond-expand
 (chibi
  (define (make-time value)
    (chibi:seconds->time value)))
 (else #f))
`

This is probably a bug but I'm not sure I want to support it, I think it's better to wrap such cond-expand logic in a library (where it does work as expected).

**Comment by OpinionatedGeek** [comment]
Hi,

Thanks for that. (Apologies for the delay - I was out of the country for a while.)

I've been in touch with the SRFI editors to find out what to do with copyright and licensing, and I've updated my repository to match what they recommend. Please let me know if I've done anything that will cause problems with Chibi:
    https://github.com/OpinionatedGeek/SRFI19

(In addition, the author of the original SRFI fixed a bug in the standard implementation I noticed.)

I've also split the cond-expand up as you recommended. Apologies - I didn't realise there was any difference in doing it in a library or program, so I didn't think mixing imports and definitions would be a problem. It all seems to work as expected now.

You mentioned:

> Note you should be able to make a fully portable R7RS implementation by storing the time the (srfi 19) library is loaded and taking the difference from the current time to approximate time spent in the process.

So I've added this to the cond-expand `else` section:

```
  ;; Simple R&RS approximation of time in process. It's very rough, so other schemes
  ;; should probably use their own primitives to come up with more accurate values.
  (define (current-milliseconds)
    (/ (current-jiffy) (/ (jiffies-per-second) 1000)))

  (define _srfi19-load-time (current-milliseconds))

  (define (current-process-milliseconds)
    (- (current-milliseconds) _srfi19-load-time))
```

Does it look OK to you? I appreciate it'll only give a very rough value.

Many thanks,

Geoff

**Comment by ashinn** [comment]
Yes, this looks fine, thanks!  A minor comment, you can just call the variable srfi-19-load-time - the advantage of a module system is we don't need special prefixes to hide unexported variables :)

**Comment by OpinionatedGeek** [comment]
Thanks! (I'll get the hang of Scheme modules eventually...)

Now, the next question: should I put this up on snow-fort? And if so, is there anything else to be done before I tackle that? (Also, should I use the library name '(srfi 19)' for it or is that reserved?)

Many thanks for all your help,

Geoff

**Comment by ashinn** [comment]
Yes, I think many people would appreciate that :)

**Comment by OpinionatedGeek** [comment]
Excellent - thanks. I'll put it up on snow-fort once I get the [packaging issue](https://github.com/ashinn/chibi-scheme/issues/417) fixed.

**Comment by OpinionatedGeek** [comment]
The implementation of SRFI 19 is now up on [Snow Fort](http://snow-fort.org/pkg).

Here's a link to the [(brief) documentation](http://snow-fort.org/s/opinionatedgeek.com/snow-fort.org/srfi/19/1.0.0/index.html).

Thanks for all the help with it!
