### ISSUE TITLE
segfault when using mk-time

### ISSUE THREAD

**Issue by OpinionatedGeek** [ashinn/chibi-scheme#410]
Hi,

mk-time causes a segfault if you pass an incorrect type of parameter for tm_isdst.

The (chibi time)[http://synthcode.com/scheme/chibi/lib/chibi/time.html] docs show a time-dst? procedure, so I assumed (wrongly) that the parameter to mk-time for tm_isdst would be a boolean. Turns out, it looks like time-dst? returns an integer, and I should pass an integer to mk-time. If I pass a boolean, it causes a segfault.

I'm happy to correct my error and pass an integer, but I figured I should mention the segfault - it would probably be better if it threw a regular error about the parameter type.

Here's a small script that shows the problem in action:
```

#!/usr/bin/env chibi-scheme
;; -*- mode: Scheme;-*-

(import (scheme small) (chibi time))

(display "About to create tm using 0. (This succeeds.)")
(newline)
(make-tm 0 0 0 1 0 114 0)
(display "Done creating tm.")
(newline)

(display "About to create tm using #f. (This fails with a segfault.)")
(newline)
(make-tm 0 0 0 1 0 114 #f)
(display "Done creating tm.")
(newline)

```

**Comment by ashinn** [comment]
Thanks!  Pushed a quick fix to prevent the segfault (just treats as 0), may make an error later.
