### ISSUE TITLE
More from issue #406

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#411]
I was wrong to say it works now: it was a config error on my side that suppressed all the errors.  Here are the remaining fails:

bitwise:
    bitwise/basic: .......................xxxx............................
    51 out of 55 (92.7%) tests passed in 0.00803208351135254 seconds.
    4 failures (7.3%).
    FAIL: test-16
        expected -2600468497 but got 18446744071109083119
    on line 28 of file "chibi-test.scm"
(bitwise-ior 1694076839 -4290775858)
    FAIL: test-17
        expected -184549633 but got 4110417663
    on line 29 of file "chibi-test.scm"
(bitwise-ior -193073517 1689392892)
    FAIL: test-18
        expected -2604237975 but got 18446744071105313641
    on line 30 of file "chibi-test.scm"
(bitwise-xor 1694076839 -4290775858)
    FAIL: test-19
        expected -1865418641 but got 2429548655
    on line 31 of file "chibi-test.scm"
(bitwise-xor -193073517 1689392892)
    bitwise/integer: ......................................x............
    50 out of 51 (98.0%) tests passed in 0.012080192565918 seconds.
    1 failure (2.0%).
    FAIL: test-258
        expected -79 but got -78
    on line 102 of file "chibi-test.scm"
(arithmetic-shift -100000000000000000000000000000000 -100)
    bitwise/single: .................xxxxx......xxx..........................x
    49 out of 58 (84.5%) tests passed in 0.013667106628418 seconds.
    9 failures (15.5%).
    FAIL: test-175
        expected -1 but got 4294967295
    on line 134 of file "chibi-test.scm"
(copy-bit 30 -1 #t)
    FAIL: test-176
        expected -1 but got 4294967295
    on line 135 of file "chibi-test.scm"
(copy-bit 31 -1 #t)
    FAIL: test-177
        expected -1 but got 4611686022722355199
    on line 136 of file "chibi-test.scm"
(copy-bit 62 -1 #t)
    FAIL: test-178
        expected -1 but got 9223372041149743103
    on line 137 of file "chibi-test.scm"
(copy-bit 63 -1 #t)
    FAIL: test-179
        expected -1 but got 340282366920938463463374607436063178751
    on line 138 of file "chibi-test.scm"
(copy-bit 128 -1 #t)
    FAIL: test-186
        expected 340282366920938463463374607431768211456 but got 0
    on line 147 of file "chibi-test.scm"
(copy-bit 64 340282366920938463463374607431768211456 #f)
    FAIL: test-187
        expected -340282366920938463463374607431768211456 but got 0
    on line 149 of file "chibi-test.scm"
(copy-bit 64 -340282366920938463463374607431768211456 #f)
    FAIL: test-188
        expected -340282366920938463463374607431768211456 but got 115792089237316195423570985010149409490260605216923310408710492420137293971456
    on line 151 of file "chibi-test.scm"
(copy-bit 256 -340282366920938463463374607431768211456 #t)
    FAIL: test-285
        expected 99 but got 60
    on line 178 of file "chibi-test.scm"
(first-set-bit (expt -2 99))
    bitwise/field: ..........................xxx............xx.
    39 out of 44 (88.6%) tests passed in 0.01202392578125 seconds.
    5 failures (11.4%).
    FAIL: test-205
        expected 340282366920938463463374607431768211456 but got 0
    on line 208 of file "chibi-test.scm"
(bit-field-rotate 340282366920938463463374607431768211456 128 0 64)
    FAIL: test-206
        expected 340282366920938463463374607431768211464 but got 8
    on line 210 of file "chibi-test.scm"
(bit-field-rotate 340282366920938463463374607431768211457 3 0 64)
    FAIL: test-207
        expected 340282366920938463465680450440981905408 but got 2305843009213693952
    on line 212 of file "chibi-test.scm"
(bit-field-rotate 340282366920938463463374607431768211457 -3 0 64)
    FAIL: test-220
        expected -1073741825 but got 18446744072635809791
    on line 230 of file "chibi-test.scm"
(bit-field-reverse -2 0 31)
    FAIL: test-221
        expected -2147483649 but got 18446744071562067967
    on line 232 of file "chibi-test.scm"
(bit-field-reverse -2 0 32)
    bitwise/conversion: ................................
    32 out of 32 (100.0%) tests passed in 0.0238101482391357 seconds.
    bitwise/fold: .......
    7 out of 7 (100.0%) tests passed in 0.0016939640045166 seconds.
228 out of 247 (92.3%) tests passed in 0.0996201038360596 seconds.
19 failures (7.7%).
2 out of 6 (33.3%) subgroups passed.

And here are the failing tests:

  (test "test-16" -2600468497 (bitwise-ior 1694076839 -4290775858))
  (test "test-160" #t (bit-set? 0 1))
  (test "test-161" #f (bit-set? 1 1))
  (test "test-162" #f (bit-set? 1 8))
  (test "test-163" #t (bit-set? 10000 -1))
  (test "test-167" #t (bit-set? 1000 -1))
  (test "test-168" 0 (copy-bit 0 0 #f))
  (test "test-169" 0 (copy-bit 30 0 #f))
  (test "test-17" -184549633 (bitwise-ior -193073517 1689392892))
  (test "test-170" 0 (copy-bit 31 0 #f))
  (test "test-171" 0 (copy-bit 62 0 #f))
  (test "test-172" 0 (copy-bit 63 0 #f))
  (test "test-173" 0 (copy-bit 128 0 #f))
  (test "test-174" -1 (copy-bit 0 -1 #t))
  (test "test-175" -1 (copy-bit 30 -1 #t))
  (test "test-176" -1 (copy-bit 31 -1 #t))
  (test "test-177" -1 (copy-bit 62 -1 #t))
  (test "test-178" -1 (copy-bit 63 -1 #t))
  (test "test-179" -1 (copy-bit 128 -1 #t))
  (test "test-18" -2604237975 (bitwise-xor 1694076839 -4290775858))
  (test "test-180" 1 (copy-bit 0 0 #t))
  (test "test-181" #x106 (copy-bit 8 6 #t))
  (test "test-182" 6 (copy-bit 8 6 #f))
  (test "test-183" -2 (copy-bit 0 -1 #f))
  (test "test-184" 0 (copy-bit 128 #x100000000000000000000000000000000 #f))
  (test "test-185" #x100000000000000000000000000000000 
  (test "test-186" #x100000000000000000000000000000000 
  (test "test-187" #x-100000000000000000000000000000000 
  (test "test-188" #x-100000000000000000000000000000000 
  (test "test-189" 0 (bit-field 6 0 1))
  (test "test-19" -1865418641 (bitwise-xor -193073517 1689392892))
  (test "test-196" 2 (arithmetic-shift 1 1))
  (test "test-197" 0 (arithmetic-shift 1 -1))
  (test "test-190" 3 (bit-field 6 1 3))
  (test "test-191" 1 (bit-field 6 2 999))
  (test "test-192" 1 (bit-field #x100000000000000000000000000000000 128 129))
  (test "test-193" #b111 (bit-field-replace #b110 1 0 1))
  (test "test-194" #b110 (bit-field-replace #b110 1 1 2))
  (test "test-195" #b010 (bit-field-replace #b110 1 1 3))
  (test "test-258" -79 (arithmetic-shift -100000000000000000000000000000000 -100))
  (test "test-175" -1 (copy-bit 30 -1 #t))
  (test "test-176" -1 (copy-bit 31 -1 #t))
  (test "test-177" -1 (copy-bit 62 -1 #t))
  (test "test-178" -1 (copy-bit 63 -1 #t))
  (test "test-179" -1 (copy-bit 128 -1 #t))
  (test "test-186" #x100000000000000000000000000000000 
  (test "test-187" #x-100000000000000000000000000000000 
  (test "test-188" #x-100000000000000000000000000000000 
  (test "test-285" 99 (first-set-bit (expt -2 99)))
      (test "test-205" #x100000000000000000000000000000000 
      (test "test-206" #x100000000000000000000000000000008 
      (test "test-207" #x100000000000000002000000000000000 
  (test "test-220" (bitwise-ior (arithmetic-shift -1 32) #xBFFFFFFF) 
  (test "test-221" (bitwise-ior (arithmetic-shift -1 32) #x7FFFFFFF)

**Comment by ashinn** [comment]
Are you sure you don't have a stale library in your path?  I checked the first two failures and can't reproduce them either on 64-bit OS X or 32-bit Linux.

**Comment by johnwcowan** [comment]
Yes, you were right.  I switched it to (include-shared "srfi/142/bit") and all was well.
