### ISSUE TITLE
SRFI-22: the arguments of main_symbol contains argv[0] incorrectly

### ISSUE THREAD

**Issue by omasanori** [ashinn/chibi-scheme#413]
From [SRFI-22](https://srfi.schemers.org/srfi-22/srfi-22.html):
> Upon invocation of a script, the Scheme system calls a procedure named main with one argument, a list of strings containing the Unix command-line arguments to the script, i.e. the elements of the argv vector of the Scheme script interpreter process from index 1 on. Thus, the first element of the list is the name of the script.

However, Chibi passes `argv[0]`. Thus,
```shell
$ cat test.scm
#! /usr/bin/env scheme-r7rs
(import (scheme r5rs))
(define (main args)
  (display args)
  (newline))
$ chibi-scheme -r test.scm
("chibi-scheme" "test.scm")
```
Another example: the `cat` implementation in the "Example" section of the SRFI:
```scheme
#! /usr/bin/env scheme-r7rs
(import (scheme r5rs))

(define (main arguments)
  (for-each display-file (cdr arguments))
  0)

(define (display-file filename)
  (call-with-input-file filename
    (lambda (port)
      (let loop ()
        (let ((thing (read-char port)))
          (if (not (eof-object? thing))
            (begin
              (write-char thing)
              (loop))))))))
```
When `chibi-scheme -r ./cat ./cat` is executed, the source code is displayed twice. It is not the expected behavior IMHO.

I confirmed with b52711cac8fca57b9f10ea8c6746069cca608dd1 .

**Comment by ashinn** [comment]
Thanks!  However many of the libraries which provide SRFI 22 main procedures (as triggered by the -R option, e.g. in (chibi tar)), assume a leading program argument and need to be updated at the same time.

**Comment by ashinn** [comment]
```
$ ack-grep 'define \(main '
lib/chibi/net/http-server.scm
525:(define (main args) (run-application app-spec args))

lib/chibi/repl.scm
468:(define (main args)

lib/chibi/tar.scm
282:(define (main args)

tests/run/lib/hello.sld
4:    (define (main args)
```

**Comment by omasanori** [comment]
I see. I will update #414.
