### ISSUE TITLE
Invoke `main` procedure by default when argv[0] is `scheme-r7rs` defined by SRFI 22

### ISSUE THREAD

**Issue by omasanori** [ashinn/chibi-scheme#416]
Now Chibi invokes the `main` procedure when `-r` option is passed without an argument. For scripting purpose, however, it is useful if there is a way to invoke `main` without passing any option for using with shebang.

`#!/usr/bin/env chibi-scheme -r` is not suitable for this purpose since multiple arguments in shebang is not portable. In fact, the shebang line above is interpreted as passing the script to "chibi-scheme -r" command on Linux and it does not work as expected.

My proposal is invoking `main` by default when the interpreter is executed as `scheme-r7rs`, the name defined in SRFI 22, instead of changing the default behavior which introduces incompatibility with current behavior (and R7RS semantics; Shiro Kawai told me this point when I considered the idea.)

**Comment by ashinn** [comment]
Do you mean scheme-script?  Sounds reasonable to me, patches welcome otherwise I may not get around to it soon.

**Comment by omasanori** [comment]
> Do you mean scheme-script?

No, I mean `scheme-r7rs` as specified in the third paragraph, "Semantics" section of SRFI 22:

> scheme-rnrs expects code written in RnRS Scheme. scheme-ieee-n-y expects code written in IEEE n-y Scheme. Specifically, scheme-r4rs expects code written in R4RS Scheme, scheme-r5rs expects code written in R5RS Scheme, and scheme-ieee-1178-1990 expects code written in IEEE 1178-1990 Scheme. scheme-srfi-0 expects code written in R5RS Scheme using the extensions specified in SRFI 0. scheme-srfi-7 expects code written in R5RS Scheme using the extensions specified in SRFI 7. 

> Sounds reasonable to me, patches welcome otherwise I may not get around to it soon.

Thanks! I will try.
