### ISSUE TITLE
Snow-chibi fails running tests if files don't exist in current folder

### ISSUE THREAD

**Issue by OpinionatedGeek** [ashinn/chibi-scheme#417]
It looks like snow-chibi fails to change to the working directory when installing from a .tgz file.

For example, here's a sequence of commands that shows the problem. It uses my WIP srfi-19-0.1.tgz file but I imagine it will fail the same way for other files that use `(load "...")` to load files using a relative path.

```
$ mkdir tmp
$ cd tmp
$ cp ../srfi-19/srfi-19-0.1.tgz .
$ ls
srfi-19-0.1.tgz
$ snow-chibi install srfi-19-0.1.tgz
ERROR in "open-input-file": couldn't open input file: "srfi-19.scm"
  called from <anonymous> on line 622 of file /usr/local/Cellar/chibi-scheme/0.7.3/share/chibi/init-7.scm
  called from <anonymous> on line 1039 of file /usr/local/Cellar/chibi-scheme/0.7.3/share/chibi/init-7.scm
  called from <anonymous> on line 542 of file /usr/local/Cellar/chibi-scheme/0.7.3/share/chibi/init-7.scm
  called from <anonymous> on line 622 of file /usr/local/Cellar/chibi-scheme/0.7.3/share/chibi/init-7.scm
Tests failed: /tmp/pkg-22831-1497800567-0/run-tests.scm (details in /tmp/pkg-22831-1497800567-0/test-{out,err}.txt)
Proceed anyway? [y/n]: n
$ tar --strip-components=1 -zxvf srfi-19-0.1.tgz
x srfi-19.scm
x srfi-19.sld
x srfi-19.html
x run-tests.scm
x package.scm
$ ls
package.scm     run-tests.scm   srfi-19-0.1.tgz srfi-19.html    srfi-19.scm     srfi-19.sld
$ snow-chibi install srfi-19-0.1.tgz
All tests passed.
```
It looks like it's trying to run the tests in `run-tests.scm`, which has line `(load "srfi-19.scm")` in it. That file is in the same directory as `run-tests.scm`, but it's not in the current directory which has only the srfi-19-0.1.tgz file.

Is it extracting all the files in the .tgz to a separate folder and then not CD-ing into it? Or is there something else going on? (Or is there something wrong with the way I'm loading files in `run-tests.scm`? I thought I was just doing the same things I'd seen done in other test files.)

**Comment by ashinn** [comment]
Did you use snow-chibi package to build the tgz?

It should search the library path for the file.  If the library is (srfi 19), then the layout should be:

package.scm
srfi/19.sld
srfi/srfi-19.scm  ; or whatever you name the include file

**Comment by OpinionatedGeek** [comment]
Thanks for that. Yes, I'm using snow-chibi to build the tgz. Also, I'm using the version built and installed from the current Chibi source on GitHub (well, current as of a few days ago).

There was no srfi directory - everything was all in the one directory (as it currently is in my [GitHub repo](https://github.com/OpinionatedGeek/SRFI19)).

If I make the srfi directory, and move srfi-19.sld to srfi/19.sld, and move srfi-19.scm to srfi/19.scm (and fix things to load the SCM file from there), when I run:
```
snow-chibi package --version=0.1 \
		--authors="Geoff Taylor <srfi-19@opinionatedgeek.com>" \
		--maintainers="Geoff Taylor <srfi-19@opinionatedgeek.com>" \
		--license=mit --doc=srfi-19.html \
		--test=run-tests.scm srfi/19.sld
```
I get a segmentation fault. I'm not sure what I'm doing wrong...

**Comment by ashinn** [comment]
If you get segfaults, try snow-chibi --noimage.  I'll fix that soon.  Will take a look at this later.

**Comment by ashinn** [comment]
Oh, silly me, I thought you were talking about loading the file from the module system.  (load "srfi-19.scm") is not in general going to work - files get re-arranged, and potentially file suffixes get renamed according to the implementation.  snow-chibi package will in fact move the module itself to the top-level but leave docs and tests nested:

```
$ tar tzvf srfi-19-0.1.tgz 
drwxr-xr-x  0 foof   nobody      0 Jun 29 23:16 srfi-19-0.1/
-rw-r--r--  0 foof   nobody  57312 Jun 29 23:16 srfi-19-0.1/srfi-19.scm
-rw-r--r--  0 foof   nobody   3235 Jun 29 23:16 srfi-19-0.1/srfi-19.sld
drwxr-xr-x  0 foof   nobody      0 Jun 29 23:16 srfi-19-0.1/SRFI19/
-rw-r--r--  0 foof   nobody   1806 Jun 29 23:16 srfi-19-0.1/SRFI19/srfi-19.html
-rw-r--r--  0 foof   nobody  57281 Jun 29 23:16 srfi-19-0.1/SRFI19/run-tests.scm
-rw-r--r--  0 foof   staff     531 Jun 29 23:19 srfi-19-0.1/package.scm
```

You should just (import (srfi 19)), which actually tests that the module is built properly in the test env.

Also, you shouldn't (import (chibi)) but instead (scheme base) and other portable libraries.  (chibi test) is fine since that is portable and already distributed on snow-fort.

**Comment by ashinn** [comment]
Also, better to use --authors="Will Fitzgerald" and keep yourself as maintainer.

**Comment by OpinionatedGeek** [comment]
Thanks for that and all your help with this. It all makes sense when you put it like that...!

I've updated the import statements and it all works as expected now.

I've also updated the authors line - thanks for pointing that out. I somehow missed that when I was going through updating the licensing.
