### ISSUE TITLE
http-get does not pass query string to host

### ISSUE THREAD

**Issue by OpinionatedGeek** [ashinn/chibi-scheme#418]
I've noticed a problem when using `http-get` - it ignores anything in the querystring.

Here's a sample program:
```
#!/usr/bin/env chibi-scheme

(import (scheme base)
        (scheme write)
        (chibi app)
        (chibi io)
        (chibi net http))

(display (port->string (http-get "http://twitrss.me/twitter_user_to_rss/?user=newsycombinator")))
```
This should fetch the RSS XML for the @newsycombinator Twitter feed, but instead it returns the default (the author @ciderpunx's feed).

My inelegant workaround for this is to insert the following at line 175 of /usr/local/share/chibi/chibi/net/http.scm:
```
(if (uri-query uri)
  (begin
    (display "Patching query: " (current-error-port))
    (display (uri-query uri) (current-error-port))
    (newline (current-error-port))
    (display "?" out)
    (display (uri-query uri) out)))
```
I'm sure there's a better way to fix it though!

**Comment by ashinn** [comment]
Thanks!  Can't believe I missed that.

**Comment by ashinn** [comment]
Let me know if you have any problems.
