### ISSUE TITLE
Clang gives warning about shifting a negative signed value on ARM

### ISSUE THREAD

**Issue by kozross** [ashinn/chibi-scheme#425]
When I compile with ``CC=clang CFLAGS=-Werror make`` (to make the warning visible), compilation stops with the following:

    clang -c -DSEXP_USE_NTPGETTIME -DSEXP_USE_INTTYPES -Iinclude  -Wall -g -g3 -O3 -Werror  -fPIC -o sexp.o sexp.c
    sexp.c:2025:37: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
      if (sexp_complex_imag(obj) == SEXP_NEG_ONE)
                                    ^~~~~~~~~~~~
    include/chibi/sexp.h:807:22: note: expanded from macro 'SEXP_NEG_ONE'
    #define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
    include/chibi/sexp.h:804:60: note: expanded from macro 'sexp_make_fixnum'
    #define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
    sexp.c:2383:25: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
      real = (c=='-') ? SEXP_NEG_ONE : SEXP_ONE;
                        ^~~~~~~~~~~~
    include/chibi/sexp.h:807:22: note: expanded from macro 'SEXP_NEG_ONE'
    #define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
    include/chibi/sexp.h:804:60: note: expanded from macro 'sexp_make_fixnum'
    #define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
    sexp.c:3200:36: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
            res = sexp_fx_mul(res, SEXP_NEG_ONE);
                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
    include/chibi/sexp.h:807:22: note: expanded from macro 'SEXP_NEG_ONE'
    #define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^
    include/chibi/sexp.h:804:60: note: expanded from macro 'sexp_make_fixnum'
    #define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                                           ^
    include/chibi/sexp.h:1298:87: note: expanded from macro 'sexp_fx_mul'
    #define sexp_fx_mul(a, b) ((sexp)((((((sexp_sint_t)a)-SEXP_FIXNUM_TAG)*(((sexp_sint_t)b)>>SEXP_FIXNUM_BITS))+SEXP_FIXNUM_TAG)))
                                                                                      ^
    sexp.c:3245:49: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
        res = sexp_make_complex(ctx, SEXP_ZERO, SEXP_NEG_ONE);
                                                ^~~~~~~~~~~~
    include/chibi/sexp.h:807:22: note: expanded from macro 'SEXP_NEG_ONE'
    #define SEXP_NEG_ONE sexp_make_fixnum(-1)
                     ^~~~~~~~~~~~~~~~~~~~
    include/chibi/sexp.h:804:60: note: expanded from macro 'sexp_make_fixnum'
    #define sexp_make_fixnum(n)    ((sexp) ((((sexp_sint_t)(n))<<SEXP_FIXNUM_BITS) + SEXP_FIXNUM_TAG))
                                         ~~~~~~~~~~~~~~~~~~^
    4 errors generated.
    make: *** [Makefile:109: sexp.o] Error 1

This is Clang version 4.0.1, as per ``clang --version`` on ARM (a BananaPi M1 with a Cortex A9).

**Comment by ashinn** [comment]
Does this arch not actually do the same thing as everywhere else on negative  shifts?  I've compiled on an raspberry pi without problems.  It may be expensive to work around this so I'll conditionally include the fix.

**Comment by kozross** [comment]
This is [UB for C][1] (even if it's not at assembly level), which makes it somewhat unsafe to rely on (given that compilers could, in theory, 'optimize' it into whatever they please). This warning has also come up for me on x86 with Clang version 4.0.1, and apparently, a [few other projects have been affected too][2]. This is probably something worth fixing.

[1]: https://stackoverflow.com/questions/40508958/shifting-a-negative-signed-value-is-undefined/40509974#40509974
[2]: https://github.com/madler/zlib/issues/183

**Comment by mnieper** [comment]
This is issue #321.
