### ISSUE TITLE
Some packaged SRFIs aren't installed

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#427]
The Makefile is out of sync with the SRFIs actually available.  Patch attached.

[Makefile.diff.txt](https://github.com/ashinn/chibi-scheme/files/1159779/Makefile.diff.txt)

**Comment by johnwcowan** [comment]
Oops, left out 125.  Revised patch attached.

[Makefile.diff.txt](https://github.com/ashinn/chibi-scheme/files/1160600/Makefile.diff.txt)

**Comment by ashinn** [comment]
Thanks!  Applied.  Pull requests also accepted.
