### ISSUE TITLE
Segmentation fault reading circular structure

### ISSUE THREAD

**Issue by jahs** [ashinn/chibi-scheme#428]
The following segfaults on chibi-scheme 0.7.3 "nitrogen" (chibi r7rs ratios complex threads full-unicode modules dynamic-loading bsd macosx little-endian). This works in e.g. chez, SISC.

`(read (open-input-string "#0=(1 #0#)"))`

**Comment by ashinn** [comment]
Default read/write handle circular structure just fine, however the basic repl uses write-simple.  Use chibi-scheme -R for the advanced repl which prints circular structures, or call write explicitly.

**Comment by jahs** [comment]
Ah, I see. Apologies. I now see the -R option in the man page. I missed it as --help says
  -R[<module>] - run main from a module
but I see if <module> is omitted it defaults to the advanced REPL: perhaps add to the help?

Many thanks for your work on Scheme and chibi.
