### ISSUE TITLE
9front port

### ISSUE THREAD

**Issue by joe9** [ashinn/chibi-scheme#451]
Hello,

Thanks for sharing chibi-scheme.

I am trying to port chibi-scheme to 9front (a more active derivative of Plan9). I could get all the compile errors fixed except for the usage of fabsl in sexp.c.: sexp_read_float_tail function.

This is the corresponding line:
    val = fabsl(e) > 320 ? exp(log(val) + e*M_LN10) : val * pow(10, e);

The compile errors are:
chibi-scheme/sexp.c:2495[sexp.c:9170] function args not checked: fabsl
chibi-scheme/sexp.c:2495[sexp.c:9170] name not declared: M_LN10
mk: 6c -p -Iinclude ...  : exit status=rc 5236: 6c 5252: error

This is the full mk output:
	 :glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; mk
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 gc.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 sexp.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 bignum.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 opcodes.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 plan9.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 vm.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 simplify.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 eval.c
6c -p -Iinclude -DPLAN9 -DSEXP_USE_GREEN_THREADS=0 main.c
/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/sexp.c:2495[sexp.c:9170] function args not checked: fabsl
/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme/sexp.c:2495[sexp.c:9170] name not declared: M_LN10
mk: 6c -p -Iinclude ...  : exit status=rc 5236: 6c 5252: error
:glenda@cirno:/mnt/term/home/j/dev/apps/plan9/custom/lisp/chibi-scheme; 

This is what I have done so far: http://okturing.com/src/1998/body . I plan on submitting a pull request after I have the above issue with fabsl resolved.

Any thoughts, please?

Thanks again

**Comment by joe9** [comment]
or, I could mask the usage of fabsl and M_LN10 with this patch:
`
diff --git a/sexp.c b/sexp.c
index 1503e5b2..ed98ad94 100644
--- a/sexp.c
+++ b/sexp.c
@@ -2491,8 +2491,13 @@ sexp sexp_read_float_tail (sexp ctx, sexp in, double whole, int negp) {
     }
 #endif
   }
+
+#ifdef PLAN9
+  if (e != 0.0) val *= pow(10, e);
+#else
   if (e != 0.0)
     val = fabsl(e) > 320 ? exp(log(val) + e*M_LN10) : val * pow(10, e);
+#endif
 #if SEXP_USE_FLONUMS
   res = sexp_make_flonum(ctx, val);
 #else
--
2.13.6
`

**Comment by ashinn** [comment]
You should be able to #define fabsl fabs if it's not defined.

**Comment by ashinn** [comment]
Thanks!  A pull request is easier to view the diff, and then you get proper credit when merged.

**Comment by joe9** [comment]
https://github.com/ashinn/chibi-scheme/pull/452 is the corresponding pull request.
