### ISSUE TITLE
error while loading shared libraries: libchibi-scheme.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kekemoto** [ashinn/chibi-scheme#457]
I did.
```
$ git clone https://github.com/ashinn/chibi-scheme.git
$ cd chibi-scheme
$ make && make test
$ make install
$ chibi-scheme
```
Result:
```
chibi-scheme: error while loading shared libraries: libchibi-scheme.so.0: cannot open shared object file: No such file or directory
```
I referred to #379.
And I checked.
```
$ echo $LD_LIBRARY_PATH
/usr/local/lib:
```
Environment
OS : CentOS 6.9  
Compiler : GCC 4.4.7
chibi-scheme version : 0.8

**Comment by ashinn** [comment]
Is LD_LIBRARY_PATH exported?  Is libchibi-scheme.so.0 in /usr//local/lib?  What does ldd `which chibi-scheme` say?

**Comment by kekemoto** [comment]
```
$ echo $PATH
/home/keke/.rbenv/shims:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/keke/bin:/usr/local/lib:/home/keke/.rbenv/bin

$ ls /usr/local/lib | grep libchibi-scheme.so.0
libchibi-scheme.so.0
libchibi-scheme.so.0.8.0

$ witch chibi-scheme
bash: witch: Command not found

$ type chibi-scheme
chibi-scheme is hashed (/usr/local/bin/chibi-scheme)
```

**Comment by ashinn** [comment]
`which` (the question), not `witch` (the magic user), but `type` gives the same info.

Please `export LD_LIBRARY_PATH` if you're not already doing so.  You didn't give the output of `ldd`.  The output of `strace chibi-scheme` would also be helpful to see if it's actually trying to open the .so.

I don't have access to a CentOS machine at the moment but this works fine on other Linux distros so I'd be surprised if this wasn't just some simple env problem.

**Comment by kekemoto** [comment]
```
$ export LD_LIBRARY_PATH
$ chibi-scheme
> (+ 1 2)
3
```
I am sorry that my English is not good.
Thank you very much!

**Comment by ashinn** [comment]
Glad it works!
