### ISSUE TITLE
Useless (?) cell lookup while resolving references (in chibi source code)

### ISSUE THREAD

**Issue by mgubi** [ashinn/chibi-scheme#458]
The following code in `eval.c` creates a new reference 
```
static sexp sexp_env_cell_create (sexp ctx, sexp env, sexp key,
                                  sexp value, sexp *varenv) {
  sexp cell = sexp_env_cell_loc(ctx, env, key, 0, varenv);
  if (!cell) cell = sexp_env_cell_define(ctx, env, key, value, varenv);
  return cell;
}
```
However it is only called from `analyze_var_ref` as follows:
```
  cell = sexp_env_cell_loc(ctx, env, x, 0, varenv);
  if (! cell) {
    cell = sexp_env_cell_create(ctx, env, x, SEXP_UNDEF, varenv);
  }
```
so maybe one of the two `sexp_env_cell_loc` can be saved.

**Comment by ashinn** [comment]
Thanks, good observation!  I don't think this is worth optimizing though, and as a general utility sexp_env_cell_create is safer if it first checks for existence.
