### ISSUE TITLE
Datum labels revisited

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#464]
> (define x '(#1=(a b) #1#))
> (write-shared x)
((a b) (a b))
> (eq? (car x) (cadr x))
#f 
This is contrary to the behavior of Gauche, MIT, Bigloo, Kawa, Chez, Ikarus/Vikare, Larceny (in R5RS/R7RS mode), Mosh, STklos, FemtoLisp, Sagittarius, Foment, Picrin, which return #t.

**Comment by ashinn** [comment]
The `quote` core form walks and strips syntax from its argument.  Using R7RS read this works as expected:

`(define x (read (open-input-string "(#1=(a b) #1#)")))`

There is some logic in `quote` to detect simple loops, I may see if I can improve it for this, but I don't think it's required by the standard and nobody writes code like this in practice.

**Comment by ashinn** [comment]
I'm kind of sick of people reporting this, so I've reversed the logic.  Now unless we know there's a syntactic closure which needs to be unwrapped by quote, we don't bother unwrapping the form at all, and if we get caught in a loop before seeing a synclo we assume there is none.

This will generally work as expected.  In the event that you have a cyclic structure with synclos this might break, but that's probably not possible anyway.

**Comment by mnieper** [comment]
The current implementation of `sexp_contains_syntax_p_bound` is buggy.  The following program should print `(#f . x)` but does print `(#f . {Sc ...})`.

```scheme
(import (scheme base)
	(scheme write))

(define-syntax foo
  (syntax-rules ()
    ((foo)
     '(#f . x))))

(display (foo))
(newline)
```

The statement at https://github.com/ashinn/chibi-scheme/blob/master/eval.c#L627 does not look right.  I would replace the whole `if` statement by `return sexp_contains_syntax_p_bound(ls1, depth-1)`.

I noticed this during my repair of SRFI 148.
