### ISSUE TITLE
`exit` with inexact integer signals error

### ISSUE THREAD

**Issue by jacius** [ashinn/chibi-scheme#467]
Calling `exit` with an inexact integer on a non-plan9 system causes an error:

```
> (exit 42.0)
ERROR in "%exit": invalid type, expected Integer: 42.0
```

R7RS says "The `exit` procedure must not signal an exception or return to its continuation," which is why I consider this a bug.

I think the problem is here: https://github.com/ashinn/chibi-scheme/blob/278911e93c8a0738217ecf2fe43d8252ba773ba9/lib/chibi/process.scm#L13

Possible solutions are:

1. Convert to an exact integer in the then-branch
2. Change the test from `integer?` to `exact-integer?`, which would mean inexact integers result in exit code 1, like inexact non-integers do

It's a simple fix either way, but I'm not sure which you prefer, so I didn't make a pull request.

**Comment by ashinn** [comment]
Thanks for the report!  Went with option 1.
