### ISSUE TITLE
apply is too lax

### ISSUE THREAD

**Issue by jacius** [ashinn/chibi-scheme#468]
Currently, chibi allows some invalid calls to `apply`.

The R7RS standard indicates that the final argument, `args`, is required and must be a list:

```
(apply proc arg1 ... args)

The apply procedure calls proc with the elements of the list
(append (list arg1 ... ) args) as the actual arguments.
```

Interestingly, I think this is the only time a `...` appears in a non-terminating position in a procedure signature anywhere in the R7RS small standard. In this case the `...` applies to `args1`, which means that `args` is required. It is implied by `(append (list arg1 ... ) args)` that `args` must be a list. Other Scheme implementations require `args` to be provided, and to be a list.

Based on that description, there are two situations where chibi should signal an error, but currently does not.

### 1. Missing args list

First, `(apply proc)` should signal an error that not enough arguments were given. But currently `apply` is defined so that  behaves the same as `(proc)`:

https://github.com/ashinn/chibi-scheme/blob/10759e8bdb62d4e596a2631271e586ff6d1d7661/lib/init-7.scm#L46-L51

I think the solution to this is just to change line 48 to raise a "too few arguments" exception instead of calling `(proc)`.

### 2. Non-list final argument

The second situation is if the final argument is not a list, such as `(apply list 'a 'b)`. It should signal a type error, but instead it silently ignores the final argument. `(equal? (apply list 'a 'b) (list 'a))`

I'm not sure what is the cause of that exact behavior. Looking at the code, I think `sexp_append2` assumes the second argument is a list, so it builds an improper list by consing. And probably, somewhere deep in the implementation of `apply1`, I guess something loops until it finds a cdr which is not a pair, and assumes that it found the terminating empty list, so the value in the final cdr is ignored.

Whatever the cause is, a simple solution would be add a `(list? (car lol))` check in the lambda inside `apply`, and raise a type exception if it is not. The downside is that this check would impact performance of every call to `apply`.

If these solutions are acceptable to you, I can submit a pull request.

**Comment by ashinn** [comment]
+1 to the first fix.  Maybe this is better:

```
(define (apply proc arg1 . args)
  (if (null? args)
      (apply1 proc arg1)
      ((lambda (lol)
         (apply1 proc (append2 (reverse (cdr lol)) (car lol))))
       (reverse (cons arg1 args)))))
```

For the latter it would be better to add a check in vm.c when unwrapping the args for SEXP_OP_APPLY1, then there's minimal performance impact.

**Comment by jacius** [comment]
Thanks for pointing me in the right direction. vm.c is pretty intimidating but I'll see if I can figure it out.

**Comment by ashinn** [comment]
It's a pretty easy change for me.  If you're specifically interested in playing with the vm then have fun, otherwise I'll do it :)

**Comment by jacius** [comment]
I'm interested in a puzzle, so I'll give it a try. After looking at it for a while, I think I understand it enough to make a crude fix. I changed this part...

https://github.com/ashinn/chibi-scheme/blob/10759e8bdb62d4e596a2631271e586ff6d1d7661/vm.c#L1177-L1181

...to this:

```c
    {
      int prev_top = top;
      for (top=fp-j+i-1; sexp_pairp(tmp2); tmp2=sexp_cdr(tmp2), top--)
        stack[top] = sexp_car(tmp2);
      top = fp+i-j+1;
      fp = k;
      /* if final cdr of tmp2 isn't null, then args list was improper */
      if (! sexp_nullp(tmp2))
        sexp_raise("improper args list", sexp_list1(ctx, stack[prev_top-2]));
    }
    goto make_call;
```

I added the braces so that `prev_top` will go out of scope. There may be a way to refer to the original args list without introducing another variable.

I tried adding the check immediately after the `for` loop, but that caused a segfault. I guess because it left `top` in a bad state.

This change seems to work, although maybe there is some cleanup that should be done to restore the stack to a previous state? What do you think? Am I on the right track?

**Comment by ashinn** [comment]
Looks good - I think you can move the check to before setting top & fp, then you don't need prev_top.

**Comment by jacius** [comment]
Unfortunately, moving the check before setting `top` causes a segfault. The loop modifies `top` as it traverses `tmp2`, so `prev_top` is (I believe) necessary to remember what `top` was before the loop.

I will submit a pull request in a minute, which has one more improvement: it resets `top` to `prev_top` before raising the error. I think that should effectively pop the (unused) arguments from the stack, so that the stack space is not wasted. If I'm wrong about that, or you can think of a better way to do things, I of course won't be offended if you modify the code.
