### ISSUE TITLE
`PREFIX="..." make install` fails

### ISSUE THREAD

**Issue by jhidding** [ashinn/chibi-scheme#470]
If I do a `make install` with PREFIX set, I get an error generating `red.img` and `snow.img`

```
cd / && LD_LIBRARY_PATH="/home/johannes/.local/pkg/chibi-scheme/lib:/home/johannes/.local/lib:" DYLD_LIBRARY_PATH="/home/johannes/.local/pkg/chibi-scheme/lib:" /home/johannes/.local/pkg/chibi-scheme/bin/chibi-scheme -mchibi.snow.commands -mchibi.snow.interface -mchibi.snow.package -mchibi.snow.utils -d /home/johannes/.local/pkg/chibi-scheme/share/chibi/snow.img
ERROR: couldn't find file in module path: "init-7.scm"
Makefile:402: recept voor doel 'install' is mislukt
make: [install] Fout 70 (genegeerd)
```

(apologies for the Dutch in the messages, 'mislukt' means 'failed' ;)

**Comment by jhidding** [comment]
To elaborate, my setup is as follows: I install packages in `~/.local/pkg/`, then use `xstow` to put symlinks into the `~/.local` prefix. If I define `export CHIBI_MODULE_PATH="${HOME}/.local/share/chibi:${HOME}/.local/lib/chibi"`, the installed chibi interpreter works fine. Also, doing this and trying to run `PREFIX="..." make install` again, the install completes successfully.

**Comment by weinholt** [comment]
`include/chibi/install.h` is not rebuilt when PREFIX= changes. Perhaps that is what happened here, your `install.h` file has a different path than where you installed to? Running "make cleaner" would help.

**Comment by ashinn** [comment]
Right, you need to use the same PREFIX=... in make and in make install.  This is how the use of PREFIX is shown in the manual.

**Comment by lassik** [comment]
If you've already managed to generate a `include/chibi/install.h` with the wrong `sexp_default_module_path`, that file won't be regenerated even if you call `make` with a different prefix. Even `make clean` doesn't get rid of it.

**Comment by ashinn** [comment]
`make cleaner`
