### ISSUE TITLE
Character name case sensitivity

### ISSUE THREAD

**Issue by jacius** [ashinn/chibi-scheme#471]
Currently, character names in chibi are case insensitive, i.e. `#\space` and `#\SPACE` are both read as the same thing. But R7RS says that character names are case sensitive (section 6.6):

> Case is significant in `#\<character>`, and in `#\<character name>`, but not in `#\x<hex scalar value>`.

On the other hand, it also says:

> The following character names must be supported by all implementations with the given values. Implementations may add other names provided they cannot be interpreted as hex scalar values preceded by `x`.

So one could argue that chibi is just implicitly adding every possible case variant of the names as an alias for the lowercase names.

I don't know if you consider this a bug, but I wanted to at least bring it to your attention so you can decide.

If you do decide it is a bug, the fix is changing `strcasecmp` to `strcmp` here:
https://github.com/ashinn/chibi-scheme/blob/10ed000e1bd2c88d884f64a70083313cdd6e089a/sexp.c#L3122-L3127

**Comment by jimrees** [comment]
Note that #!fold-case is supposed to enable case-insensitivity in identifiers and character names - so the suggested fix is not complete.

**Comment by ashinn** [comment]
Yes, I think this should be fixed as a bug, but as you note respecting the reader case sensitivity.
