### ISSUE TITLE
unbound identifiers always match bound literals

### ISSUE THREAD

**Issue by jimrees** [ashinn/chibi-scheme#472]
> (eval '(cond (else 'ok)) (environment '(except (scheme base) else)))
    > ok

..and similarly,

    (define-library (contrib smalltest)
      (export macro)
      (import (scheme base))
      (begin
        (define cadazzle 42)   ;; non-exported library-local binding
        (define-syntax macro
          (syntax-rules (cadazzle)
            ((_ cadazzle) 'yes)
            ((_ other) 'no)))))

    > (import (contrib smallest))
    > (macro foo)
    no
    > (macro cadazzle)
    yes

The R7RS spec is unclear about the case where the literal is not bound, but that doesn't apply here -- the input expression must have the same binding as the literal.    If the input is not bound, then it definitely does not have the same binding as a literal that is bound.

This seems like something that would have been caught years ago, so I would be interested to know if this was a deliberate design decision for Chibi and what the reasoning is.

**Comment by ashinn** [comment]
Yes, it is a deliberate (configurable) decision, explained in the docs (http://synthcode.com/scheme/chibi/#h3_SchemeStandard):

> In R7RS (and R6RS) semantics it is impossible to use two macros from different modules which both use the same auxiliary keywords (like else in cond forms) without renaming one of the keywords. By default Chibi considers all top-level bindings effectively unbound when matching auxiliary keywords, so this case will "just work". This decision was made because the chance of different modules using the same keywords seems more likely than user code unintentionally matching a top-level keyword with a different binding, however if you want to use R7RS semantics you can compile with SEXP_USE_STRICT_TOPLEVEL_BINDINGS=1.

If you're mentioning this because it broke for you I'm very curious to hear since it means my assumption is wrong!

Either way, I get this same duplicate bug quite a lot and need to make the deviation more clear, or give up and just switch the default.
