### ISSUE TITLE
Reading +inf.0+0i

### ISSUE THREAD

**Issue by jacius** [ashinn/chibi-scheme#474]
Chibi signals an error when it reads a literal complex number with `+inf.0` or `-inf.0` as the real part and non-decimal `0` as the imaginary part:

```
> +inf.0+0i
ERROR on line 1: invalid complex infinity: 0
> -inf.0+0i
ERROR on line 2: invalid complex infinity: 0
> +inf.0-0i
ERROR on line 3: invalid complex infinity: 0
> -inf.0-0i
ERROR on line 4: invalid complex infinity: 0
```

As far as I have seen, it is only the combination of infinity real and non-decimal 0 imaginary that causes a problem. It is fine to have only one or the other, but not both. For example, these all work:

```
+inf.0+0.0i  ; decimal `0.0` as imaginary
+inf.0+0.i   ; decimal `0.` as imaginary
+inf.0+.0i   ; decimal `.0` as imaginary
+inf.0+1i    ; non-zero integer as imaginary
1+0i         ; non-infinity as real
```

**Comment by ashinn** [comment]
Thanks!  Fixed.
