### ISSUE TITLE
sexp_write_one when sizeof(long) < sizeof(sexp_sint_t)

### ISSUE THREAD

**Issue by tramboi** [ashinn/chibi-scheme#479]
sexp_write_one assumes unbox_fixnum result is not truncated by casting to long.
snprintf(numbuf, NUMBUF_LEN, "%ld", (long)sexp_unbox_fixnum(obj));
It's not always the case, but I don't really know how to fix this portably. Using long long and %lld seems a no-brainer but is it portable enough ?

**Comment by okuoku** [comment]
Aside Plan9, I guess we can safely assume C99 `<stdint.h>` so we could:

```c
#if SEXP_64_BIT
#define SEXP_PRIdFIXNUM PRId64
#else
#define SEXP_PRIdFIXNUM PRId32
#endif
```

then,

```c
snprintf(numbuf, NUMBUF_LEN, "%" SEXP_PRIdFIXNUM, sexp_unbox_fixnum(obj));
```

**Comment by tramboi** [comment]
Good enough for me, I'm pretty much into fixed size types, easier to reason
about.

2018-06-28 15:25 GMT+02:00 okuoku <notifications@github.com>:

**Comment by ashinn** [comment]
When is it the case that a fixnum doesn't fit in a long?

**Comment by tramboi** [comment]
On MSVC x64, SEXP_64_BIT=1, sizeof(long) = 4

2018-06-29 7:53 GMT+02:00 Alex Shinn <notifications@github.com>:

**Comment by ashinn** [comment]
Oh, right... MSVC is psychotic. Pushed a fix.

Just noticed the recent commits broke reading floating point (0.3 is not 0.3), investigating.

**Comment by tramboi** [comment]
C standard is a bit crazy too, what does long and long long mean any way :)


2018-06-29 16:47 GMT+02:00 Alex Shinn <notifications@github.com>:
