### ISSUE TITLE
(chibi bytevector) should be enhanced with R6RS native IEEE procedures

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#489]
The native IEEE conversions from `(rnrs bytevector (6))`should be provided as part of `(chibi bytevector)`, as they are trivial to implement in C with `memcpy()` and painful to implement in Scheme.  Here is a spec, a lightly edited extract from R6RS:

`(bytevector-ieee-single-native-ref `_bytevector k_`)`

_K, ..., k_ + 3 must be valid indices of _bytevector_, and _k_ must be a multiple of 4.

Returns the inexact real number that best represents the IEEE-754 single-precision number represented by the four bytes beginning at index _k_.

`(bytevector-ieee-double-native-ref `_bytevector k_`)`

_K, ..., k_ + 7 must be valid indices of _bytevector_, and _k_ must be a multiple of 8.

Returns the inexact real number that best represents the IEEE-754 double-precision number represented by the eight bytes beginning at index _k_ .

`(bytevector-ieee-single-native-set! `_bytevector k x_`)`

K, ..., _k_  + 3 must be valid indices of _bytevector_, and _k_  must be a multiple of 4.

Stores an IEEE-754 single-precision representation of _k_ into elements _k_ through _k_ + 3 of _bytevector_, and return an unspecified value.

`(bytevector-ieee-double-native-set! `_bytevector k x_`)‌‌`

_K_, ..., _k_  + 7 must be valid indices of _bytevector_, and _k_ must be a multiple of 8.

Stores an IEEE-754 double-precision representation of _x_ into elements _k_  through _k_  + 7 of _bytevector_, and return an unspecified value.

**Comment by ashinn** [comment]
Chibi now provides `(scheme bytevector)` with these procedures.
