### ISSUE TITLE
Core types are not available by name, per docs for (chibi ast)

### ISSUE THREAD

**Issue by edw** [ashinn/chibi-scheme#505]
The docs for [(chibi ast)](http://synthcode.com/scheme/chibi/lib/chibi/ast.html) say:

> The following core types are also available by name, and may be used in the `match ($ ...)` syntax.

Also, `<hash-table>` seems conspicuously absent from the documented list.

If implementing this requires some grunt work, please point me in the right direction and I'll put together a pull request. I need to implement these for my own work and would rather they be inside Chibi.

**Comment by ashinn** [comment]
Exporting the Hash-Table name would only allow you to match on the record fields: buckets, size, hash-fn, eq-fn.  The buckets are a vector of alists.  This wouldn't be useful for pattern matching.

What you presumably want is the ability to match a subset of key-value pairs in the table, which would need to be added to match.scm.  A possible syntax is:

```(Hash-Table (key1 value1) (key2 value2))```

presumably requiring the keys to be literals to avoid expensive quadratic matching.

**Comment by edw** [comment]
What you suggest — adding hash-table support to the match macro — would be a wonderful enhancement, but it's not the reason I'm looking for these type names. I've developed a Clojure-style protocol-based dynamic dispatch facility, and I keep a data structure of protocol names to type values. The table is used to look up the implemented methods of a protocol on a given type. The code is here:

https://github.com/thunknyc/i7t/blob/master/lib/thunknyc/i7t.scm#L297

When extending a type to support a protocol, it is from a user-interface perspective much more clear to specify e.g. `<hash-table>` than something like `(type-of (hash-table equal?))`. Example usages conclude the file referenced above.

I've written an incomplete implementation of the type names listed in the `(chibit ast)` docs in the following code:

https://github.com/thunknyc/i7t/blob/master/lib/thunknyc/types.sld

The implementation is kludgy in that it derives the types by querying exemplars of each type.

**Comment by ashinn** [comment]
Sorry, I misread your complaint because the type names *are* exported, but realize now they had not been updated since changing the type naming convention from <common-lisp> to Upper-Case.
