### ISSUE TITLE
make install fails for uvprim.so

### ISSUE THREAD

**Issue by ecraven** [ashinn/chibi-scheme#510]
Compiling git head works fine, but make install then fails:
```
install: cannot stat 'lib/srfi/160/uvprim.so': No such file or directory
```
Am I doing something incorrect here? This happens for the arch linux PKGBUILD (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chibi-scheme-git).

Thanks for any assistance

**Comment by ashinn** [comment]
Thanks for the report!  This was a typo fixed in pr #509.
