### ISSUE TITLE
Two minor issues with (chibi monad environment)

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#516]
While I have been studying SRFI 159, I have taken a look at Chibi's implementation of the environment monad [1].

There are two minor issues:

(1) The environment variables of the environment monad as it is currently implemented are syntactically symbols, not identifiers. However, in the record-type definition [2], they are used as field names of R7RS records. If record field names are interpreted as identifiers and not as symbols (which was the intention of WG 1), there is a mismatch that will lead to errors if `define-environment-monad` is used in a context where two identifiers have the same meaning but are represented by different symbols and these symbols are used as predefined fields for the environment monad.

The solution is to generate a temporary identifier for each predefined field that is used in the record-type definition.

(2) In the definition of `local`, the values are evaluated each time the dynamic context with the local bindings is entered [3]. This is in contrast to how `parameterize` works. However, SRFI 159 says that its `with`, which is `local` in disguise is conceptually the equivalent of `parameterize`. So in the definition of `local`, the values should be evaluated once outside `dynamic-wind` and stored in temporary variables.

--
[1] https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/monad/environment.scm
[2] https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/monad/environment.scm#L106
[3] https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/monad/environment.scm#L178

**Comment by mnieper** [comment]
If found a third issue:

(3) In the definition of the sequence operator [4], the case of one monadic value `(sequence f)` behaves differently to the case of two or more monadic values `(sequence f g)`. In the former case, `f` is evaluated when the `(sequence f)` is evaluated. In the latter case, `f` and `g` are not evaluated before the resulting monadic value `(sequence f g)` is being run.

We probably want the former behavior in all cases.

(The same is true for the evaluations of the values in `local` and `local!' and the evaluation of the body of the former.)

[4] https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/monad/environment.scm#L161

**Comment by ashinn** [comment]
Fixed, though this should probably be deprecated in favor of (srfi 165).
