### ISSUE TITLE
fits-in-width in (chibi show pretty) broken

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#518]
`fits-in-width` in `(chibi show pretty)` runs a second environment monad using `show`:

https://github.com/ashinn/chibi-scheme/blob/d1bb4c27a454e60f58fa7302eac778c5a1d8d52c/lib/chibi/show/pretty.scm#L82

This is wrong as `proc` (in that procedure) may reference state variables, which are reset to their defaults in the new environment monad.

The solution is to rewrite `fits-in-width` and `fits-in-columns` with `call-with-output`. This means that both procedures would have to return formatters. Either the technique of `try-fitted2` with an explicit continuation or SRFI 165, which allows non-void monadic values, can be used.

**Comment by ashinn** [comment]
The original fits-in-width from fmt uses continuations, and I was being lazy when porting to show.  It should still use continuations - not call-with-output.
