### ISSUE TITLE
Does Chibi support sandboxing?

### ISSUE THREAD

**Issue by lighth7015** [ashinn/chibi-scheme#519]
I was wondering if Chibi supported limiting I/O (e.g. by restricting filesystem and/module importing), for embeddong in an app that has security concerns.

**Comment by ashinn** [comment]
Yes, there are no backdoors in "eval," so if you create an environment that has neither I/O nor import, untrusted code can be safely evaluated without security concerns.

The remaining concern is to avoid DoS, so you'd probably want to limit the amount of CPU and memory consumed.  A time-limit is easy by just running in a separate thread and killing after a certain time, but memory-limiting would take a little work. Similarly, there are likely remaining corner cases where you can segfault Chibi - I fix these as I find them but have not done a full security audit.

**Comment by lighth7015** [comment]
So how would I create an environment without import or I/O?

**Comment by ashinn** [comment]
```
> (define sandbox (environment '(scheme base)))
> (eval '(map square '(1 2 3)) sandbox)
(1 4 9)
> (eval '(import (scheme file)) sandbox)
ERROR: undefined variable: file
Searching for modules exporting file ...
... none found.
> 
```

**Comment by lighth7015** [comment]
Huh, so I just have to load sandbox before I start executing user code?

**Comment by jacobstern** [comment]
Hi @ashinn, I'm trying to achieve this scenario (embedding a sandboxed environment in C++) but struggling how to achieve this result in C code.

So far I have:

```cpp
    m_ctx = sexp_make_eval_context(nullptr, nullptr, nullptr, 0, 0);
    auto env = sexp_load_standard_env(m_ctx, nullptr, SEXP_SEVEN);
    sexp_load_standard_ports(m_ctx, env, stdin, m_outfile, stderr, 1);
```

in my initialization function, but the `environment` function doesn't seem to be bound in the default environment and it's unclear how to instantiate a new environment using C. Could you possibly provide a pointer here?

**Comment by johnwcowan** [comment]
The `environment` procedure is in the library `(scheme eval)`, which must be imported.

[SRFI 172](http://srfi.schemers.org/srfi-172/srfi-172.html) is an ongoing attempt to define libraries that list only the less-unsafe procedures of R7RS-small.

**Comment by jacobstern** [comment]
Thanks for responding! I'm no longer working on that experiment but I appreciate the clarification. (Also apologies since I obviously didn't understand R7RS libraries when I wrote the question.)
