### ISSUE TITLE
(- 0.0) => -0.0

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#523]
Currently `(- 0.0) => 0.0` in Chibi, whereas in Gambit, Guile, Chicken, Kawa, and Chez at least the result is `-0.0`.  In other words, these systems flip the sign bit in accordance with the IEEE `negate` function, whereas Chibi treats `(- 0.0)` as synonymous with `(- 0.0 0.0)`, which IEEE explicitly says does not need to be the case, though for all other flonums there is no difference between the two interpretations.

**Comment by ashinn** [comment]
Chibi treats (- x) as (- 0 x), and that won't change, but I accept the argument that (- 0 0.0) should be -0.0.
