### ISSUE TITLE
Getting string representation of type name

### ISSUE THREAD

**Issue by lighth7015** [ashinn/chibi-scheme#524]
Is it possible to find the string representation of a `sexp` type name?

**Comment by ashinn** [comment]
From C `sexp_type_name`, from Scheme `type-name` in `(chibi ast)`.

**Comment by lighth7015** [comment]
Well, I tried getting type name of a `sexp_fixnum`, and it segfaults.

**Comment by ashinn** [comment]
Sorry, you said get the string representation of a type, not of an instance of a type.

If it's a heap allocated object (`sexp_pointerp` returns true) you can use `sexp_object_type_name(ctx, obj)`.

You can use something like `sexp_type_of` in (chibi ast) to handle immediate values as well.
