### ISSUE TITLE
Comparison of big negative bignums fails

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#541]
;; Tested this on the current HEAD
(define smallest-s64  -9223372036854775808)
(define really-small-bignum 100000000000000000000000000)
(< smallest-s64 really-small-bignum) => #t 
(<= smallest-s64 really-small-bignum) => #t 
(> really-small-bignum smallest-s64) => #t 
(>= really-small-bignum smallest-s64) => #t

**Comment by ashinn** [comment]
I think you wanted really-small-bignum to be negative.  Nice catch, surprised this hadn't been found.
