### ISSUE TITLE
Win32: Fix embedding for Windows

### ISSUE THREAD

**Issue by okuoku** [ashinn/chibi-scheme#543]
It seems `SEXP_API` assumes it can export a variable; which is not really true on Win32/64.

**Comment by okuoku** [comment]
Perhaps we need;

1) Drop DLL build entirely: https://github.com/okuoku/chibi-scheme/commit/b4e8e9603d6f10e027b683f0f23f3f8ba48d3503 

or

2) Adjust DLL build specifically for Win32

@ashinn : I guess we need to support both static-library and DLL. Give me some time for proposal...

**Comment by ashinn** [comment]
@okuoku , both is best, I'm thinking DLL support is more important than the static build.
