### ISSUE TITLE
lib/init-7.scm has syntax error

### ISSUE THREAD

**Issue by Beu** [ashinn/chibi-scheme#545]
My original r7rs token/datum parser says that lib/init-7.scm has syntax error on line 874:

`(_len ((rename'len))  (_length (rename 'length*))`

Maybe whitespace is needed between `rename` and `'len`.
Why is there different from the other ways to rename (`lambda`, `let`, `begin`, ... and so on)?

**Comment by ashinn** [comment]
just a typo
