### ISSUE TITLE
snow-chibi.scm ignores proxy environment

### ISSUE THREAD

**Issue by ceving** [ashinn/chibi-scheme#549]
The command

    $ snow-chibi show names

tries to access a web server directly

    $ lsof -n -p $! -a -i
    COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
    chibi-sch 30917  szi    4u  IPv4 650009      0t0  TCP 198.51.100.236:49198->69.164.211.140:http (SYN_SENT)

although the proxy environment has been set.

**Comment by ashinn** [comment]
Do you mean the http_proxy env var?  This is not currently supported by `(chibi net http)`, though I can consider adding it.
In the meantime you can set `(use-curl? #t)` in your snow config to call out to curl instead.

**Comment by ceving** [comment]
It seems to me that `curl` is just used in `snow-post`:

https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/snow/commands.scm#L779

    $ grep -i curl /usr/local/share/chibi/chibi/snow/*.scm
    /usr/local/share/chibi/chibi/snow/commands.scm:;; a subset of http-post functionality that can shell out to curl
    /usr/local/share/chibi/chibi/snow/commands.scm:   ((conf-get cfg 'use-curl?)
    /usr/local/share/chibi/chibi/snow/commands.scm:    (let ((cmd `(curl --silent

`snow-chibi --use-curl search xml` still tries to connect directly.
