### ISSUE TITLE
Incorrect SRE test related to bol/eol ?

### ISSUE THREAD

**Issue by pclouds** [ashinn/chibi-scheme#552]
The test in question is this

```scheme
      (test-re #f
               '(: (* #\newline) bol ($ (* alpha)) eol (* #\newline))
               "\n'abc\n")
```

The expectation here is of course the first newline is eaten by `(* #\newline)`, then `'` cannot be matched and the test fail.

But the first `(* #\newline)` could also match _nothing_, the "cursor" remains at the first position, which satisfies `bol`. `eol` is also satisfied because of the first `\n` (i.e. it's an empty sentence) and the \n is eaten by the last `(* #\newline)` block. This results in a good match (of just the "\n" part, "'abc\n" is ignored), not `#f`.

I don't see anything wrong with this. `*` is supposed to be greedy, but when things are tight it could be a bit less greedy (by backtracking) and that's still compliant, isn't it?

I just want to double check that this is behavior is specific to Chibi and Gauche not behaving the same way is still correct.

This behavior is observed with Gauche regexp engine. The test code is here if you want to try out https://github.com/pclouds/Gauche branch regexp-bos-eos. Including @shirok in case I misunderstood either gauche regex, srfi-115, or just regex in general

**Comment by ashinn** [comment]
Yes, this can match up to `bol` correctly, and 0 matches of `($ (* alpha))`, but then `eol` (which is not optional) will fail.  So the test is correct.
