### ISSUE TITLE
(chibi filesystem) current-directory can get into an infinite loop

### ISSUE THREAD

**Issue by hga** [ashinn/chibi-scheme#553]
The stub code for it is:
```
(define-c non-null-string (current-directory "getcwd")
  ((result (array char (auto-expand arg1))) (value 256 int)))
```
The auto-expand loop does not allow for `EACCES`, [per POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/functions/getcwd.html), "Search permission was denied for the current directory, or read or search permission was denied for a directory above the current directory in the file hierarchy."

This is easy to achieve in OpenBSD by changing into a directory and as the above says, chmod 000 it or a directory above it.

**Comment by apg** [comment]
(*note:* I'm not an authority here, but I've looked into this a bit)

I'm pretty sure I understand the problem, but I don't think it can be solved directly with `chibi-ffi` stubs. Without `auto-expand` the behavior just returns `#f` on failure. That's only sort of what we want, though. The stubbed FFI code assumes the only failure is related to insufficient buffer size, and using auto-expand, doubles that value on subsequent calls. 

I guess there are 2 possible solutions that I see as a naive Chibi hacker:

1) Write the FFI by hand using `pathconf` and thwart the possible EINVAL, ERANGE errno values -- e.g. prevent the non-exceptional errors.
2) Make a simpler stub that can be called from a scheme implementation that inspects the errno for the failure reason and recalls appropriately.

I vote for option 1, but have to wonder how many other places errno isn't properly being considered from stubbed code under POSIX... Perhaps there's a solution via a patch to `chibi-ffi`?

**Comment by ashinn** [comment]
There is a third option, which is to count and impose a limit on the number of failures, which should probably be done regardless.
For 2 we have two variants - only repeat for a whitelisted set of errnos, or break on a blacklisted set.  I will more likely implement one of these.

**Comment by ashinn** [comment]
Added a simple limit for now.  It seems very difficult to get the EACCESS error in linux.
