### ISSUE TITLE
compile error in (chibi pty) on macOS

### ISSUE THREAD

**Issue by mbamac** [ashinn/chibi-scheme#558]
(chibi pty) do not compile on macOS Mojave (and High Sierra) with error:

cc  -dynamiclib -DSEXP_USE_NTPGETTIME -DSEXP_USE_INTTYPES -Iinclude  -Wall -g -g3 -O3   -o lib/chibi/pty.dylib lib/chibi/pty.c -L.   -lchibi-scheme -lutil
lib/chibi/pty.c:5:10: fatal error: 'pty.h' file not found
#include <pty.h>
         ^~~~~~~
1 error generated.
make: *** [lib/chibi/pty.dylib] Error 1

**Comment by lassik** [comment]
Try changing `(c-system-include "pty.h")` to `(c-system-include "util.h")` in `lib/chibi/pty.stub`

**Comment by iizukak** [comment]
@lassik That's works for me. thanks.
