### ISSUE TITLE
`if` accepts more than three arguments

### ISSUE THREAD

**Issue by lassik** [ashinn/chibi-scheme#561]
The current version of Chibi accepts the following, which can lead to subtle bugs in code:

```
$ chibi-scheme
> (if 1 2 3 4)
2
> (import (scheme base))
> (if 1 2 3 4)
2
```

Am I missing something obvious?

**Comment by ashinn** [comment]
Not missing anything, was just lazy checking for this originally.

**Comment by lassik** [comment]
Thanks for fixing it. Chibi is not the only implementation with this oversight :) I'll file issues with the others as well.

**Comment by ashinn** [comment]
Note it's not strictly speaking a bug but I agree is useful to report an error here.

**Comment by lassik** [comment]
Yeah, R7RS has some things that most people would think are errors but are undefined in the spec. In this case, it's easy to leave too many expressions in an `if` when editing code quickly and the code will produce unexpected results. That's how I found it :)
