### ISSUE TITLE
Imported definitions not visible inside the same cond-expand

### ISSUE THREAD

**Issue by lassik** [ashinn/chibi-scheme#565]
Is this intentional?

```
;;; Works:

(cond-expand
  (chibi
   (import (scheme base)
           (scheme write))))

(cond-expand
  (chibi
   (display "Hello world")
   (newline)))

;;; Does not work:

(cond-expand
  (chibi
   (import (scheme base)
           (scheme write))
   (display "Hello world")
   (newline)))
```

**Comment by ashinn** [comment]
Works for me - what are you getting?

**Comment by lassik** [comment]
```
ERROR on line 5 of file notwork.scm: undefined variable: display
  called from <anonymous> on line 1285 of file /Users/lassi/.local/share/chibi/init-7.scm
  called from <anonymous> on line 280 of file /Users/lassi/.local/share/chibi/init-7.scm
  called from <anonymous> on line 813 of file /Users/lassi/.local/share/chibi/init-7.scm
Searching for modules exporting display ...
display is exported by:
  (chibi)
  (scheme r5rs)
  (scheme red)
  (scheme small)
  (scheme write)
```

**Comment by ashinn** [comment]
`cond-expand` and `import` are both macros.  `import` expands into a primitive which inserts bindings at runtime.  These bindings won't be resolved in forms analyzed at the same time as the import.

I don't think it's worth trying to make this work.

**Comment by lassik** [comment]
I agree that the workaround of using two `cond-expand`s is easy enough. R7RS probably doesn't mandate expanding the bindings within the same form either.

**Comment by lockywolf** [comment]
(begin is not a macro, is it?

Geiser, in Emacs, tries to do:
(begin
    (import (scheme base))
    (display "hello world"))

But fails. Is it the same behaviour or different?

Lassi Kortela <notifications@github.com> 於 2019年8月31日 週六 23:01 寫道：

**Comment by ashinn** [comment]
Possibly, but note that `display` is not exported by (scheme base).

-- 
Alex

**Comment by lockywolf** [comment]
Yeah, I forgot to add (scheme write).

I just wanted to say that it would be nice to be able to wrap whole scm
file contents into a (begin).

Alex Shinn <notifications@github.com> 於 2019年9月1日 週日 10:13 寫道：

**Comment by lassik** [comment]
Might be worth polling srfi-discuss to find out what the consensus is among R7RS implementors.

**Comment by mnieper** [comment]
> I agree that the workaround of using two `cond-expand`s is easy enough. R7RS probably doesn't mandate expanding the bindings within the same form either.

Your example is not a valid R7RS program as `import` is only part of the meta-language of the module system. It is not a keyword that can be used to introduce a special form in the body of a program, a library or procedure.

**Comment by lassik** [comment]
`cond-expand` you mean?

**Comment by lassik** [comment]
Nope, once again you are right - `cond-expand` seems defined everywhere `cond` is, whereas `import`  only in `define-library`. But nevertheless the R7RS-small spec contains an example program that uses `import` outside a library.

**Comment by mnieper** [comment]
Can you show me the page where the example is? Note that `import` may appear at the top of a top-level program, but there it is still part of the module meta-language and not part of the program body.

**Comment by lassik** [comment]
It's _5.6.2. Library example_ on page 29.

Here's the definition of where `import` may appear:

> 5. Program structure
> 5.1. Programs
> A Scheme program consists of one or more import declarations followed by a sequence of expressions and definitions.

It's not clear to me how source files should be handled in different situations:

> 5.7. The REPL
>
> Implementations may provide an interactive session called a REPL
(Read-Eval-Print Loop), where import declarations, expressions and
definitions can be entered and evaluated one at a time.
> 
> [...]
>
> An implementation may provide a mode of operation in which the REPL
reads its input from a file. Such a file is not, in general, the same
as a program, because it can contain import declarations in places
other than the beginning.

So:

* in a program imports can only be at the very top
* in the REPL, or a file loaded into the REPL, imports can be freely mixed with other things

Which interpretation does Chibi use?

**Comment by lassik** [comment]
Chibi seems to allow mixed imports everywhere. This works:

`foo.sld`:

```scheme
(define-library (foo)
  (export foo)
  (import (scheme base))
  (begin (define foo 123)))
```

`bar.sld:`

```scheme
(define-library (bar)
  (export bar)
  (import (scheme base))
  (begin (define bar 456)))
```

`baz.scm`:

```scheme
(import (scheme base) (scheme write))

(display "foo = ")
(import (foo))
(display foo)
(newline)

(display "bar = ")
(import (bar))
(display bar)
(newline)
```

Output:

```
foo = 123
bar = 456
```

**Comment by lassik** [comment]
We should probably write a document clarifying this part of R7RS. Maybe it should be a SRFI. Implementations could then say that they use the semantics in that SRFI.

**Comment by mnieper** [comment]
I haven't yet understood what is to be clarified. What part of the semantics isn't clear?

By the way, `import' should be unbound in a top-level program that does not import or define this identifier. So if Chibi adhered strictly to the R7RS, your `baz.scm` would trigger an error because an unbound variable named `import` is accessed.

**Comment by lassik** [comment]
> By the way, `import` should be unbound in a top-level program that does not import or define this identifier.

Wow, you're right. _Appendix A. Standard Libraries_ says that there is no `import` in `(scheme base)` or any other standard library. I never noticed that omission, but it makes perfect sense to me now.

> I haven't yet understood what is to be clarified. What part of the semantics isn't clear?

It's not clear to me whether "program" or "REPL" semantics are used by:

* `-e` command line flag (probably always REPL mode)
* script mode `-s` or `-script` flag, or just the script filename, in several Schemes
* `(load)` from `(scheme load)`
* files implicitly loaded by an `(import)`
* any other implementation-specific loading mechanisms

The behavior of R7RS *load* is also really vague:

> 6.14. System interface
>
> [...]
>
> [...] The load procedure reads expressions and definitions from the
> file and evaluates them sequentially in the environment specified by
> environment-specifier . If environment-specifier is omitted,
> (interaction-environment) is assumed.
>
> It is unspecified whether the results of the expressions are
> printed. The load procedure does not affect the values returned by
> current-input-port and current-output-port. It returns an
> unspecified value.
>
> Rationale: For portability, load must operate on source files. Its
> operation on other kinds of files necessarily varies among
> implementations.

That reads like `(load ...)` doesn't need to handle `import` in the source file at all.

**Comment by lassik** [comment]
Since `load` evaluates things in `interaction-environment` by default, I guess it's expected that `import` is defined in that environment by the implementation.

**Comment by ashinn** [comment]
Chibi allows imports anywhere in a top-level program mostly because it's easier to implement :)  It does have the advantage of matching REPL behavior, and only deviates from the standard in pathological cases.

You shouldn't rely on this behavior, and either way import is not allowed in a library top-level.
