### ISSUE TITLE
The C level can't reliably receive multiple values

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#569]
You can sort of detect a multiple value return by checking that a pair is returned and the car of the pair is the same (in the sense of `equal?`) to `(values . ())`, but it's only *really* a multiple value if the cons is the specific cons, and C can't know that.

My suggestion is to add a new singleton object (like `()`, `#t`, `#f`) to be the car of a multiple values list.  C would be able to create and test this object, and the multiple-values routines and the write routines would have access to it through the C FFI, but ordinary Scheme code would not.

**Comment by ashinn** [comment]
Generally the C API was designed to integrate with C libraries, which have no multiple values, so this is not an issue.

If you want to write Chibi-specific C libraries this could come up.  What were you trying to do?

**Comment by johnwcowan** [comment]
In principle a C program should be just as capable of calling Chibi procedures that return multiple values as they are if the return is a complex number.  (Hence #570 on bignums.)

But the application of immediate interest is using Chibi for fast execution of interpreted Scheme scripts or plugins in a Chicken program through Chicken's C FFI, because Chicken's `eval` is terribly slow.  (I tried this before, years ago, but made the design too big and implementing it daunted me.)  Currently the best way to do that is probably Lua, although the lua egg hasn't been updated to C5 yet.

Certainly there is no reason why Chibi can't return multiple values to Chicken programs that expect them, provided the Chibi multiple-value protocol can be minimally exposed (as I say, a singleton object with a way to get hold of it and to detect it from both Chibi and C).

**Comment by ashinn** [comment]
You can call `(values)` from the external library and check future results against that.  It's perhaps a clumsy workaround but I prefer this to polluting the core of Chibi with a new type/object and corresponding new opcodes.
