### ISSUE TITLE
Bignums in the C API

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#570]
There is a `bignump()` macro to detect when a Chibi value is a bignum, but no documented way to retrieve its value.  The best you can do using the C API is to create a string output port, write the bignum to it, and pass the result along as a string (and the reverse to create a bignum).

**Comment by ashinn** [comment]
The "value" of a bignum is in the struct:

```    struct {
      signed char sign;
      sexp_uint_t length;
      sexp_uint_t data SEXP_FLEXIBLE_ARRAY;
    } bignum;
```

The exported API functions are in bignum.h.

I added a note to consult the headers for more info in the manual.
Let me know if you want something else.
