### ISSUE TITLE
match-letrec does not evaluate init forms with pattern variables in scope

### ISSUE THREAD

**Issue by peter-b** [ashinn/chibi-scheme#574]
I'm filing this here because you don't have a separate repository for `match`.

In Andrew Wright's original `match` implementation, as found in Guile 1.8, the following holds:

```scheme
(match-letrec (((x y) (list 1 (lambda () (list a x))))
               ((a b) (list 2 (lambda () (list x a)))))
  (append (y) (b))
=> (2 1 1 2)
```

This seems to match the behaviour suggested by your comment in `match.scm`:

> Similar to `match-let`, but analogously to `letrec`
> matches and binds the variables with all match variables in scope.

However, Scheme implementations that use your `match.scm`, the result is an error that `a` and/or `x` are unbound variables.

Which outcome is correct?

**Comment by ashinn** [comment]
Interesting, I think I need to extract all vars first from the expressions, bind them to dummy values, then set! them with the results.

Was this from a failed test or real-world example?

**Comment by peter-b** [comment]
I was writing unit tests to make sure that I'd ported your (very elegant) implementation correctly.  I wrote this test to try to demonstrate that `match-letrec` had different semantics from `match-let`.

I tried to patch this myself, but my Scheme metaprogramming skills are nowhere near good enough yet. The main problem I had was figuring out how to generate the `set!` forms correctly.

**Comment by peter-b** [comment]
@ashinn Nice fix!
