### ISSUE TITLE
Feature: JSON unparse

### ISSUE THREAD

**Issue by ekaitz-zarraga** [ashinn/chibi-scheme#590]
Hi,

As there's a JSON parse function I'm considering to develop a JSON unparse function.
Should I write it in C as json parser is or is it ok to go with Scheme + SRFI 159?
Any specific not about the design I should consider before spending time on it?

Thanks!

**Comment by ashinn** [comment]
This is on my TODO list, and I was intending to write it in C, but PRs are welcome.

**Comment by ekaitz-zarraga** [comment]
Cool, I'll try to implement it in Scheme this weekend with SRFI 159, and then consider rewriting it in C.

Thank you.

**Comment by ekaitz-zarraga** [comment]
Hi @ashinn ,

I started to work on this on my own repo:
https://github.com/ekaitz-zarraga/chibi-scheme/pull/1

If you have some feedback please let me know. It would be very useful.
Once I'm more or less done I'll make a PR here.

**Comment by ashinn** [comment]
This was merged (also I just updated this to work on port I/O).
