### ISSUE TITLE
SRFI 159 doesn't include `pretty`

### ISSUE THREAD

**Issue by ekaitz-zarraga** [ashinn/chibi-scheme#593]
Hi there,

The srfi 159 doesn't include `pretty`, it's necessary to import `chiby show pretty` for that. As [it's included in the srfi](https://srfi.schemers.org/srfi-159/srfi-159.html#proc-pretty), there's no reason to keep it separated, right?

**Comment by ashinn** [comment]
Yes, I just never got around to porting this from fmt.

**Comment by pclouds** [comment]
'pretty' is included in #612. Maybe we can close this now.
