### ISSUE TITLE
SRFI 18's `thread-sleep!` doesn't work

### ISSUE THREAD

**Issue by Winseven4lyf** [ashinn/chibi-scheme#594]
Unless I'm doing something wrong, SRFI 18's `thread-sleep!` doesn't seem to work.

When I run one of the examples from the SRFI document like so:

```scheme
;; sleep.scm
(import (scheme base)
        (scheme write)
        (srfi 18))

(let loop ((x 1))
  (thread-sleep! 1)
  (write x)
  (newline)
  (loop (+ x 1)))
```

```shell
$ chibi-scheme sleep.scm
```

which should wait one second between each `write`, it gets to about 100 in one second. And if I change the value given to `thread-sleep!`, even to very large values, it does the same thing.

I am using revision `d79f557` on Trisquel 8.0 (which is based on Ubuntu 16.04) with GCC version 5.4.0.

**Comment by Winseven4lyf** [comment]
Also, here's an unsightly hack that should continue to work when this is fixed (assuming I did the math for using 0.01 for `old-thread-sleep!` right):

```scheme
(import (scheme base)
        ;; (scheme write)
        (except (srfi 18) thread-sleep!)
        (rename (srfi 18) (thread-sleep! old-thread-sleep!)))

(cond-expand
 (chibi
  (define (thread-sleep! timeout)
    (if (time? timeout)
        (let ((start (time->seconds (current-time)))
              (timeout (time->seconds timeout)))
          (do ((k 0 (+ k 1)))
              ((>= k (* (- timeout start) 100)))
            (old-thread-sleep! 0.01)))
        (begin
          (do ((k 0 (+ k 1)))
              ((>= k (* timeout 100)))
            (old-thread-sleep! 0.01))))))
 (else
  (define thread-sleep! old-thread-sleep!)))

;; (let loop ((x 1))
;;   (thread-sleep! 1)
;;   (write x)
;;   (newline)
;;   (loop (+ x 1)))

;; (let ((start (time->seconds (current-time))))
;;   (let loop ((x 1))
;;     (thread-sleep! (seconds->time (+ x start)))
;;     (write x)
;;     (newline)
;;     (loop (+ x 1))))
```

**Comment by lockywolf** [comment]
Yeah, I confirm this.

**Comment by lockywolf** [comment]
@Winseven4lyf 
What you are doing here, is wrong.

First of all, you are using the -r switch while you have no main function. This is an erroneous behaviour (on the user's side), and chibi is super unforgiving to erroneous behaviour. I believe, you wanted chibi-scheme -l

Secondly, I think that thread-sleep! _only_ works for _child_ threads, not the main thread. I am not super sure, but the following code works fine:

```
(import (srfi 18) (scheme small))
(define (parallel-execute . forms)
  (define (create-threads . forms)
    (if (null? forms)
	(list)
	(let ((ctxi (thread-start! (make-thread (car forms)))))
	  (cons ctxi (apply create-threads (cdr forms))))))
  (define (wait-threads thread-list)
    (if (null? thread-list)
	#t
	(begin (thread-join! (car thread-list))
	       (wait-threads (cdr thread-list)))))
  (wait-threads (apply create-threads forms)))
(parallel-execute 
  (lambda () (thread-sleep! 10) (display "hello1") (newline))
  (lambda () (display "hello2") (newline)))
(exit)
```

**Comment by ashinn** [comment]
Yes, I think as implemented the main thread can't sleep.  Let me see if that's easy to fix.

**Comment by Winseven4lyf** [comment]
@lockywolf Yes, that example shouldn't have the `-r` flag, good point.

@ashinn Only children threads being able to sleep should be fine for my use case, but if it's not an easy fix, maybe a note in the procedure's documentation would be a good idea?

**Comment by ashinn** [comment]
Actually, it wasn't about child threads but about all threads waiting at the same time, and the selected thread not waiting on an event.  Fixed.
