### ISSUE TITLE
The default language and the -l language are not the same

### ISSUE THREAD

**Issue by lockywolf** [ashinn/chibi-scheme#595]
I have the following file, called test-parallel.scm:

```
(import (srfi 18))

(define (parallel-execute . forms)
  (if (null? forms)
      (list)
      (let ((ctxi (thread-start! (make-thread (car forms)))))
	(cons ctxi (apply parallel-execute (cdr forms))))))
(parallel-execute 
  (lambda () (display "hello1") (newline))
  (lambda () (display "hello2") (newline)))
(exit)
```

Evidently, it's a very simple code.

When I run chibi-scheme (without the -R option), bare interpreter with the defaul language, and issue:

```
(load "test-parallel.scm")
```
I get 
```
hello1
hello2
```
as expected.

However, when I run:
```
chibi-scheme -l test-parallel.scm
```
The output is empty.
Apparently, the "-l" language doesn't open the input-output ports, or something like that.

**Comment by lockywolf** [comment]
Maybe this is not a bug at all. 

Is the interpreter _not_ waiting for the threads to finish before terminating by default?

Maybe a warning could be added? Something like "WARNING: terminating the main thread while there are still alive children."?

**Comment by ashinn** [comment]
Note -l means load, not language, and is probably not what you want.

Just include all the imports explicitly, and call `chibi-scheme test-parallel.scm`.

I think the default I/O ports may not be inherited.

**Comment by ashinn** [comment]
The problem is you're not waiting for the child threads to terminate.  The following works:

```
(import (scheme base) (scheme process-context) (scheme write) (srfi 18))

(define (parallel-execute . forms)
  (let lp ((forms forms) (threads '()))
    (if (null? forms)
        (for-each thread-join! threads)
        (let ((thread (thread-start! (make-thread (car forms)))))
          (lp (cdr forms) (cons thread threads))))))
(parallel-execute 
  (lambda () (display "hello1") (newline))
  (lambda () (display "hello2") (newline)))
(exit)
```
