### ISSUE TITLE
What is the expected decoding of JSON \uFFFE

### ISSUE THREAD

**Issue by amirouche** [ashinn/chibi-scheme#597]
As part of https://github.com/amirouche/SRFI-JSON I am trying to pass all the tests in https://github.com/nst/JSONTestSuite.

What is the expected behavior of the following `zen` procedure:

```scheme
  (define (zen bv)
    ;; convert a bytevector encoded in utf16, into a single char
    (string-ref (textual->string (utf16->text bv))) 0)
```
It works except on `\uFFFE`, which says that there an index error in the generated string because  FFFE is converted to no char.

Python does return something when parsing that escaped sequence:

```python
In [5]: json.loads(""" "\uFFFE" """)
Out[5]: '\ufffe'
```

And the test suite I am refering to seems to imply that it is valid input but it is not clear what the output should be, see https://github.com/nst/JSONTestSuite/blob/master/test_parsing/y_string_unicode_U%2BFFFE_nonchar.json

Chez scheme does not produce a char for that sequence.

**Comment by lassik** [comment]
You should probably ask @johnwcowan about that, he's a Unicode expert.

More generally, there are going to be situations where JSON input has invalid UTF-8 but should be parsed anyway. In case of decoding error, instead of a string we could return a bytevector with the raw bytes of the string that we could not decode.

**Comment by lassik** [comment]
@shirok What do you do in Gauche's JSON parser?

**Comment by amirouche** [comment]
It is not the only test that fails with utf8 errors, actually I skipped all unspecified utf8 tests.

I sent a mail to [schemeweb@schemers.org](https://srfi.schemers.org/srfi-list-subscribe.html#schemeweb)

**Comment by johnwcowan** [comment]
U+FFFE is what you get when an initial [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark), U+FEFF, is read in byte-swapped order, so a bytevector with only #ff #fe or #fe #ff in it correctly converts to an empty string.  If you aren't expecting a BOM, and in this case you aren't, you need to use the `utf16-le` or `utf16-be` conversions instead of plain `utf-16`.

**Comment by amirouche** [comment]
According to JSON spec there should be no BOM in JSON, I assume they mean the file containing JSON should not contain a BOM *at the beginning of the text*.

> Implementations MUST NOT add a byte order mark to the beginning of a
> JSON text.  In the interests of interoperability, implementations
> that parse JSON texts MAY ignore the presence of a byte order mark
> rather than treating it as an error.

But the test use the following JSON text:

```
["\uFFFE"]
```

**Comment by johnwcowan** [comment]
That's a perfectly cromulent JSON value, an array with a single string of 1
character.  I don't understand where bytevectors come in, though.

**Comment by amirouche** [comment]
> I don't understand where bytevectors come in, though.

The string `\uFFFE` is converted to the bytevector `#vu8(#xFF #xFE)` then that bytevector is passed to `utf16->text` from `(scheme text)`.

**Comment by johnwcowan** [comment]
Okay, in that case simply call `utf16be->text` instead, and `#vu8(#xff #xfe)` will be treated as having a single character rather than a BOM followed by zero characters.

I am glad to see you are using texts rather than strings.

**Comment by amirouche** [comment]
I think I will use the trick used in CPython's json module:

https://github.com/python/cpython/blob/3a5de511596f17575de082dcb8d43d63b2bd2da9/Lib/json/decoder.py#L117-L124

There is also Gauche approach which is less hack-ish but indeed requires `(scheme text)`:

https://github.com/shirok/Gauche/blob/18d4f81c49167bf189c96f3a1558eeb63851f19a/lib/rfc/json.scm#L110-L140

**Comment by amirouche** [comment]
I used the python trick, which seems to do the magic that was advertised.
