### ISSUE TITLE
`string->number` behavior

### ISSUE THREAD

**Issue by amirouche** [ashinn/chibi-scheme#599]
I have still a few failing tests in my JSON library. They are related to `string->number`.

```scheme
(= (string->number "-01") -1)
(= (string->number "0.e1") 0.0)
(= (string->number "1eE2") 1.0) ;; chez says not a number
(= (string->number ".2e-3") 0.0002)
(= (string->number "2.e-3") 0.002)
(= (string->number "2.e+3") 2000.0)
(= (string->number "2.e3") 2000.0)
(= (string->number "-2.") -2.0)
(= (string->number "0e+-1") 0.0)  ;; chez says not a number
(= (string->number "-012") -12)
(= (string->number ".123") 0.123)
(= (string->number "042") 42)
```

I know JSON is not Scheme, I just want to make sure those behaviors are intentional?

**Comment by johnwcowan** [comment]
These are all valid R7RS numbers except the two flagged by Chez.

**Comment by lassik** [comment]
What's the closest thing to a canonical R7RS test suite btw?

**Comment by ashinn** [comment]
These are valid extensions, I don't really think it's worth signaling an exception here.
