### ISSUE TITLE
Foreign functions not working on Windows MSYS2 MinGW32

### ISSUE THREAD

**Issue by seb-jones** [ashinn/chibi-scheme#614]
I have a simple test program for using `sexp_define_foreign`:

```c
#include <stdio.h>
#include <chibi/eval.h>

sexp sexp_hello(sexp ctx, sexp self, sexp_sint_t n)
{
    printf("Hello, World\n");
    return SEXP_VOID;
}

void dostuff(sexp ctx) {
    sexp_gc_var1(res);
    sexp_gc_preserve1(ctx, res);

    res = sexp_eval_string(ctx, "(hello)", -1, NULL);

    if (sexp_exceptionp(res)) {
        sexp_debug(ctx, "Hello", res);
    }

    sexp_gc_release1(ctx);
}

int main(int argc, char *argv[])
{
    sexp ctx;

    ctx = sexp_make_eval_context(NULL, NULL, NULL, 0, 0);

    sexp_load_standard_env(ctx, NULL, SEXP_SEVEN);
    sexp_load_standard_ports(ctx, NULL, stdin, stdout, stderr, 1);

    sexp_define_foreign(ctx, sexp_context_env(ctx), "hello",
            0, sexp_hello);

    dostuff(ctx);

    sexp_destroy_context(ctx);

    return 0;
}
```

This works correctly on Linux, printing "Hello, World" to stdout. However when running on Windows in MSYS2, the `sexp_eval_string` appears to do nothing and the `sexp_debug` causes a Segmentation Fault.

**Comment by okuoku** [comment]
Hmm it works for me.

![SnapCrab_NoName_2020-2-16_21-40-41_No-00](https://user-images.githubusercontent.com/100813/74604833-0774c180-5105-11ea-93d3-bce16758b3ff.png)

Few points, assuming you are on Win64;

- `Makefile` on master is broken for default MinGW build (Some manual edits are required). To compile against MSYS, `make PLATFORM=msys` and `make PLATFORM=msys install` 
- It is not recommended linking MSYS chibi-scheme with MinGW program and vice versa. They will use different libc(MSYS uses variant of Cygwin, MinGW uses MSVCRT + some MinGW-w64 specific code)

**Comment by okuoku** [comment]
... and same for Win32.

On Win32, they will use different calling convention and it might describe what you see -- calling back to MinGW32 code causing crash.

**Comment by seb-jones** [comment]
Compiling it against MSYS does seem to make it work. Is there definitely no safe way to build chibi scheme with MinGW? I was hoping to use it as an extension language for an SDL2 program.

**Comment by okuoku** [comment]
I'll try to fix Makefile for MinGW. Meanwhile, CMakeLists.txt is sort-of (written by me) -- it will generate static library by default.

**Comment by okuoku** [comment]
Ugh, that was my own MSYS installation issue.. With MSYS fresh install and fresh checkout chibi-scheme Git, I was able to build MinGW32/64 chibi-scheme with `make` flawlessly.

To wrap-up:

1. Do not mix MSYS and MinGW code
2. Do not install MinGW version of chibi-scheme bin under `/usr/local/bin` or other paths

`Makefile` tries to avoid to pick-up wrong chibi-scheme installation by overriding `LD_LIBRARY_PATH` but it is not effective under MSYS. (Perhaps we should use `PATH` instead here.)

**Comment by seb-jones** [comment]
Would you mind explaining the steps you took from a fresh install of MSYS to getting a functioning build?

**Comment by okuoku** [comment]
... I'm still struggling with creating reliable reproduction (for both success/fail) on MinGW..

But, on MSVC, I can reliably recreate issue seemingly matching with yours. It raises "undefined variable" exception while evaluating `(hello)`; I'm not sure why this happens yet (FWIW `test/apply-loop.c`  https://github.com/ashinn/chibi-scheme/blob/3161edbe86d676329832829e4e6b8635ac09a21c/tests/foreign/apply-loop.c still works on Win32/Win64).

Created: https://github.com/okuoku/issue614

**Comment by okuoku** [comment]
Adding `-DSEXP_USE_GREEN_THREADS=0` seems fixing issue, for me.. https://github.com/okuoku/issue614/commit/7ef5740a3cdc36a10668191f9d8b4464245358a4

@ashinn : Does it intentional that `SEXP_USE_GREEN_THREADS` affects ABI?

**Comment by seb-jones** [comment]
Disabling green threads worked! Thanks :)
