### ISSUE TITLE
make fails with with undefined reference

### ISSUE THREAD

**Issue by phikal** [ashinn/chibi-scheme#615]
Hi, I'm trying to build chibi on a Debian buster system, but after a few compiler warnings, it always fails with the following message:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile.libs:65: lib/chibi/filesystem.so] Error 1
```

For reference, this is my...
- uname: `Linux bulbul 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`
- glibc version: `GLIBC 2.28-10`
- gcc version: `Debian 8.3.0-6`

I have tried building on different tags, but they all result in the same mistake. Could there be some dependencies I have forgotten to install?

**Comment by ashinn** [comment]
Just tried on Debian 9.9 and it works fine, and had worked on previous versions.
Chibi has no external dependencies.
Can you include the output of make -d?

**Comment by pclouds** [comment]
> undefined reference to `main'
> make: *** [Makefile.libs:65: lib/chibi/filesystem.so] Error 1

maybe wrong build flags. A shared library should never need 'main' function.

**Comment by ashinn** [comment]
Yes, but the default build flags should work fine.
Possibly he has CFLAGS set or something?

**Comment by pclouds** [comment]
Yeah could be. It would be hard to _remove_ -shared with a CFLAGS set from outside though. I looked again, it is possible that platform is detected wrong, then Makefile.detect may fail to include -shared flag.

**Comment by ashinn** [comment]
If uname -o returns GNU/Linux it will detect as Linux, but you can make PLATFORM=linux to be sure.
Either way, the default unknown PLATFORM still includes -shared.

**Comment by pclouds** [comment]
You're right. It would be good if @phikal posts the few lines before the error message, then we can see the exact compile command (with or without -shared) and hopefully see the problem.

**Comment by phikal** [comment]
It was related to `CFLAGS`, thanks for the tip! In my case I had it set to 

    export CFLAGS="-Wall -Wextra -Wformat -Wformat-security -pipe -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIE -pie -pedantic -D_XOPEN_SOURCE=700 -mtune=native -march=native"

but I don't quite see what would have broken it... Maybe the `-D_XOPEN_SOURCE=700`?

To @ashinn's request, here's a link to the output of `make -d` (without the compiler output): https://0x0.st/iZAd.log

**Comment by pclouds** [comment]
You can easily test it by elimination. I could reproduce it too. The problem is `-pie`
