### ISSUE TITLE
SRFI-30 multiline comment cannot placed on end-of-list

### ISSUE THREAD

**Issue by okuoku** [ashinn/chibi-scheme#623]
at https://github.com/ashinn/chibi-scheme/commit/72ea1258e63a9caf97ab330e4a78304d7b964c16

It seems Chibi-scheme's reader cannot read multiline comment (SRFI-30) iff it was at end-of-list.

```scheme
> (write (read (open-input-string "(#||#)")))
ERROR on line 1: too many ')'s
> (write (read (open-input-string "(ng #||#)")))
ERROR on line 1: too many ')'s
> (write (read (open-input-string "(#||# ok)")))
(ok)>
```

At least it was there [back to 2016](https://github.com/okuoku/yuni/issues/28) .

**Comment by ashinn** [comment]
Thanks, let me know if you see any more problems.
