### ISSUE TITLE
Confusing error message on importing a name-mismatched library

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#624]
If you say `(import (foo))` but foo.sld contains `(define-library (bar) ...`, Chibi reports that it can't find `(foo)`.  If you use the `-mfoo` option, the message is longer but even less helpful: it claims not to be able to find `foo.sld` in the path even though it's right there.

The fix needed is basically a better report: `foo.sld contains definition of (bar)`, or something like that.

**Comment by ashinn** [comment]
Note this works with -mfoo or with the advanced repl (-R), but not the basic repl.
