### ISSUE TITLE
regexp-split behaving differently than a specification example

### ISSUE THREAD

**Issue by hiddenwaffle** [ashinn/chibi-scheme#628]
In one of the examples for regexp-split as seen here: https://srfi.schemers.org/srfi-115/srfi-115.html#Implementation
the output does not quite match. Chibi returns a list with two extra strings, one at the front of the list and one at the back of the list, both empty. I'm not too familiar with SRE syntax so I'm not sure which is correct.

Expected:
```
(regexp-split '(+ space) " fee fi  fo\tfum\n")
=> ("fee" "fi" "fo" "fum")
```

Actual:
```
chibi-scheme -R
> (import (srfi 115))
> (regexp-split '(+ space) " fee fi  fo\tfum\n")
("" "fee" "fi" "fo" "fum" "")
```

This is a build from the master branch, 69aed9350276d3820e547911ca3327e004160f3f.

**Comment by ashinn** [comment]
Actually, Chibi is correct here and the and the SRFI example is wrong.
The semantics is more clearly explained in regexp-partition.
Note that regexp-split and regexp-extract when interspersed should be the same as regexp-partition.
I'll submit an errata to the SRFI.
