### ISSUE TITLE
APPLY segfaults on a circular list

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#629]
The following code reproduces the segfault:

```scheme
(define x '#0=(a . #0#))
(apply list x)
```

**Comment by ashinn** [comment]
Hmmm.  Probably apply is not in any critical code, although the check would also slow down exception raising.  I'll run some benchmarks.

**Comment by lassik** [comment]
Should applying a circular list actually have well defined behavior under some circumstances?

**Comment by mnieper** [comment]
Apply is insofar critical as it is in SRFI 172, which I am not a fan of,
though.

Alex Shinn <notifications@github.com> schrieb am So., 3. Mai 2020, 01:18:

**Comment by ashinn** [comment]
Actually, apply is already using a circular-list aware length, there's no overhead.
