### ISSUE TITLE
Possible overflow

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#636]
I think an arithmetic overflow can happen in code like the following:

https://github.com/ashinn/chibi-scheme/blob/e7e6530c353ec139d59254f343c67320a456623c/sexp.c#L1527

This can lead to insufficient space being allocated and later program crashes.

NB: Gnulib solves such issues with a small module for calculations with the `size_t` type: http://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/xsize.h

**Comment by ashinn** [comment]
This would only be possible with a pathologically large argument to `make-vector` which would fail regardless.  It may be best to introduce a hard but generous limit on the vector size.

**Comment by mnieper** [comment]
Am Di., 12. Mai 2020 um 17:54 Uhr schrieb Alex Shinn <
notifications@github.com>:

> This would only be possible with a pathologically large argument to
> make-vector which would fail regardless. It may be best to introduce a
> hard but generous limit on the vector size.
>
I have been wondering whether such a pathologically large argument could be
used by an attacker.
