### ISSUE TITLE
Access Violation when using sexp_current_error_port in Visual Studio build

### ISSUE THREAD

**Issue by seb-jones** [ashinn/chibi-scheme#645]
Using x64-Debug DLL built in Visual Studio.

I was trying to use `sexp_print_exception` but it was causing an error, and after some messing around I have found that just calling `sexp_current_error_port` seems to cause an Access Violation error. For example this contrived code causes said exception:

```
#include <chibi/eval.h>

int main(int argc, char *argv[])
{
	sexp ctx;

	ctx = sexp_make_eval_context(NULL, NULL, NULL, 0, 0);

	sexp_load_standard_env(ctx, NULL, SEXP_SEVEN);
	sexp_load_standard_ports(ctx, NULL, stdin, stdout, stderr, 1);

	sexp_current_error_port(ctx);

	return 0;
}
```

**Comment by okuoku** [comment]
Is `sexp_load_standard_env` and `sexp_load_standard_ports` working for you? Since `current-error-port` etc is a parameter object that required in R7RS standard, they need correctly setup standard_env first.

**Comment by seb-jones** [comment]
They appear to be working correctly. For example, the following program works correctly:
```
#include <chibi/eval.h>

int main(int argc, char *argv[])
{
	sexp ctx;
	FILE *out;
	FILE *err;

	ctx = sexp_make_eval_context(NULL, NULL, NULL, 0, 0);

	sexp_load_standard_env(ctx, NULL, SEXP_SEVEN);

	out = fopen("out.txt", "w");
	err = fopen("err.txt", "w");

	sexp_load_standard_ports(ctx, NULL, stdin, out, err, 1);

	sexp_eval_string(ctx, "(display \"Output!\")", -1, NULL);

	sexp_eval_string(ctx, "(display \"Error!\" (current-error-port))", -1, NULL);

	fclose(out);

	return 0;
}
```

This writes 'Output!' to `out.txt` and 'Error!' to `err.txt` as expected, which suggests to me that those ports are getting set correctly.

**Comment by seb-jones** [comment]
Additionally if I get the error port by evaluating the scheme alternative, it also works correctly:
```
#include <chibi/eval.h>

int main(int argc, char *argv[])
{
	sexp ctx;
	FILE *out;
	FILE *err;

	ctx = sexp_make_eval_context(NULL, NULL, NULL, 0, 0);

	sexp_load_standard_env(ctx, NULL, SEXP_SEVEN);

	out = fopen("out.txt", "w");
	err = fopen("err.txt", "w");

	sexp_load_standard_ports(ctx, NULL, stdin, out, err, 1);

	sexp_eval_string(ctx, "(display \"Output!\")", -1, NULL);

	{
		sexp_gc_var1(error_port);
		sexp_gc_preserve1(ctx, error_port);

		error_port = sexp_eval_string(ctx, "(current-error-port)", -1, NULL);

		sexp_write_string(ctx, "Error!", error_port);

		sexp_gc_release1(ctx);
	}

	fclose(out);
	fclose(err);

	return 0;
}
```

**Comment by okuoku** [comment]
Hmm, still no luck -- the first example still runs flawlessly on my side(VS2019 16.5.4). Could you share VisualStudio version and "Call stack" content? (`CTRL + ALT + C`)

Prepared reproduction branch: https://github.com/okuoku/issue614/tree/issue645

**Comment by seb-jones** [comment]
I'm using Visual Studio Community 2017 15.9.23. When I pulled down your branch and built it, it ran fine, so it must be an issue with how I'm building it.

**Comment by seb-jones** [comment]
Interestingly I now seem to get the following error on the same call:
```
ctx->value.context.globals was nullptr.
```

**Comment by mlabbe** [comment]
`ctx->value.context.globals` is also null for me.  I explain some of the steps in this related mailing list post: https://groups.google.com/forum/#!topic/chibi-scheme/zkJKyI4vcqI

In addition to Visual Studio, I built chibi scheme and my own calling code with Clang on Windows.  The bug remains entirely the same.

Stepping through in disassembly, `sexp_make_eval_context` correctly returns the qword ctx ptr via register as expected in convention.  However, upon assignment, `ctx != 0x0 && ctx->value.context.globals == 0x0`, where `ctx` is the sexp retval from `sexp_make_eval_context`.

**Comment by mlabbe** [comment]
Okay, putting `SEXP_USE_GREEN_THREADS` before `#include <chibi/eval.h>` worked. 

Previously, I only compiled the DLL, defining `SEXP_USE_GREEN_THREADS=0`.
