### ISSUE TITLE
make test-all fails on macos

### ISSUE THREAD

**Issue by mbamac** [ashinn/chibi-scheme#651]
LD_LIBRARY_PATH=".:" DYLD_LIBRARY_PATH=".:" CHIBI_IGNORE_SYSTEM_PATH=1 CHIBI_MODULE_PATH=lib ./chibi-scheme tests/lib-tests.scm
ERROR: couldn't find import: (srfi 64)
  called from <anonymous> on line 280 of file lib/init-7.scm
  called from for1 on line 75 of file lib/init-7.scm
  called from for1 on line 75 of file lib/init-7.scm
  called from <anonymous> on line 173 of file lib/meta-7.scm
  called from <anonymous> on line 222 of file lib/meta-7.scm
  called from <anonymous> on line 404 of file lib/meta-7.scm
  called from <anonymous> on line 1289 of file lib/init-7.scm
  called from <anonymous> on line 280 of file lib/init-7.scm
  called from <anonymous> on line 817 of file lib/init-7.scm
Searched module path ("lib") for "srfi/64.sld".
make: *** [test-libs] Error 70

**Comment by lassik** [comment]
Chibi doesn't ship with [SRFI 64](https://srfi.schemers.org/srfi-64/srfi-64.html) at all. I wonder what is trying to import it.

Can you try `grep -FRn '(srfi 64)' .`

**Comment by lassik** [comment]
It's `lib/srfi/146/hash-test.sld` right?
