### ISSUE TITLE
Fedora $VERSION interfering with Makefile

### ISSUE THREAD

**Issue by apapsch** [ashinn/chibi-scheme#659]
I'm on Fedora 32 Silverblue, which sets environment variable `VERSION` either to `32.xxx.0 (Silverblue)` (xxx being a timestamp). Toolbox containers have it set to `32 (Container Image)`.

Chibis Makefile itself uses the $VERSION variable, which gets overwritten. Running `make` with the fraudulent variable results in failing build:

```
$ make
[...]
echo '#define sexp_version "'32 (Container Image)'"' >> include/chibi/install.h
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo '#define sexp_version "'32 (Container Image)'"' >> include/chibi/install.h'
make: *** [Makefile:136: include/chibi/install.h] Error 1
```

I could work around the problem by unsetting VERSION before running `make`.

**Comment by ashinn** [comment]
I think it's bad practice for Fedora to define that variable, but I'll redefine it to CHIBI_VERSION or similar.

**Comment by apapsch** [comment]
Agreed, I was surprised as well to see that short, generic name defined.
