### ISSUE TITLE
Interpreter exit(0) even if uncaught exception happened

### ISSUE THREAD

**Issue by okuoku** [ashinn/chibi-scheme#664]
Tested: https://github.com/ashinn/chibi-scheme/commit/36c3471fa7f0f0b25761bb377328ae4f544c05e0

Chibi-scheme does not report error if `raise` was not caught any exception handler. This behaviour does not match with `error`. AFAIK, other Schemes return non-zero result.

Tested(interpreter): Cyclone Chez(R6RS) Gauche Guile MIT-Scheme Gambit Chicken Sagittarius Foment Digamma Kawa Racket(R6RS) IronScheme(R6RS)

```
chibi-scheme -e "(raise 'unexpected)" && echo "success."
success.
```

```
chibi-scheme -e "(error \"unexpected\")" && echo "success."
ERROR: unexpected
```

**Comment by ashinn** [comment]
This isn't related to `raise` vs `error` but an artifact of how the top-level handles exceptions.
It assumes an exception object returned to the top-level is an error and reports accordingly, otherwise it assumes success:

```
$ chibi-scheme -q -e "(raise (make-exception 'user \"unexpected\" '() #f #f))" && echo "success"
ERROR: unexpected
```

I think it's a bad idea to raise a non-exception object in general, and don't want to complicate the top-level main just to support this.

**Comment by okuoku** [comment]
Hmm, it's your choice.

**Comment by ashinn** [comment]
What non-exception object do you want to pass to `raise`?

**Comment by okuoku** [comment]
Anything, just to align with R6RS or other languages. For example, R6RS says:

http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-8.html

> any object may be used to represent an exception.

In practice, a record(with CLOS-like runtime) will be used to describe typed exception. Nested `guard` will construct exception-filter for application specific exception types. 

As a portability layer, originally we didn't plan to have dedicated exception object since other languages do not have this limitation(any other Scheme / C++ /  JavaScript can `raise` / `throw` any object as exception). OTOH, Python and C# require dedicated class(which is must be a subclass of language's Exception class). Ruby needs dedicated tag object along with exception object.

In my opinion, I do still think exception system should be type-system agnostic(other R7RSs, JavaScript) or tightly coupled with language's type system(R6RS, C++, C#, Python). Requesting `raise`ed object being wrapped (with `make-exception`) without any type-system support(e.g. subclassing) is somewhat ...unique. If we require any exceptions being wrapped before `raise`, `guard` clauses always tasked to unwrap object first to determine exception's (application-specific) class.

**Comment by ashinn** [comment]
Chibi of course follows the standard and allows any object to be passed to raise.

The question is what the default main.c does when a `raised`ed object escapes to the top-level, which is outside the scope of any of the standards.  Currently there is nowhere to return such out of band information in the C API and I don't want to change the API for this corner case.

**Comment by ashinn** [comment]
I could, however, automatically wrap other objects in an exception when returning to the top-level.

**Comment by okuoku** [comment]
> which is outside the scope of any of the standards.

Yup, thus this can be implementation specific behaviour. The point is chibi-scheme behaves differently with other Scheme or other language implementations in this case. Since failing with non-zero exit code is really crucial to integrate scripts into other systems (build system etc.) to detect failures, I thought it'd be better to follow other implementations to make less surprise, at least for standard batch mode operations.

> I don't want to change the API for this corner case.

To make this as a corner case, we need some Scheme API to wrap arbitrary object as exception object, to implement application specific exception classes. R6RS had `condition` APIs to implement such object but no R7RS (small) counter part exists so the plain Scheme object is the only way to utilize exception system with application specific exception classes.

In regard of embedding API, I'm neutral on this. I have no clear idea for what approach usually taken. But anyway, current `main.c` `check_exception` does nothing for such stray non-exception object; IMHO ignoring uncaught object is not a good example for embedders and it'd be better to demonstrate how to gracefully fail on such case. Wrapping the object in an exception object(and leave current `check_exception` as-is) would be a solution on this, as you say.

For example, when `(raise "uncaught exception")` happened inside batch mode scripts without any exception handler, following implementations will exit with message with non-zero exit code. 

Chez:

```
Exception occurred with non-condition value "uncaught exception"
```


Foment:

```
exception: "uncaught exception"
```

Gauche:

```
Error: uncaught exception: "uncaught exception"
```

Sagittarius:

```
Unhandled exception
  uncaught exception
```

Gambit(GSI):

```
*** ERROR IN "../repos/yuni/tests/err/fail8.sps"@3.1 -- This object was raised: "uncaught exception"
```

Guile3:

```
Throw to key `%exception' with args `("uncaught exception")'.
```

Cyclone:

```
Error: uncaught exception
```

Digamma:

```
error: unknown type of exception caught, uncaught exception


error in raise: returned from non-continuable exception

irritants:
  "uncaught exception"
```

MIT/GNU Scheme:

```
The object "uncaught exception" was raised.
```

Kawa:

```
kawa.lib.ExceptionWithValue: uncaught exception
        at kawa.lib.ExceptionWithValue.wrap(ExceptionClasses.scm:36)
```

Racket R6RS:

```
uncaught exception: "uncaught exception"
handler for uncaught exceptions: did not escape; original raise called (with non-exception value): "uncaught exception"
```

IronScheme:

```
uncaught exception
```
