### ISSUE TITLE
srfi-27 with large range parameter not returning all numbers

### ISSUE THREAD

**Issue by arvyy** [ashinn/chibi-scheme#668]
Calling procedure returned from `random-source-make-integers` with large parameter, it doesn't return values representative of the range. Seemingly no values are generated for upper end. Chibi was compiled with default configuration, version latest from master branch

```scheme
(import 
  (scheme base)
  (srfi 27)
  (srfi 158)
  (chibi test))

(test-begin "High number")

(define int-generator
  (let ((get-int (random-source-make-integers default-random-source)))
   (lambda ()
     (get-int 4294967296))))

(test-assert
  (generator-any
    (lambda (int)
      (> int 3221225472))
    (gtake int-generator 10000)))

(test-end "High number")
```

**Comment by jimrees** [comment]
I built chibi in 32-bit mode using "make CFLAGS=-m32 LDFLAGS=-m32" in order to force the bignum codepath when given the modulus 4294967296.    But then the generator function above would frequently return exactly 4294967295.

**Comment by ashinn** [comment]
Thanks for the report!  Fixed the fixnum case.  In 64-bit mode I don't see any weirdness with the bignum distribution, but will take a closer look and also check the 32-bit build.  I'm working on a stats library for which I need this to behave well, though have been focused on statistical tests so far.
