### ISSUE TITLE
Is sexp_primitive_opcodes required to be an ABI?

### ISSUE THREAD

**Issue by okuoku** [ashinn/chibi-scheme#669]
While debugging MinGW64 build with MSYS, I noticed `sexp_primitive_opcodes` is exported from DLL. Is this really required?

I don't recommend exporting this (and any) variable as ABI; adding opcode would immediately result ABI breakage.

If we still have to export this one, we have to adjust `SEXP_API` location like:

```diff
diff --git a/include/chibi/eval.h b/include/chibi/eval.h
index de308ebb..d0178548 100644
--- a/include/chibi/eval.h
+++ b/include/chibi/eval.h
@@ -46,7 +46,12 @@ enum sexp_opcode_classes {
   SEXP_OPC_NUM_OP_CLASSES
 };

-SEXP_API struct sexp_opcode_struct* sexp_primitive_opcodes;
+#ifdef BUILDING_DLL
+extern
+#else
+SEXP_API
+#endif
+struct sexp_opcode_struct* sexp_primitive_opcodes;

 #if SEXP_USE_DEBUG_VM || SEXP_USE_PROFILE_VM || SEXP_USE_STATIC_LIBS
 SEXP_API const char** sexp_opcode_names;
diff --git a/opcodes.c b/opcodes.c
index f4554b23..f2e7be9e 100644
--- a/opcodes.c
+++ b/opcodes.c
@@ -292,4 +292,4 @@ _FN2(_I(SEXP_UNIFORM_VECTOR), _I(SEXP_FIXNUM), _I(SEXP_FIXNUM), "make-uvector",
 _OP(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
 };

-struct sexp_opcode_struct* sexp_primitive_opcodes = opcodes;
+SEXP_API struct sexp_opcode_struct* sexp_primitive_opcodes = opcodes;
```

because C variables cannot have function prototypes. We have to add `extern` for any `BUILDING_DLL` files except instantiating actual struct(`opcodes.o`).

**Comment by ashinn** [comment]
I'll double check, but I don't think we need this. `sexp_make_primitive_env` should be a sufficient interface to these opcodes.
