### ISSUE TITLE
Makefile.detect: SEXP_USE_INTTYPES is never defined

### ISSUE THREAD

**Issue by okuoku** [ashinn/chibi-scheme#670]
at: https://github.com/ashinn/chibi-scheme/commit/b4fb077fef0d554ece144d27070d176957f09087

It seems `SEXP_USE_INTTYPES` is not defined inside `Makefile.detect` as intended since actual `XCPPFLAGS` is defined before `CPPFLAGS` settled. Perhaps we can remove this entirely or just mandate C99 and use `<inttypes.h>` without any conditions?

This was found because https://github.com/ashinn/chibi-scheme/commit/b4fb077fef0d554ece144d27070d176957f09087 lacks `<stdint.h>` reference inside `rand.c` -- this is why currently MinGW32/64 on MSYS build failing on the CI. `<stdint.h>` is also a C99 and at least on Windows, we can safely depend on this.

**Comment by ashinn** [comment]
Thanks!  I'll fix this without mandating C99 - don't want to break the Plan9 build.
