### ISSUE TITLE
Error installing master

### ISSUE THREAD

**Issue by amirouche** [ashinn/chibi-scheme#673]
The following command will error:

```sh
% PREFIX=$(pwd)/local make install
... 
install -m0644 doc/chibi-doc.1 /home/amirouche/src/scheme/chibi/chibi/local/share/man/man1/
if type ldconfig >/dev/null 2>/dev/null; then ldconfig; fi
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
make: [Makefile:388: install-base] Error 1 (ignored)
echo "Generating images"
Generating images
cd / && LD_LIBRARY_PATH="/home/amirouche/src/scheme/chibi/chibi/local/lib:" DYLD_LIBRARY_PATH="/home/amirouche/src/scheme/chibi/chibi/local/lib:" CHIBI_MODULE_PATH="/home/amirouche/src/scheme/chibi/chibi/local/share/chibi:/home/amirouche/src/scheme/chibi/chibi/local/lib/chibi" /home/amirouche/src/scheme/chibi/chibi/local/bin/chibi-scheme -d /home/amirouche/src/scheme/chibi/chibi/local/share/chibi/chibi.img
cd / && LD_LIBRARY_PATH="/home/amirouche/src/scheme/chibi/chibi/local/lib:" DYLD_LIBRARY_PATH="/home/amirouche/src/scheme/chibi/chibi/local/lib:" CHIBI_MODULE_PATH="/home/amirouche/src/scheme/chibi/chibi/local/share/chibi:/home/amirouche/src/scheme/chibi/chibi/local/lib/chibi" /home/amirouche/src/scheme/chibi/chibi/local/bin/chibi-scheme -xscheme.red -d /home/amirouche/src/scheme/chibi/chibi/local/share/chibi/red.img
cd / && LD_LIBRARY_PATH="/home/amirouche/src/scheme/chibi/chibi/local/lib:" DYLD_LIBRARY_PATH="/home/amirouche/src/scheme/chibi/chibi/local/lib:" CHIBI_MODULE_PATH="/home/amirouche/src/scheme/chibi/chibi/local/share/chibi:/home/amirouche/src/scheme/chibi/chibi/local/lib/chibi" /home/amirouche/src/scheme/chibi/chibi/local/bin/chibi-scheme -mchibi.snow.commands -mchibi.snow.interface -mchibi.snow.package -mchibi.snow.utils -d /home/amirouche/src/scheme/chibi/chibi/local/share/chibi/snow.img
ERROR: couldn't find include: "scheme/bytevector.so"
make: [Makefile:395: install] Error 70 (ignored)
```

**Comment by amirouche** [comment]
Actually, it is unrelated to PREFIX.

```
$ git show --shortstat 
commit 82acca477226ba16f34f64ac394e1c23a1df4c70 (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by amirouche** [comment]
That is still an issue when compiling with a prefix:

```sh
if type ldconfig >/dev/null 2>/dev/null; then ldconfig; fi
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```

**Comment by amirouche** [comment]
According to `git bisect` the problem was introduced in 

```
$ git show
commit 23e62275df5b9c883fd1d6316df3930b55ef8dab (HEAD, refs/bisect/bad)
Author: Alex Shinn <alexshinn@gmail.com>
Date:   Tue Jul 28 15:09:40 2020 +0900

    fixing scheme bytevector for 32bit arch
```

See 23e62275df5b9c883fd1d6316df3930b55ef8dab

**Comment by amirouche** [comment]
It should work according to CI

https://github.com/ashinn/chibi-scheme/actions/runs/185281466

**Comment by mbamac** [comment]
I've got similar error on macOS with "make install":

Generating images
cd / && LD_LIBRARY_PATH="/usr/local/lib:" DYLD_LIBRARY_PATH="/usr/local/lib:" CHIBI_MODULE_PATH="/usr/local/share/chibi:/usr/local/lib/chibi" /usr/local/bin/chibi-scheme -d /usr/local/share/chibi/chibi.img
cd / && LD_LIBRARY_PATH="/usr/local/lib:" DYLD_LIBRARY_PATH="/usr/local/lib:" CHIBI_MODULE_PATH="/usr/local/share/chibi:/usr/local/lib/chibi" /usr/local/bin/chibi-scheme -xscheme.red -d /usr/local/share/chibi/red.img
cd / && LD_LIBRARY_PATH="/usr/local/lib:" DYLD_LIBRARY_PATH="/usr/local/lib:" CHIBI_MODULE_PATH="/usr/local/share/chibi:/usr/local/lib/chibi" /usr/local/bin/chibi-scheme -mchibi.snow.commands -mchibi.snow.interface -mchibi.snow.package -mchibi.snow.utils -d /usr/local/share/chibi/snow.img
ERROR: couldn't find include: "scheme/bytevector.dylib"
make: [install] Error 70 (ignored)

**Comment by ashinn** [comment]
Thanks!  This is an error generating the images, which as make tells you is ignored.

The build and install were successful but (scheme bytevector) wasn't installed.  Will fix.

**Comment by amirouche** [comment]
It works for me.

@mbamac Feel free to re-open the issue if you have a problem.
