### ISSUE TITLE
Incompatible definition of SRFI 160's vector=

### ISSUE THREAD

**Issue by Zipheir** [ashinn/chibi-scheme#674]
Chibi's implementation of SRFI 160 provides a version of _vector= which is incompatible with the SRFI document; namely, it takes a comparison procedure as its first argument.  A compatible version, which
also fixes the space-inefficient variadic recursion:

    (define (vector= . o)
      (let lp ((o o))
        (cond
         ((null? o) #t)
         ((null? (cdr o)) #t)
         (else
          (and (let* ((v1 (car o))
                      (v2 (cadr o))
                      (len (uvector-length v1)))
                 (and (= len (uvector-length v2))
                      (let lp ((i 0))
                        (or (>= i len)
                            (and (= (uvector-ref v1 i)
                                    (uvector-ref v2 i))
                                 (lp (+ i 1)))))))
               (lp (cdr o)))))))

**Comment by ashinn** [comment]
There was the same confusion in the original sample impl: https://srfi-email.schemers.org/srfi-160/msg/11859717/

I guess we're stuck with it now.

**Comment by ashinn** [comment]
It's a real shame, they even both agreed the predicate was better and it was just left out due to time...
