### ISSUE TITLE
SRFI 160: Off-by-one error in vector-reverse-copy

### ISSUE THREAD

**Issue by Zipheir** [ashinn/chibi-scheme#676]
There's an off-by-one error in the `uvector-unfold` used to implement `vector-reverse-copy`. Evaluating

`(u8vector-reverse-copy (u8vector 1 3 4))`

gives:

`ERROR on line 66 of file ./lib/srfi/160/uvector.scm: byte-vector-ref: index out of range
 #u8(#x01 #x03 #x04)
    3`

**Comment by ashinn** [comment]
Thanks!  Actually the error was in `vector-reverse-copy` and it wasn't off-by-one.
