### ISSUE TITLE
SRFI 160: vector-segment returns only the first segment

### ISSUE THREAD

**Issue by Zipheir** [ashinn/chibi-scheme#677]
`@vector-segment` always returns a list containing only the first segment:

`(u8vector-segment #u8(1 2 3 4) 2)   ; => (#u8(#x01 #x02))`

This is due to the use of `max` in the function's body loop, which causes the index `i` to jump to `(uvector-length vec)` on the first tail-call.

EDIT: Fix typo.

**Comment by ashinn** [comment]
Thanks!
