### ISSUE TITLE
make test-all fails on macos at srfi-160

### ISSUE THREAD

**Issue by mbamac** [ashinn/chibi-scheme#679]
srfi-160: uniform vectors: 
        uvectors/constructors: ..!...........
        13 out of 14 (92.9%) tests passed in 0.0031371116638183594 seconds.
        1 error (7.1%).
        ERROR: (u32vector-unfold values 7)
            ERROR on line 280 of file lib/init-7.scm: not enough args
    #<procedure uvector-unfold>
    2
    on line 14 of file "lib/srfi/160/test.sld"
        uvectors/predicates: ........
        8 out of 8 (100.0%) tests passed in 0.0013599395751953125 seconds.
        uvectors/iteration: ...........
        11 out of 11 (100.0%) tests passed in 0.002104043960571289 seconds.
        uvectors/searching: ..................
        18 out of 18 (100.0%) tests passed in 0.004358768463134766 seconds.
        uvectors/mutation: .............
        13 out of 13 (100.0%) tests passed in 0.0037310123443603516 seconds.
        uvectors/conversion: ........
        8 out of 8 (100.0%) tests passed in 0.0020761489868164062 seconds.
    71 out of 72 (98.6%) tests passed in 0.019374847412109375 seconds.
    1 error (1.4%).
    5 out of 6 (83.3%) subgroups passed.

**Comment by ashinn** [comment]
I had forgot to push some changes to the uvector tests, can you try again?

**Comment by mbamac** [comment]
now it's OK
