### ISSUE TITLE
SRFI 145

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#684]
The code of SRFI 145 (assumptions) for Chibi calls "(car 0)" when the "debug" feature identifier is not set (and the assumption not fulfilled).

I suggest removing the dependence on "debug" and call "error" unconditionally. The "(car 0)" really only makes sense for Schemes that do DFA for optimization.

If you agree, @ashinn, I'll do this.

**Comment by ashinn** [comment]
I think optimizing Schemes could treat a call to `error` the same as they do `(car 0)`.  I think this change is fine.

Wouldn't it make sense, though, to translate `assume` to a noop unless `debug` is enabled?

**Comment by mnieper** [comment]
Am Mi., 19. Aug. 2020 um 02:58 Uhr schrieb Alex Shinn <
notifications@github.com>:

> I think optimizing Schemes could treat a call to error the same as they
> do (car 0). I think this change is fine.
>
As a call to "error" mustn't be treated as "(car 0)" as long as the
optimizing Scheme still wants to conform to the standard. "error" has a
well-defined behavior (and won't help for type deduction through CFA),
while "(car 0)" can really mean the same as GCC's __builtin_unreachable,
i.e. "you may assume that the program never comes to this point".
(This is the whole point of SRFI 145's assume vs R6RS's assert. The latter
has to raise an error condition, which is not helpful in optimizing modes.)

> Wouldn't it make sense, though, to translate assume to a noop unless debug
> is enabled?
>
Yes, that's probably more in line with the spirit of SRFI 145.

PS When I enable "debug" in Chibi through "-Ddebug", my programs suddenly
take much much time to run. What else is enabled by enabling this?

**Comment by ashinn** [comment]
Ah, yes, of course.

I don't believe anything else uses the debug feature.  Do you use it in local code?

**Comment by mnieper** [comment]
Am Mi., 19. Aug. 2020 um 08:26 Uhr schrieb Alex Shinn <
notifications@github.com>:

> Ah, yes, of course.
>
> I don't believe anything else uses the debug feature. Do you use it in
> local code?
>
Not much... but maybe it is used in some Chibi library, which my code uses
in inner loops.  But that's fine; I just wanted to make sure that "debug"
does not control some other features as well.

**Comment by mnieper** [comment]
I will push the discussed change (assume is a noop without assumptions) in a second.

Assumptions will be unconditionally disabled when the feature identifier `elide-assumptions` is present; if not, they are enabled if the feature identifier `debug` or `assumptions` is present.
