### ISSUE TITLE
Continuations don't work across successive evals in the advanced REPL

### ISSUE THREAD

**Issue by Zipheir** [ashinn/chibi-scheme#686]
An error occurs when the result of make-unfold-generator is called at least twice:

```
> (define ones (make-unfold-generator (lambda (_) #f) values values 1))
> (ones)
1
> (ones)
ERROR in child thread: #<Context 140558283242336>
ERROR in travel-to-point! on line 838 of file .../share/chibi/init-7.scm: non procedure application: #f
ERROR in travel-to-point! on line 838 of file .../share/chibi/init-7.scm: non procedure application: #f
```

**Comment by mnieper** [comment]
`make-unfold-generator` is defined in terms of `make-coroutine-generator`. `make-coroutine-generator` in turn relies on saving the current continuation in a local variable.

However, first-class continuations do not work across prompts in the repl.

**Comment by mnieper** [comment]
PS You can write your own repl using `(scheme read)`, `(scheme eval)`, `(scheme repl)` and `(scheme write)`. Then it should work.

**Comment by mnieper** [comment]
A minimal example:

``` 
$ chibi-scheme -R
> (define x #f)
> (call/cc (lambda (c) (set! x c)))
> (x)
ERROR in child thread: #<Context 139664177533536>
ERROR in travel-to-point! on line 834 of file /usr/local/share/chibi/init-7.scm: non procedure application: #f
ERROR in travel-to-point! on line 834 of file /usr/local/share/chibi/init-7.scm: non procedure application: #f
```

**Comment by Zipheir** [comment]
Thanks!  This can be closed, then.

**Comment by ashinn** [comment]
Actually, these examples both work if you _don't_ use -R.

The advanced repl runs eval in a separate thread in order to be able to interrupt it with C-c.

**Comment by ashinn** [comment]
A trivial repl such as Marc suggests is not a good solution, however this can be fixed with some internal tooling to support aborting a thread back to a previous computation and/or better syncing of dynamic-wind in child threads.
