### ISSUE TITLE
(chibi loop) protocol cannot fully support (in-generator ...)

### ISSUE THREAD

**Issue by bjoli** [ashinn/chibi-scheme#695]
If I understand things correctly, the iterator protocol used by chibi loop cannot support iterating over generors without help from the user (in the form of a named loop and explicitly checking the bound value).  This is due to the generator protocol missing support for checking a value _after_ the body values have been bound to identifiers. There is no way for an (for x (in-generator gen)) to break if (gen) returns the eof-object, since the iterator protocol currently only supports testing the container if it has been exhausted, which in the case of generators is impossible unless you give generators some magic tag argument to check it with. 

I noticed because I have been looking at foof-loop/(chibi loop) for inspiration for something that is even hairier to implement using syntax-rules. It is such a neat and elegant looping facility!

Best regards
Linus

**Comment by ashinn** [comment]
Gee, then I wonder how `in-port` was implemented?

**Comment by bjoli** [comment]
Dang. Sorry for wasting your time.

**Comment by bjoli** [comment]
So, for anyone wondering just about how wrong I was and why: I was thinking of implementing in-generator as in-list, where the "collection" is passed along, I had considered in-port but instead of looking I just though it was implemented with something like (port-eof? ...), which wouldn't have worked for in-generator for generators as described in srfi-158. In hindsight I give myself F for effort.

For future reference if anyone else would like to make statements, thinking they have grooked something without reading further than their own nose: 

(chibi loop) in-port binds the port outside the loop body. Say we have a loop with the only clause (for line (in-port p read-line)) we get something akin to (typing on my phone here, so this is not the actual expansion, but more in the spirit of it):

`
(let ((port-name p))
  (let loop ((line (read-line port-name)))
    (if (eof-object? line)
        DONE
        (begin
          BODY
          (loop (read-line port-name))))))
`

This of course makes perfect sense, and is a lot more efficient than a portable version of my idea with a port-eof? procedure.

**Comment by ashinn** [comment]
In all fairness, the documentation for `(chibi loop)` needs improvement.

If `in-generator` is useful to people we can add it.
