### ISSUE TITLE
Combinatorial explosion for not clauses in match?

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#698]
Here

https://github.com/ashinn/chibi-scheme/blob/9433b8b912aab67644fe6f1346686bd031c6c979/lib/chibi/match/match.scm#L388

you seem to switch the success with the failure continuation. For the failure continuation, however, you make the assumption that it has a cheap expansion.

**Comment by ashinn** [comment]
Thanks!

**Comment by mnieper** [comment]
> 
> 
> Thanks!

Besides the academic discussion in the other thread, I would like to contribute something constructive as well. :)

**Comment by mnieper** [comment]
Sorry, reopening the issue because I am not sure that your patch does everything intended. The `(sk ...)` continuation passed to the not-clause of  `match-two` can be very expensive to expand (as in `(and (not <pat1>) <pat2>)`), but it will be expanded several times when viewed as the failure continuation in the pattern argument of `not`.

**Comment by ashinn** [comment]
Oops, captured the wrong thing.
