### ISSUE TITLE
R7RS compatibility

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#699]
So that the R7RS compatibility is the default, consider setting this

https://github.com/ashinn/chibi-scheme/blob/e7e034dea05438938092f06edf1bad1618154594/include/chibi/features.h#L556

by default, so that the user has to explicitly turn that compatibility feature off.

**Comment by ashinn** [comment]
I will when I first see an example of a real-world R7RS program which breaks because of this.

**Comment by mnieper** [comment]
The problem is the other way round. When one writes sophisticated macros
and tests them with Chibi, they work, but then they miraculously don't work
with other implementations. It has happened to me more than once.

The idea of my request is to ease writing portable macros. We have been
discussing lots of fine Kiselyov-like tricks but they often depend on the
exact semantics.

A real-world example may be the match macro when, for whatever reason, you
want or need to bind a "reserved keyword" like "and". What you would do
would be

(import (rename (scheme base) (and scheme-and))
        (chibi match))
(match '(1 2) ((and y) <body>)

Without strict-top level bindings, "match" would fail and wouldn't bind
"and" in <body>, I think.

Anyway, this is just a suggestion.


Am Di., 1. Sept. 2020 um 10:15 Uhr schrieb Alex Shinn <
notifications@github.com>:
