### ISSUE TITLE
A relative DESTDIR breaks the installation

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#707]
Why is the directory changed to the root directory here?

https://github.com/ashinn/chibi-scheme/blob/77aab98784570b8d03e0bd30feac040352ddb359/Makefile#L397

Installations in relative directories (DISTDIR) break.

**Comment by ashinn** [comment]
DESTDIR is for package managers and I would imagine is never relative in practice, but I can support this.

**Comment by mnieper** [comment]
I observed the issue when I experimented with building a Docker image. I wanted to collect the Chibi install files in a directory relative to the Docker build working directory.

Anyway, the GNU Coding Standards also do not guarantee that a non-absolute DESTDIR will work: https://www.gnu.org/prep/standards/standards.html#DESTDIR
