### ISSUE TITLE
and-let* non-conforming

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#712]
The SRFI 2 and-let* form has the following syntax (with <body> being optional):

(and-let* (<claw> ...) <body>)

In Chibi's implementation, however, <body> can only be a sequence of expressions but not a body in the sense of R5+RS.

This can be corrected in the macro by wrapping <body> in a `let*` form instead of a `begin` form; the case of an empty body becomes a special case.

**Comment by ashinn** [comment]
Sorry, I don't understand, can you provide a test case?

**Comment by mnieper** [comment]
I have created a pull request #713. I added two tests to the SRFI 2 test suite. Does it clarify the issue?

**Comment by ashinn** [comment]
This is more commonly described as "and-let* should introduce a new contour", or "internal definitions are permitted in and-let*".

However, although I think this would strictly be more intuitive and more useful, I don't see where it's specified in SRFI 2.
On the contrary, it gives a formal denotational semantics expanding into a `begin`.
Oleg's sample implementation also expands into a `begin`, failing your test case.

**Comment by mnieper** [comment]
Am Do., 22. Okt. 2020 um 15:41 Uhr schrieb Alex Shinn <
notifications@github.com>:

> This is more commonly described as "and-let* should introduce a new
> contour", or "internal definitions are permitted in and-let*".
>
> However, although I think this would strictly be more intuitive and more
> useful, I don't see where it's specified in SRFI 2.
> On the contrary, it gives a formal denotational semantics expanding into a
> begin.
> Oleg's sample implementation also expands into a begin, failing your test
> case.
>
In the syntax section, it says <body>, which is defined at least since R5RS
as a sequence of definitions followed by a sequence of expressions.
Moreover, and-let* is advertised as a generalization of let*, which takes a
body.

I agree that the formal denotational semantics does not take this into
account but the formal denotational semantics of R5RS and R7RS neither
handles internal definitions. (By rewriting a body into an equivalent
letrec*-expression during expansion, this is a sensible approach.)

In any case, introducing a new contour is backwards-compatible to an
implementation that just uses `begin`.

**Comment by ashinn** [comment]
Lots of macros name their trailing rest portion "body" - it makes no claim this is "body" in the formal sense of R5RS.
And both the semantics and sample implementation contradict this.

It's also not a backwards compatible change, as the following would cease to work:

`(let () (and-let* () (define x 5)) x)`

**Comment by mnieper** [comment]
If in a specification some token is named <body> but no further explanation is given, I can only assume that it is a body in the sense of the underlying Scheme specification.

The example `(let () (and-let* () (define x 5)) x)` only works in Chibi (with its current implementation of `and-let*`) because it doesn't mind if a definition follows an expression (`#t` in this case) in a body as long as it is wrapped in a splicing `begin`.

It would be inconsistent to allow `(let () (and-let* () (define x 5)) x)` while disallowing `(and-let* ((y 0)) (define x 5) x)`. In the first case, you have to read the `BEGIN` in the formal semantics as the _splicing_ begin; to disallow the second, you have to read the same `BEGIN` as the _expression_ form of begin.

**Comment by ashinn** [comment]
I would not assume anything by the use of a common word.  It does not say `<body>` nor reference R5RS.

Anyway, I'm not saying it's a good example, or that I wouldn't prefer this change, but it's not what the SRFI specifies.

If you disagree, take it up on the SRFI 2 mailing list.  Get an errata and correction to the used sample implementation.
Note on quick perusal, Chicken, Gauche and Scheme48 all agree with Chibi and the sample implementation on this.

**Comment by ashinn** [comment]
I would not assume anything by the use of a common word.  It does not say `<body>` nor reference R5RS.

Anyway, I'm not saying it's a good example, or that I wouldn't prefer this change, but it's not what the SRFI specifies.

If you disagree, take it up on the SRFI 2 mailing list.  Get an errata and correction to the used sample implementation.
Note on quick perusal, Chicken, Gauche and Scheme48 all agree with Chibi and the sample implementation on this.
