### ISSUE TITLE
Debian Package - Symbols File - 32 Bit Machine - Build Failure

### ISSUE THREAD

**Issue by barak** [ashinn/chibi-scheme#714]
The chibi-scheme Debian package 0.9.1-1 is failing to build on some architectures, it looks like 32 bit ones, due to a problem with `debian/libchibi-scheme0.symbols`.

* build logs: https://buildd.debian.org/status/package.php?p=chibi-scheme
* bug report: https://bugs.debian.org/972956

Assistance welcome. (My own inclination would be to just rip out the symbols files, but apparently that's frowned upon.)

**Comment by ashinn** [comment]
Thanks Barak, these errors are pertaining to image related utilities which are disabled on 32 bit.  I'll take a look.
