### ISSUE TITLE
EOF doesn't match on 9front

### ISSUE THREAD

**Issue by smazga** [ashinn/chibi-scheme#731]
I'm not sure what the right way to approach this is, so I'm hoping for some feedback.

`mk clibs.c` does not complete because the executable gets stuck in a loop allocating memory and is eventually killed.

I've traced the issue down to https://github.com/ashinn/chibi-scheme/blob/2d562bdae1575d8354a4637fa79c4f26a79f002a/vm.c#L2102 

The problem is that `EOF` is `(int)-1` (size:4), but `i` is `sexp_sint_t` (size:8). So, not only is `EOF` > `0x80`, but it also won't match the subsequent check of `i == EOF`.

A hacky workaround is just to cast `(int)i` wherever it's compared against `EOF` (changing the linked line to `if ((int)i != EOF && i >= 0x80)` seems to work), but I don't know if that's kosher chibi code or good C (I'm just not that familiar).

Is there a better way to handle this?

**Comment by ashinn** [comment]
The order of checks is wrong here - we check `if (i == EOF)` next, but should check it first.  Move the >= 80 check to after that.   I don't think you need to bother with a cast.

**Comment by ashinn** [comment]
Let me know if you still have problems.

**Comment by smazga** [comment]
It's still an issue, but I appear to be the only one affected and the larger system still isn't working, anyway. So I've been working on that. I've been distracted with life lately, but hopefully I'll have a more comprehensive answer for Plan9 before too long.

**Comment by linusroesener** [comment]
One issue is, that when green threads are disabled (like on Plan9) read_char doesn't return SEXP_EOF, but instead it returns the input port.
https://github.com/ashinn/chibi-scheme/blob/2d562bdae1575d8354a4637fa79c4f26a79f002a/vm.c#L2122
This #endif has to be put before the "else", as far as I understand the code.
