### ISSUE TITLE
Compiling chibi with the newest emscripten

### ISSUE THREAD

**Issue by nomelif** [ashinn/chibi-scheme#742]
Hi.

I am again trying to compile chibi to JS for a personal project, but I am failing to do it.

I used a clean (+git) Ubuntu 20.04 virtual machine and did the [following](https://pastebin.com/BR4Y1Bn2), emscripten install as per [here](https://emscripten.org/docs/getting_started/downloads.html). The version of emscripten this gave me was 2.0.18. The make command I used was `CC=emcc make js`.

I also tried to run emmake, with [this](https://pastebin.com/7LQE3PC8) result. The emmake command I used was `emmake make js`.

Am I doing something wrong? Thanks in advance.

**Comment by pclouds** [comment]
I think this shouldn't run

```
./chibi-scheme-emscripten -q tools/chibi-ffi lib/chibi/filesystem.stub
make[1]: execvp: ./chibi-scheme-emscripten: Lupa evätty
```

Although I have no idea why it runs. Maybe it should run anyway but use the native binary, not the emscripten version

**Comment by pclouds** [comment]
Never mind, that seems right. Maybe you can just delete chibi-scheme-emscripten and let it recreate again.

**Comment by nomelif** [comment]
> Never mind, that seems right. Maybe you can just delete chibi-scheme-emscripten and let it recreate again.

I am not quite sure what you meant by that, I tried to

```
rm chibi-scheme-emscripten
CC=emcc make js
```

But that gave me the same error as before.

Is https://github.com/ashinn/chibi-scheme/pull/744 about this? I tried the same steps on it, but got further.

Thanks for helping me.

**Comment by nomelif** [comment]
Also I went ahead and tested emcc 2.0.0 as it was discussed in that pr. It also seems broken to me with newest master chibi-scheme. [This](https://pastebin.com/3HRXrUHF) is the error.

**Comment by pclouds** [comment]
Your problem is probably with this `CC=emcc` part. 'js' target will create a native chibi binary _and_ a wasm, but by forcing CC to emcc, I guess the native one becomes wasm too, which cannot be executed directly. Just do

    make js

and see how it goes. #744 would happen after you get past your error. I was testing on 2.0.18 and it went ok. Let me know how it goes

**Comment by nomelif** [comment]
Ah, by the looks of it that would seem to work on my setup as well. Thank you very much.
