### ISSUE TITLE
`display` doesn't treat strings specially inside containers

### ISSUE THREAD

**Issue by arvyy** [ashinn/chibi-scheme#750]
https://github.com/ashinn/chibi-scheme/blob/05c546e38d886a660018c6d9a3c6bec2bcf325d7/lib/scheme/write.sld#L8

For example, `(display (list "a"))` shows `("a")` instead of `(a)`

**Comment by arvyy** [comment]
Nevermind, closing. It seems it's unspecified / implementation dependent, so not a bug.

**Comment by ashinn** [comment]
It's not exactly clear in the spec.  I think what other impls output is what was intended.  On the other hand, I don't see the point of that semantics.  Personally I think it's best to deprecate `display` given that we have `write-string` and `write-char` and various formatting SRFIs.
