### ISSUE TITLE
(vector-find-median) error

### ISSUE THREAD

**Issue by arkoort** [ashinn/chibi-scheme#754]
Code:

```scheme
(import (scheme base)
        (scheme show)
        (scheme sort))

(define ls '(18.0 11.0 20.0 15.0 16.0 9.0 24.0 15.0 21.0 20.0))

(define (main args)
  (show #t (joined displayed (list-sort < ls) " ") nl
        (vector-find-median < (list->vector ls) +nan.0) nl))
```

Result:

```
9.0 11.0 15.0 15.0 16.0 18.0 20.0 20.0 21.0 24.0
16.5
```

The first line tells us that the middle elements are ```16.0 18.0```, so median
must be 17.0, but it is reported as 16.5.

If I understand right, the reason is following ([srfi/132/sort.scm](https://github.com/ashinn/chibi-scheme/blob/f3bccf1f7b5a30a40824375ac0910c62c9b0e2a9/lib/srfi/132/sort.scm#L169)):

```scheme
(vector-separate! < vec mid)
(cond
 ((odd? len) (vector-ref vec mid))
 (else (mean (vector-ref vec (- mid 1)) (vector-ref vec mid))))
```

The vector is only separated, not sorted, and elements in positions `(- mid 1)`
and `mid` are `<= 16.00` and `>= 18.0`, not `==`.

**Comment by ashinn** [comment]
Actually, the element in position mid is guaranteed the be = 18.0.

**Comment by arkoort** [comment]
Thank you. :)
