### ISSUE TITLE
(chibi parse): parse-ignore does not work with last parse-seq element

### ISSUE THREAD

**Issue by nmeum** [ashinn/chibi-scheme#757]
I am using the following chibi-scheme version:

```
chibi-scheme 0.10.0 "neon" (chibi r7rs ratios complex uvector threads full-unicode modules dynamic-loading unix little-endian)
```

With the following test program:

```Scheme
(import (scheme base) (scheme write) (chibi parse))

(define my-parser
  (parse-seq
    (parse-char #\a)
    (parse-ignore (parse-char #\b))))

(display (parse my-parser "ab"))
```

I would expect this program to output `(#\a)`. Unfortunately, it does output `(#\a (ignore))` instead.

If the last element of the `parse-seq` list is not `parse-ignore`, everything works as expected:

```Scheme
(import (scheme base) (scheme write) (chibi parse))

(define my-parser
  (parse-seq
    (parse-char #\a)
    (parse-ignore (parse-char #\b))
    (parse-char #\c)))

(display (parse my-parser "abc"))
```

Outputs `(#\a #\c)` as one would expect. As such, I believe this to be a bug in `parse-seq`.

**Comment by ashinn** [comment]
Yep, that's a bug, will fix shortly.
