### ISSUE TITLE
Ship SRFI 28?

### ISSUE THREAD

**Issue by lassik** [ashinn/chibi-scheme#759]
What's your stance on shipping SRFI 28 (Basic Format Strings) with Chibi? It's the simplest format SRFI, 30 lines of code, and is widely supported (by 18 implementations, if my count is correct).

Otherwise, we could ship a `(srfi 28)` package in snow-fort. There's already the `(rapid format)` package by @mnieper but it doesn't use the `(srfi 28)` library name so it's not as convenient to import from portable code.

**Comment by ashinn** [comment]
I'll package this for snow-fort.  Chibi has SRFI 166 natively.

**Comment by lassik** [comment]
I have uploaded a `(srfi 28)` library to http://snow-fort.org/pkg. It's a repackaging of the SRFI's sample implementation with minimal changes for R7RS compatibility. The code is hosted at [the SRFI's official repo](https://github.com/scheme-requests-for-implementation/srfi-28) in the `srfi` directory.
