### ISSUE TITLE
Bug: for-each, map, etc. don't iterate if the argument is not a list

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#766]
`(map (lambda (x) x) #(1 2 3 4 5)) => ()`
`(map (lambda (x) x) "abcde") => ()`

and similarly for `for-each` etc.

I'm guessing that it thinks non-lists are improper lists and it ignores the tail.

`(map (lambda (x) x) '(1 2 . 3)) => (1 2)`

**Comment by lassik** [comment]
SRFI 1 has `null-list?` for this purpose.

**Comment by ashinn** [comment]
Yes, basically it allows improper lists (which is also shorter and easier to implement).  This is not so useful and can confuse people so I'll change it.

**Comment by ashinn** [comment]
... unfortunately I actually abuse this in some places :(

**Comment by ashinn** [comment]
Fixed in 18d0adf13ba2a854f73fd0febf90e51ca86e13c0
