### ISSUE TITLE
ffi: pid_t should be a signed type

### ISSUE THREAD

**Issue by leahneukirchen** [ashinn/chibi-scheme#769]
```
% chibi-scheme -m chibi.process -m chibi.ast
> (waitpid -1 0)
(340282366920938463463374607431768211455 32598)
> (errno)
10
```

The car should be -1, but it's interpreted as an unsigned number. Alternatively it could return `#f`, but that requires special casing since `errno` won't work as a return type.

Note that POSIX specifies pid_t to be signed, see https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/types.h.html so I think this should not break anything.

**Comment by ashinn** [comment]
Thanks for the report!
