### ISSUE TITLE
force raises an error with promise created by delay-force

### ISSUE THREAD

**Issue by ktakashi** [ashinn/chibi-scheme#776]
This raises an error
```scheme
(import (scheme lazy))
(define p (delay-force (+ 1 1)))
(force p)
;; ERROR in promise-done? on line 1280 of file /usr/local/share/chibi/init-7.scm: car: not a pair: 2
```
I'm not entirely sure if this is an invalid behaviour of R7RS, as the specification says `(delay-force <expression>)` is conceptually the same as `(delay (force <expression>))` while `force` only accepts a promise (and the above snippet obviously doesn't return any promise)

Other info:
```
$ chibi-scheme -V
chibi-scheme 0.10.0 "neon" (chibi r7rs ratios complex uvector threads full-unicode modules dynamic-loading darwin bsd macosx little-endian)
```

**Comment by mnieper** [comment]
This is an error according to R7RS.  Implementations are allowed to treat non-promise values as (trivial) promises when forced but are not required to. So Chibi's behavior is correct.

Operationally, `(delay-force <expression>)` is, in fact, equivalent to `(delay (force <expression>))`. (That the former allows iterative algorithms to run in bounded space is not really observable through standard procedures. See SRFI 226 for an implementation of promises that makes `delay-force` superfluous.)

**Comment by ktakashi** [comment]
Okay, as I expected (though the specification seems a bit misleading or vague to me, as it doesn't explicitly say `<expression>` should return a promise or so).
Thx

**Comment by mnieper** [comment]
> Okay, as I expected (though the specification seems a bit misleading or vague to me, as it doesn't explicitly say `<expression>` should return a promise or so).
> Thx

The difference to `force` is that `delay-force` is syntax, and not a procedure, so the entry format is different. But `delay-force` explicitly says that effectively `(force <expression>)` is evaluated which requires `<expression>` to evaluate to a promise per description of `force`.
