### ISSUE TITLE
Nonsensical program that crashes chibi-scheme

### ISSUE THREAD

**Issue by leahneukirchen** [ashinn/chibi-scheme#792]
This is a reproducer, originating from a program that used `do` wrongly:

```
(import (chibi))

(if #t
    (do
        (begin))
    (do
        (begin)))
```

This crashes chibi-scheme 0.10 and git 9a172545 in `sexp_get_stack_trace` on Linux x86_64.

**Comment by ashinn** [comment]
Bizarre.  Taking a look.

**Comment by ashinn** [comment]
Chibi was compiling all 3 of the test, pass and fail expressions in an if before checking if any were errors.  If two of them had compile errors, the compile time state got confused, which should be fixed but it's simpler for now to just check for errors one at a time.

**Comment by leahneukirchen** [comment]
This explains why I couldn't get rid of the `if`. Thanks!
