### ISSUE TITLE
Wrong definition of `reduce-right` of SRFI-1

### ISSUE THREAD

**Issue by ytaki0801** [ashinn/chibi-scheme#799]
`reduce-right` definition of SRFI-1 is wrong. Explanation of "in other words" in the [SRFI-1 document](https://srfi.schemers.org/srfi-1/srfi-1.html) is not covering for the first element of *list*. See the document and [reference implementation]( https://github.com/scheme-requests-for-implementation/srfi-1/blob/master/srfi-1-reference.scm) for details. Here is my sample code to fix derived from the reference implementation.
```scm
diff --git a/lib/srfi/1/fold.scm b/lib/srfi/1/fold.scm
index 2ac1564..73ca0e7 100644
--- a/lib/srfi/1/fold.scm
+++ b/lib/srfi/1/fold.scm
@@ -42,7 +42,11 @@
   (if (null? ls) identity (fold f (car ls) (cdr ls))))
 
 (define (reduce-right f identity ls)
-  (if (null? ls) identity (fold-right f identity ls)))
+  (if (null? ls) identity
+      (let lp ((ls1 (car ls)) (ls (cdr ls)))
+        (if (pair? ls)
+            (f ls1 (lp (car ls) (cdr ls)))
+            ls1))))
 
 (define (unfold p f g seed . o)
   (let lp ((seed seed))
```

**Comment by ashinn** [comment]
The SRFI 1 document clearly uses the ridentity in all expansions and states "in other words, we compute (fold-right f ridentity list)" which is what the Chibi implementation does.  I suspect this is a bug in the SRFI 1 reference implementation which _doesn't_ use ridentity in the non-empty list case.

Since it is an identity it shouldn't matter, but that's just a calling convention, and users could provide a non-identity argument, in which case we should fix the SRFI 1 implementation.

**Comment by ytaki0801** [comment]
Thank you for reply. I wonder some have been supposing `reduce-right` just as a left-to-right version of `reduce` to implement regardless of describing in SRFI-1. I am now considering to keep in touch with the SRFI-1 mailinglist, although I do not know if it is proper manner to settle this issue or not...

**Comment by pclouds** [comment]
> I am now considering to keep in touch with the SRFI-1 mailinglist, although I do not know if it is proper manner to settle this issue or not...

If anything, the SRFI editor is still very active and can contact more people when you bring up the problem.

**Comment by ashinn** [comment]
Actually, it was probably the intention to be a left-to-right version of `reduce`.  It's worth bringing up on the list for clarification.

**Comment by ytaki0801** [comment]
Thank you for comments. Ok, so I am going to send to the list about the issue before long, not for the specification but the reference implemtation of `reduce-right`. In fact, the both `reduce-right` implementations are still satisfying the SRFI-1 specification just under *(f x ridentity) = x*, although the reference implementation of `reduce-right` seems to be *forced to define* as a left-to-right version of the reference implementation of `reduce` also under other *f* and *ridentity* arguments...
