### ISSUE TITLE
SRFI 166 numeric/si problem with 0 and -1

### ISSUE THREAD

**Issue by tkurtbond** [ashinn/chibi-scheme#801]
I tried this with chibi-scheme 0.10 and commit f812bbc96b2d624df3fa1f02bfa0de93336e20de, which was head at the time I checked this today, and both had the same result.
```
$ chibi-scheme
> (import (srfi 166))
> (show #f (numeric/si 1024))
"1k"
> (show #f (numeric/si 0))
ERROR in "inexact->exact": exact: not a finite number: +inf.0
> (show #f (numeric/si -1))
ERROR in "floor": invalid type, expected Number: 0.0+0.45479211794728047i
>
```
You might say si units only make sense for strictly positive non-zero values, but if nothing else, I'd expect a better error message if that that is the case.

(I tried this in chibi-scheme because of an email on the CHICKEN Scheme users mailing list about a similar problem with the fmt egg, also written by Alex Shinn that is similar to SRFI 166, but I can't find the email in the web interface of the mailing list to link to here.)

**Comment by ashinn** [comment]
Thanks!  That was definitely an oversight, I'm surprised I didn't have test cases for it.
