### ISSUE TITLE
Inconsistency in string->number

### ISSUE THREAD

**Issue by vmanis** [ashinn/chibi-scheme#811]
I observed the following behaviour in the current git checkout.

```
bash-5.1$ chibi-scheme 
> (string->number "123%4")  
#f
> (string->number "123*4")
#f
> (string->number "123,4")
123
> 123,4
123
> ERROR: invalid use of auxiliary syntax: unquote
```
I would think that the result for 123,4 is incorrect. The error message indicates a violation of the last paragraph of the specification of string->number.

**Comment by ashinn** [comment]
The comma starts a new token - this parses as 123 followed by (unquote 4).  You get the same behavior in Chez.

**Comment by vmanis** [comment]
On 2022-02-02 4:44 p.m., Alex Shinn wrote:
>
> The comma starts a new token - this parses as 123 followed by (unquote 
> 4). You get the same behavior in Chez.
>
> Message ID: ***@***.***>
>
bash-5.1$ scheme
Chez Scheme Version 9.5.7.4
Copyright 1984-2021 Cisco Systems, Inc.

 > (string->number "123,4")
#f
 > 123,4
123
 >
Exception: misplaced aux keyword (unquote 4)
Type (debug) to enter the debugger.

bash-5.1$ chibi-scheme
 > (string->number "123,4")
123
 > 123,4
123
 > ERROR: invalid use of auxiliary syntax: unquote

Both Chez and Chibi complain about the misuse of unquote. However, Chez 
has string->number yield #f (complying with that last paragraph), while 
Chibi returns the numerical equivalent of the prefix.

-- v

**Comment by ashinn** [comment]
Ah, sorry, this is the more general issue that `(string->number "123   4") => 123`.

**Comment by vmanis** [comment]
On 2022-02-03 7:35 p.m., Alex Shinn wrote:
>
> Ah, sorry, this is the more general issue that |(string->number "123 
> 4") => 123|.
>
Thanks -- v
