### ISSUE TITLE
= can be not transitive

### ISSUE THREAD

**Issue by FrankHB** [ashinn/chibi-scheme#812]
R7RS requires `=` to be transitive.

However, with a case from [this page](https://codewords.recurse.com/issues/one/when-is-equality-transitive-and-other-floating-point-curiosities): `(= 9007199254740992.0 9007199254740993)` => `#t`.

This is not conforming. The requirement is same from R5RS to R7RS, and there is a note in R7RS stating "the implementation  approach of converting all arguments to inexact numbers if any argument is inexact is not transitive".

(I'm not sure whether this is intended in R6RS, since [this ticket](https://small.r7rs.org/ticket/367/) suggests inexact contagion is allowed generally.)

**Comment by ashinn** [comment]
Yes, that requirement dates back to at least R4RS, along with the note:

> The traditional implementations of these predicates in Lisp-like languages are not transitive.

which is in fact still true today - Chez and Racket both return `#t` here.  Gambit gets this right though.

**Comment by mnieper** [comment]
For R6RS, returning `#t` is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).

The R7RS, the same general caveat can be found on page 36, so I would say that Chibi's behavior is compliant.

**Comment by FrankHB** [comment]
> Yes, that requirement dates back to at least R4RS, along with the note:
> 
> > The traditional implementations of these predicates in Lisp-like languages are not transitive.
> 
> which is in fact still true today - Chez and Racket both return `#t` here. Gambit gets this right though.

Yes, Chez and Racket both return `#t`, as well as some other implementations like [Gauche](https://github.com/shirok/Gauche/issues/805).

I've also [reported this to Chez](https://github.com/cisco/ChezScheme/issues/606), but there is no reply yet.

As of Racket, it seems OK because Racket is not conforming to RnRS by default, and there is no similar guarantee [in its documentation](https://docs.racket-lang.org/reference/generic-numbers.html#%28def._%28%28quote._~23~25kernel%29._~3d%29%29) (it can even accept different number of arguments). It might deserve checking against its implementation of `r5rs` and `r6rs` modules, but I'm not that sure about how much conformance is actually guaranteed by the simulated environments.

OTOH, (as I've verified) Chicken 5.3.0, Guile 2.2.7 and Gambit 4.9.4 are conforming.

The divergence is not similar to the treatment of exact 0 divisors in the [mentioned ticket](https://small.r7rs.org/ticket/367/), so there might be some other tips about implementation strategies I've missed.

(Interestingly, this note is not in R7RS. Is the tradition changed during these days?)

**Comment by FrankHB** [comment]
> For R6RS, returning `#t` is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).
> 
> The R7RS, the same general caveat can be found on page 36, so I would say that Chibi's behavior is compliant.

> For R6RS, returning #t is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).

The caveat is about to compare among inexact numbers, not covering the cases of comparing between an inexact number an exact number here.

I see the intention of the note reflecting the precision problems of comparing small floating-pointer numbers. When practically dealing with such implementations of inexact numbers, it is often good to take things like [machine epsilon](https://en.wikipedia.org/wiki/Machine_epsilon) into account, to prevent accumlated errors during multiple steps of computations. However, this is not always the case, in particular where the floating-point number (not necessarily from the result of some other computations) can assumed to be precise because the representation is exact, e.g. floating-point zeroes (+0.0 and -0.0). Actually I routinely turn off the [Wfloat-equal] warning of GCC in such contexts for this exact reason.

If not so, this seems strange. The requirement in R6RS (using the word "must") should be clear enough, and R7RS even has clearer wording. Even there are general rules (if any), it should overriding them, or it should simply not exist here (to prevent suspicious logical inconsistency problems). But I found nothing further explainations, like in the errata.

Moreover, notes are not normative rules; they should not determine the critera of conformance by their own.

**Comment by mnieper** [comment]
> > For R6RS, returning `#t` is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).
> > The R7RS, the same general caveat can be found on page 36, so I would say that Chibi's behavior is compliant.
> 
> > For R6RS, returning #t is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).
> 
> The caveat is about to compare among inexact numbers, not covering the cases of comparing between an inexact number and an exact number here.

I don't see a meaningful difference here.

> If not so, this seems strange. The requirement in R6RS (using the word "must") should be clear enough, and R7RS even has clearer wording. Even there are general rules (if any), it should overriding them, or it should simply not exist here (to prevent suspicious logical inconsistency problems). But I found nothing further explanations, like in the errata.
> 
> Moreover, notes are not normative rules; they should not determine the criteria of conformance by their own.

The note just highlights a specific case of what is said on page 11 (R6RS) about inexact numbers.

The question of transitivity is a mathematical property like whether `+` is addition. The reports say that `(+ z1 z2 ...)` evaluates to the addition of the arguments. Addition is clearly associative, so the report implies that `+` is associative.

However, in practice, this is not the case for adding inexact (IEEE) numbers. So claimed mathematical properties in the reports when applied to inexact numbers must have been meant to be taken modulo inexactness limitations. There is no reason to treat transitivity differently than the addition (or associativity) property, etc. Other interpretations lead to inconsistencies.

I'm not fully satisfied with the wording in both reports, though.

**Comment by ilammy** [comment]
> I see the intention of the note reflecting the precision problems of comparing small floating-pointer numbers.

Magnitude of numbers affects the ideal, mathematical interpretation of comparison. Implementation practicalities limit *significant digits* of inexact numbers – that's where they are inexact.

With IEEE `float64` you cannot compare 295147905179352825855.0 (2<sup>68</sup> − 1) exactly with integers, since its encoding can mean any integer in the [295147905179352809472, 295147905179352858624] range. They are indistinguishable, as far as IEEE is concerned.

Unless you're using arbitrary-precision inexact numbers, I don't think you can meaningfully achieve the behavior you seem to desire. While using something like MPFR for inexact numbers is a valid implementation approach, I doubt the reports have that in mind as a requirement.

**Comment by mnieper** [comment]
In fact, the sense of the implementation suggestion in R7RS saying that "converting exact numbers to exact numbers that are the same (in the sense of =) to them will avoid this problem, ..." is not completely clear to me. Firstly, there seems to be a circular reference to `=`; secondly, there is, in general, more than one exact number to convert to, and `=` will then depend on that choice.

**Comment by ilammy** [comment]
It's more of a question how do you interpret `1000.0` when it's being read.

Is this 1000 exactly? Or is it 1000.0 with 5 significant decimal digits? So now 1000.00 and 1000.0 are different numbers? Should they be different from 1000.00000000000001 – which cannot be represented exactly with `float64`?

**Comment by ashinn** [comment]
Setting aside the unclear wording in the standards, it is certainly possible to implement `=` to always be transitive, and in fact several implementations get it right.  There are a finite number of floating point numbers, just map each deterministically to a rational number (e.g. with `(rationalize x ulp)`).

If I can fix this in Chibi without much performance hit (in size or speed) I will do so.  Possibly speed isn't crucial since you tend not to compare inexact with exact?  I'm busy lately though, and this is somewhat lower priority.

**Comment by mnieper** [comment]
I think the issue was not whether it is possible to implement `=` to be always transitive (after all, even `+` can be made strictly associative for inexact values), but whether it is a meaningful requirement. And whether it is even required by the wording of the standard. I have doubts about both.

**Comment by ashinn** [comment]
For practical applications I don't think this is a big deal.  For pedagogic purposes it matters.

**Comment by luke21923** [comment]
For learners, it is nice if the rules of automatic numerical conversions are consistent across arithmetic operations and arithmetic comparisons. It means that you don't need to know which arithmetic procedure is applied to find out how the arguments will be evaluated.

Automatically applying `exact` to the inexact arguments of `=` (when there is at least one exact argument) would break this consistency. This is what MIT Scheme does, and it leads to this:

    1 ]=> (< (+ 9007199254740993 0.01) 9007199254740993)
    
    ;Value: #t

(the bignum on the left is converted to a floating-point number and then converted back to a *smaller* bignum, just before the bignum comparison).

Whereas in Chibi Scheme you get:

    > (< (+ 9007199254740993 0.01) 9007199254740993)
    #f

(the bignum on the left is converted to a floating-point number and stays that way during the floating-point comparison).

**Comment by mnieper** [comment]
From the wording of the specifications of `exact` and `inexact` in the report (R7RS), it seems (unless an implementation restriction is hit) that the following should be true:

```scheme
(= z (exact z))
```

and

```scheme
(= z (inexact z))
```

for all finite numbers `z`. If `=` is implemented by converting all arguments to exact ones when applied to arguments of mixed exactness, the second assertion would only hold when `(exact (inexact z))` for any exact `z` would evaluate to `z`. This is, in general, not the case for a typical implementation, which supports only a finite number of inexact values but a countably infinite number (at least in principle) of exact values.

On the other hand, a typical implementation can implement `exact` to be a section of `inexact`, that is `(inexact (exact z))` for any inexact `z`. If `=` converts all arguments to inexact values in case of mixed exactness, the above two assertions will then hold, but not the transitivity.

**Comment by luke21923** [comment]
So, you imply that R7RS compliance cannot be achieved by either one of those two simple strategies (apply `exact` or `inexact` to all arguments of `=` in case of mixed exactness).

(Could you please check/edit the first sentence of your last paragraph? I think you meant "that is `(inexact (exact z))` **evaluates to `z`** for any inexact `z`".)

**Comment by ilammy** [comment]
Speaking aside, I realized where my understanding was wrong.

Consider comparison between

　　a = `295147905179352809472`
　　b = `295147905179352825855.0`
　　c = `295147905179352858624`

If exact-inexact comparison is implemented by converting exact numbers into inexact representation (by deterministically choosing the closest inexact number), this breaks transitivity of equivalence because `(= a b)` and `(= b c)` are `#t`, but naturally `(= a c)` is not.

However, if exact-inexact comparison will convert inexact number `b` to some exact number deterministically, then transitivity will be observed, as exact `b` cannot be equal to `a` and `c` at the same time, which makes result of `(= a c)` irrelevant for transitivity.

The same reasoning applies to (total) ordering. Assuming conversion to inexact: if numbers are sufficiently close to be compared equal because of imprecision of inexact numbers – some numbers are definitely not `<` or `>` than each other, and so no violation of transitivity occurs. Otherwise, if all numbers are distinguishable, they'd be properly ordered. Conversion to exact will have these property as well, it does not matter for ordering.

Infinities and nans are not equal to any exact number, so again – no violation of transitivity here. `<` and `>` are always false if any argument is nan, so no violation here either. Infinities are distinguishable by `<` and `>` from any exact number, so transitivity will work for them as intended.

**Comment by mnieper** [comment]
> Where is it implied that `(= z (inexact z))` be true? That clearly can't work.

In the specification of `inexact`, R7RS says that "If an exact argument has no reasonably close inexact equivalent (in the sense of `=`), then a violation of an implementation restriction may be reported."

Now, `=` is a binary-valued predicate, defining a discrete topology. "Reasonably close" can logically therefore only mean "equal (in the sense of `=`)" if the above sentence cited from the spec is supposed to have any meaning.

The following is subjective, of course, but I think that maintaining `(= z (inexact z))` is more important and practically more useful (and also helps explain `inexact`) than forcing transitivity of `=`.

**Comment by FrankHB** [comment]
> > > For R6RS, returning `#t` is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).
> > > The R7RS, the same general caveat can be found on page 36, so I would say that Chibi's behavior is compliant.
> > 
> > 
> > > For R6RS, returning #t is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).
> > 
> > 
> > The caveat is about to compare among inexact numbers, not covering the cases of comparing between an inexact number and an exact number here.
> 
> I don't see a meaningful difference here.
> 

Comparing between inexact numbers is almost always implemented by directly mapping to comparing the underlying representations, that is, floating-point numbers, for most implementations. Typically there is no need to introduce any conversions because only one floating-point format is supported. The result is generally unreliable because there is no way to know how precise it is by its value own, despite of the existence of the conversions. But by the floating-point format itself, any single defined operation is still accurate; if the user assume the value is accurate, it is just reliable. Moreover, comparing over floating-point values (excluding NaNs) is transitive by definition of the underlying operation.

Comparing between exact numbers and inexact numbers is radically different. Since exact numbers and inexact numbers are mandated to be different in the language specification, and they can't share a same representation, and conversions are expected. Conversions in vain are wasteful, so there should be only one (same) conversion for each operand: either inexact to exact, or exact to inexact. Any conversion can be lossy with native implementations, and the transitive guarantee is immediately destroyed once a lossy conversion is introduced. Such unreliable is totally out of the control from the users' view.

Note that lossless conversions are still practically implementable (e.g. MPFR). So it is at least not meaningless for `=`. (Whether appropriate to require this property is a further question.)

The reasons of the unreliableness are quite different, so they deserve different treatments in this topic.


> > If not so, this seems strange. The requirement in R6RS (using the word "must") should be clear enough, and R7RS even has clearer wording. Even there are general rules (if any), it should overriding them, or it should simply not exist here (to prevent suspicious logical inconsistency problems). But I found nothing further explanations, like in the errata.
> > Moreover, notes are not normative rules; they should not determine the criteria of conformance by their own.
> 
> The note just highlights a specific case of what is said on page 11 (R6RS) about inexact numbers.
> 

I see nothing close to this on page 11 except "approximate representation".

> The question of transitivity is a mathematical property like whether `+` is addition. The reports say that `(+ z1 z2 ...)` evaluates to the addition of the arguments. Addition is clearly associative, so the report implies that `+` is associative.
> 
> However, in practice, this is not the case for adding inexact (IEEE) numbers. So claimed mathematical properties in the reports when applied to inexact numbers must have been meant to be taken modulo inexactness limitations. There is no reason to treat transitivity differently than the addition (or associativity) property, etc. Other interpretations lead to inconsistencies.
> 

I agree `=` should not be special and different to handling like `+`, ideally. However, the reports do have different descriptions on requirements on different operations. I don't think the requirement of `=` is unintentional in all these reports, although it is quite suspicious in R6RS.

And I don't think the interpretation must follow the practice of IEEE arithmetic. In the contrast, R6RS (on page 11) explicitly states:

> This report recommends, but does not require, that the IEEE floating-point standards be followed by implementations that use floating-point representations and that implementations using other representations should match or exceed the precision achievable using these floating-point standards.

**Comment by FrankHB** [comment]
> > I see the intention of the note reflecting the precision problems of comparing small floating-pointer numbers.
> 
> Magnitude of numbers affects the ideal, mathematical interpretation of comparison. Implementation practicalities limit _significant digits_ of inexact numbers – that's where they are inexact.

True. But that note is specifically about the problem of accuracy, not magnitude. With given precision (an implementation parlance of the formal notion of "significant digits"), both accuracy and magnitude are limited.

> Unless you're using arbitrary-precision inexact numbers and have a special category of "actually exact numbers that were read using inexact syntax", I don't think you can meaningfully achieve the behavior you seem to desire. While using something like MPFR for inexact numbers is a valid implementation approach, I doubt the reports have that in mind as a requirement.

Actually I'm not quite convincing of the feasibility of this requirement exactly for this practical reason: to introduce arbitrary-precision floating-point arithmetic seems too expensive in general. But there are also some counterarguments:

- The requirement seems to have a long history. No documents I found suggest to formally remove the requirement.
- The numerical tower is already a non-trivial and costly feature. So are `call/cc`, `dynamic-wind` and more. Many of them have stricter requirements of mandatory (i.e. there are less optional parts.) These features make Scheme distinguishing among many other languages.

**Comment by mnieper** [comment]
> > > > For R6RS, returning `#t` is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).
> > > > The R7RS, the same general caveat can be found on page 36, so I would say that Chibi's behavior is compliant.
> > > 
> > > 
> > > > For R6RS, returning #t is correct because of the general caveat noted on page 42 that comparing inexact numbers isn't reliable (so that the question of exact transitivity is meaningless).
> > > 
> > > 
> > > The caveat is about to compare among inexact numbers, not covering the cases of comparing between an inexact number and an exact number here.
> > 
> > 
> > I don't see a meaningful difference here.
> 
> Comparing between inexact numbers is almost always implemented by directly mapping to comparing the underlying representations, that is, floating-point numbers, for most implementations. Typically there is no need to introduce any conversions because only one floating-point format is supported. The result is generally unreliable because there is no way to know how precise it is by its value own, despite of the existence of the conversions. But by the floating-point format itself, any single defined operation is still accurate; if the user assume the value is accurate, it is just reliable. Moreover, comparing over floating-point values (excluding NaNs) is transitive by definition of the underlying operation.

What you describe is that the Scheme procedures involving inexact numbers are functions in the mathematical sense. Accuracy is a different thing. Even if I know that `1.0` represents the exact value, `(sin 1.0)` won't, in general, represent the exact value of the sine of its argument.

> Comparing between exact numbers and inexact numbers is radically different. Since exact numbers and inexact numbers are mandated to be different in the language specification, and they can't share a same representation, and conversions are expected. Conversions in vain are wasteful, so there should be only one (same) conversion for each operand: either inexact to exact, or exact to inexact. Any conversion can be lossy with native implementations, and the transitive guarantee is immediately destroyed once a lossy conversion is introduced. Such unreliable is totally out of the control from the users' view.

This is from an implementation perspective; from the abstract point of view (which is basically taken when exactness and inexactness are introduced), I still see no difference.
 
> Note that lossless conversions are still practically implementable (e.g. MPFR). So it is at least not meaningless for `=`. (Whether appropriate to require this property is a further question.)

Meaningless in the logical sense; I never meant meaningless in the sense of whether it can be implemented or not. You don't have to go as far as GNU MPFR, by the way. Just think of a Scheme system that only has one number representation (all rationals) and each number comes in two colors (exact and inexact).

> > > If not so, this seems strange. The requirement in R6RS (using the word "must") should be clear enough, and R7RS even has clearer wording. Even there are general rules (if any), it should overriding them, or it should simply not exist here (to prevent suspicious logical inconsistency problems). But I found nothing further explanations, like in the errata.
> > > Moreover, notes are not normative rules; they should not determine the criteria of conformance by their own.
> > 
> > 
> > The note just highlights a specific case of what is said on page 11 (R6RS) about inexact numbers.
> 
> I see nothing close to this on page 11 except "approximate representation".

My mistake. I think I meant the last paragraph of 3.2 on page 10.

> > The question of transitivity is a mathematical property like whether `+` is addition. The reports say that `(+ z1 z2 ...)` evaluates to the addition of the arguments. Addition is clearly associative, so the report implies that `+` is associative.
> > However, in practice, this is not the case for adding inexact (IEEE) numbers. So claimed mathematical properties in the reports when applied to inexact numbers must have been meant to be taken modulo inexactness limitations. There is no reason to treat transitivity differently than the addition (or associativity) property, etc. Other interpretations lead to inconsistencies.
> 
> I agree `=` should not be special and different to handling like `+`, ideally. However, the reports do have different descriptions on requirements on different operations. I don't think the requirement of `=` is unintentional in all these reports, although it is quite suspicious in R6RS.
> 
> And I don't think the interpretation must follow the practice of IEEE arithmetic. In the contrast, R6RS (on page 11) explicitly states:
> 
> > This report recommends, but does not require, that the IEEE floating-point standards be followed by implementations that use floating-point representations and that implementations using other representations should match or exceed the precision achievable using these floating-point standards.

That's true; but the standard certainly does not want to prohibit using the IEEE floating-point standards either.

**Comment by mnieper** [comment]
> Actually I'm not quite convincing of the feasibility of this requirement exactly for this practical reason: to introduce arbitrary-precision floating-point arithmetic seems too expensive in general. But there are also some counterarguments:
> 
>     * The requirement seems to have a long history. No documents I found suggest to formally remove the requirement.

Some parts of the report may have only survived because of copy-and-paste and because no one had the time to rethink a particular aspect. This is especially true for the requirement we are talking about as part of R6RS.

>     * The numerical tower is already a non-trivial and costly feature. So are `call/cc`, `dynamic-wind` and more. Many of them have stricter requirements of mandatory (i.e. there are less optional parts.) These features make Scheme distinguishing among many other languages.

Things like `call/cc` and `dynamic-wind` (which don't have to be costly just by being provided, by the way) are meaningful and useful. Forcing transitivity of `=` is not. Worse, it makes other assumptions (that are also implicitly in the reports) like `(= z (inexact z))` impossible (unless one has a bijection between exact and inexact numbers).

**Comment by mnieper** [comment]
> There are too many choices to build the mapping from the remaining things to ones defined by math. Operationally, voiding the transitivity requirement is definitely not a good beginning, because it does not reduce any of the choices; in the contrast, it will just provide more to choose.

In fact, dropping this requirement is crucial to give any guarantees for `exact` and `inexact`.

> Numerical programming is a plausible area here, but given the fact that most work are done using languages with explicit manifest typing, it is not as interesting as it sounds.
> 
> For a language with latent typing like Scheme, assumptions over operations (like transitivity) makes it far more easily statically analyze specific properties for the program transformation. Surely this won't make much sense to you (and actually most users), because such assumptions are mostly not intended to be consumed by programmers, but the program analyzers, esp. the optimizer. With transitivity on certain operands, an optimizer can just drop some of the operands without additional proofs. Such proofs are generally difficult, in particular within a language without a sophisticated manifest type system.

While I generally agree with you here, making use of the transitivity requirement is even in view of automated program analyzers quite far-fetched in my opinion.

In fact, along the same line, one can motivate that one should not drop that `(= z (inexact z))` always yields true. But this requirement is actually useful in practise and may be effectively useful for program analyzers.

Just adding arbitrary requirements to make the language more rigid doesn't help.

**Comment by FrankHB** [comment]
> > There are too many choices to build the mapping from the remaining things to ones defined by math. Operationally, voiding the transitivity requirement is definitely not a good beginning, because it does not reduce any of the choices; in the contrast, it will just provide more to choose.
> 
> In fact, dropping this requirement is crucial to give any guarantees for `exact` and `inexact`.
> 

1. Some more detailed proof?
2. I'm curious in this question as @ashinn: how do other implementation satisfying this requirement actually do? Are there buggy on `exact` and `inexact`? Or they simply do not conform to R7RS?

> > Numerical programming is a plausible area here, but given the fact that most work are done using languages with explicit manifest typing, it is not as interesting as it sounds.
> > For a language with latent typing like Scheme, assumptions over operations (like transitivity) makes it far more easily statically analyze specific properties for the program transformation. Surely this won't make much sense to you (and actually most users), because such assumptions are mostly not intended to be consumed by programmers, but the program analyzers, esp. the optimizer. With transitivity on certain operands, an optimizer can just drop some of the operands without additional proofs. Such proofs are generally difficult, in particular within a language without a sophisticated manifest type system.
> 
> While I generally agree with you here, making use of the transitivity requirement is even in view of automated program analyzers quite far-fetched in my opinion.
> 
> In fact, along the same line, one can motivate that one should not drop that `(= z (inexact z))` always yields true. But this requirement is actually useful in practise and may be effectively useful for program analyzers.
> 
I don't see its usefulness, mainly because I can hardly imagine in which cases such patterns will be useful in a program or its immediate representation:

1. For human programmers, one may get inexact numbers from computation results of numbers not in the range of rationals. But there are too few cases to deliberately produce an inexact value from an exact number and then compare with with other numbers.
2. For machines, inexact numbers provide too few details (boundary, precision, ...) to aid the reductions. Why use built-in inexact numbers instead of specialized records for reasoning?

> Just adding arbitrary requirements to make the language more rigid doesn't help.

True, but it is already there.
And removal of an existing requirement will certainly reduce the current set of guarantees, without improving portability. (Probably the only lucky thing: it is buggy not only in one implementations; it seems not widely adopted.)

**Comment by luke21923** [comment]
The report is not a formal document, it requires interpretation using common sense. If a change doesn't make sense, or is bad, then it is very likely that the report doesn't require it. So it is a good thing that you provided a rationale for your proposal.

> For a language with latent typing like Scheme, assumptions over operations (like transitivity) makes it far more easily statically analyze specific properties for the program transformation. Surely this won't make much sense to you (and actually most users), because such assumptions are mostly not intended to be consumed by programmers, but the program analyzers, esp. the optimizer. With transitivity on certain operands, an optimizer can just drop some of the operands without additional proofs. Such proofs are generally difficult, in particular within a language without a sophisticated manifest type system.

This is interesting. I don't know enough about optimising compilers to tell how much more optimised a program can be with this.

However, [as I mentioned earlier](https://github.com/ashinn/chibi-scheme/issues/812#issuecomment-1033772290), this potential speed gain comes at a *sizeable* cost in terms of code readability. Reading and writing arithmetical code is easier when mixed exact/inexact arguments are consistently converted to inexact arguments (for both `+` and `<`).

As for whether R7RS-small requires `=` to be transitive when applied to a mix of exact/inexact arguments, I have found a language-lawyer proof that it doesn't. Here it goes:

### Language-lawyer proof

The rules stated in the definition of `=` are:

1) `=` returns `#t` if its arguments are equal, and `#f` otherwise
2) `=` is required to be transitive

Even though the report allows an implementation to encode inexact numbers as finite-precision floating-point numbers, such an implementation necessarily violates the above definition. For instance, here is a violation of rule number 1 in Chibi Scheme: 

    > (= 9007199254740992.0 9007199254740993.0)
    #t

I don't see any indication about what such an implementation is required to do, when the definition of `=` cannot be respected. In particular, it is not specified whether the implementation must respect the complete definition on the maximum possible number of argument combinations, or if it must respect the maximum possible number of rules on all argument combinations, or if it must adopt any other behaviour.

I see a note (R7RS-small page 36) providing an advice on how to preserve rule number 2 on all argument combinations *(if the implementation whishes it)*, when the implementation necessarily violates the definition of `=`, because it encodes inexact numbers as finite-precision floating-point numbers.

**Comment by FrankHB** [comment]
> The report is not a formal document, it requires interpretation using common sense. If a change doesn't make sense, or is bad, then it is very likely that the report doesn't require it. So it is a good thing that you provided a rationale for your proposal.

This is a document as a widely adopted defac-to standard with normative rules. The requirement is actually not a change, as it is kept in several last versions. Nevertheless, I'm in doubt about whether it is really intended. However, there is still lack of the proof.

I have not make any proposal effectively besides pointing out the things I've found. I will try to, if it makes help.

> Reading and writing arithmetical code is easier when mixed exact/inexact arguments are consistently converted to inexact numbers (for both + and <).

Although I agree that `+` and `<` should ideally behave the same, I'm not very convinced by this point, due to the direction of reasoning.

To my experience, programmers will get things right easily if they known the exact rules, but not only the results, to determine the outcome.

For `+`, we don't expect the results can be exact if any one of the operand is inexact, because it makes no sense to guarantee any concrete results can be correct in such cases as per the math rules (pretending exact should not be correct). Breaking transitivity is a natural side effect.

However, for unary predicates like `zero?`, it should not follow the similar rules because it will be almost useless for inexact numbers if it does so. Since inexact is actually allowed, better avoid such design. Instead, there are caveats to users about the accuracy issue.

Binary predicates behave more complex: it is a predicate, so it should behave like `zero?` about the possible results; it is also an operation accepting more than one operand, so it allows the mixture of exact and inexact numbers as input.

The disagreement comes from the dilemma: when the behaviors conflict, and there are no math rules suggesting it definitely incorrect, which should be choosed for this?

Without considering the inpacts on the implementations, I choose the former. Generally, when implementing a pure function (without any side effects), the range of the results of the procedure is a more significant property then how it constraints on the input.

(The nature of predicates are often reflect in the precedure's name. In Scheme, `=` occasionally does not have a `?` postfix, but some other procedures with transitivity requirement do have, e.g. `char=?`; in some other designs of Scheme-flavor language like [Kernel](https://web.cs.wpi.edu/~jshutt/kernel.html), `=?` is used instead of `=`.)

So, the fact `=` is a predicate is more important than it is a binary arithmetic operation here.

This interpretation also looks like intentional in R7RS: the second note in page 36 mentions `=` and `zero?` together to sure how inaccuracy makes the results unreliable.

> For instance, here is a violation of rule number 1 in Chibi Scheme:

Although the rule of equality is not very clear, it still allows the result, because, from R7RS:

> 6.2.4 ... It is important to distinguish between mathematical numbers,  the Scheme numbers that attempt to model them, the machine representations used to implement the Scheme numbers, and notations used to write numbers. 

The rule of the equality relationship is defined mathematically on mathematical numbers, because by common sense, there are no other definitions not exposing the implementation details available (except comparing the written forms in the source, which is absurd). Computations of inexact numbers are explicitly allowed using "approximate methods" in 6.2.4. So, this is not a violation.

The rule of transitivity is directly defined on "these predicates", i.e. it constraints the operands in a call, irrespective to the domains of the operands (so there is also no need to differentiate which kind of numbers it constraints for this purpose). By common sense, "transitive" is defined by transitive relationship in math, which may cover any 2 operands in a call of these procedures, including `=`. Other procudures also having this requirement also do not necessarily specify the relationship on the domains of the operands (e.g. `char=?`).

Further, the first note in R7RS page 36 strongly supports this interpretation. The note is new in R7RS, so it is very likely that the author of R7RS clearly know the potentional unclear problems about the old specification, so they finally add this note.

> Also, the fact that rule number 2 contains the keyword "required" does not make it special or privileged compared to rule number 1, because rule number 1 is required as well.

True.

**Comment by luke21923** [comment]
### On the benefits of the proposal

> I have not make any proposal effectively, besides pointing out the things I've found. I will try to, if it makes help.

I assumed that you were proposing to make Chibi Scheme automatically convert the inexact arguments of `=`, `<`, `>`, `<=` and `>=` to exact numbers (with `exact`), when at least one of the arguments is exact. This is the behaviour of MIT Scheme, for instance.

> For `+` [...]. Breaking math properties on inexact number operands is a natural side effect. [...]
> 
> However, for unary predicates like `zero?`, it should not follow the similar rules because it will be almost useless for inexact numbers if it does so. Since inexact numbers are actually allowed, better avoid such design. Instead, there are caveats to users about the accuracy issue. [...]

`zero?` and `=` are useless for inexact (IEEE 754 binary64) numbers. Exact equality comparison involving an inexact floating-point number does not make sense:

    > (= 3 (/ 0.6 0.2))
    #f
    > (zero? (- 3 (/ 0.6 0.2)))
    #f

There is no point in trying to reverse that. Transitive or not, `zero?` and `=` (applied to inexact IEEE 754 binary64 arguments) are irrelevant. I really don't see how transitivity would make them useful again (except perhaps for the [argument](https://github.com/ashinn/chibi-scheme/issues/812#issuecomment-1034916585) about optimisation that you mentioned previously).

The only comparison procedures that make sense when applied to one or more inexact (IEEE 754 binary64) arguments are `<`, `>`, `<=` and `>=`.

> The disagreement comes from the dilemma: when the behaviors conflict, and there are no math rules suggesting it definitely incorrect, which should be choosed for this?
> 
> Without considering the inpacts on the implementations, I choose the former. Generally, when implementing a pure function (without any side effects in the call), the range of the results of the procedure is a more significant property then how it constraints on the input.

I am not convinced by that. In fact I don't understand how it is connected to any benefit of making `=` and `<` transitive.

I acknowledge that you are not convinced by the benefit of consistent conversion of arguments (for both `+` and `<`). I am not sure we will be able to agree on any of that.

> This interpretation also looks like intentional in R7RS: the second note in page 36 mentions `=` and `zero?` together to show how inaccuracy makes the results unreliable.

Let's look at that note:

    Note: While it is not an error to compare inexact numbers
    using these predicates, the results are unreliable because a small
    inaccuracy can affect the result; this is especially true of = and
    zero?. When in doubt, consult a numerical analyst.

Yes, that note groups `zero?` and `=` together. That note says that comparison predicates applied to inexact numbers (presumably IEEE 754 floating-point numbers) are **unreliable**, and that this is **especially true** for `=` and `zero?`. It means that `=` and `zero?` are *especially unreliable* when applied to inexact (IEEE 754 binary64) arguments. In other words, as I said before, they are useless. I acknowledge that `=` and `<` are predicates.

### Refutation of the language-lawyer proof

Now, let's talk about your arguments aimed at refuting my [language-lawyer proof](https://github.com/ashinn/chibi-scheme/issues/812#issuecomment-1035495818).

> > For instance, here is a violation of rule number 1 in Chibi Scheme:
> > `> (= 9007199254740992.0 9007199254740993.0)`
> > `#t`
> 
> Although the rule of equality is not very clear, it still allows the result, because, from R7RS:
> 
> > 6.2.4 ... It is important to distinguish between mathematical numbers,  the Scheme numbers that attempt to model them, the machine representations used to implement the Scheme numbers, and notations used to write numbers.
> 
> The rule of the equality relationship is defined mathematically on mathematical numbers, because by common sense, there are no other definitions not exposing the implementation details available (except comparing the written forms in the source, which is absurd).

This invalidates my proof. It is not obvious (at least to me), but the report defines the rules of `=` as being valid over "Scheme numbers", not over the *written form* of the numbers in the source code. Two numbers in *written form* designate the same "Scheme number" if the procedure `number->string` returns the same result with both numbers as argument.

For instance:

    > (number->string 9007199254740992.0)
    "9007199254740992.0"
    > (number->string 9007199254740993.0)
    "9007199254740992.0"

Notwithstanding what the report says, I still consider the evaluation of `(= 9007199254740992.0 9007199254740993.0)` => `#t` to be erroneous.

### Transitivity of `<`

`=` is useless on inexact finite-precision floating-point numbers, and, after all, I couldn't care less about what it returns (when applied to a mix of exact/inexact arguments). For the extremely rare cases *(floating-point bit twiddling)* where I would want to test the raw equality on inexact finite-precision floating-point numbers, I can afford to encapsulate the arguments inside `inexact` forms.

What really matters is the behaviour of the other comparison procedures `<`, `>`, `>=` and `<=`. Do the transitivity of *those* procedures is broken? I am trying to find three (exact and/or inexact) numbers **num1**, **num2** and **num3** such that:

`(< num1 num2)` => `#t`
`(< num2 num3)` => `#t`
`(< num1 num3)` => `#f`

or such that:

`(<= num1 num2)` => `#t`
`(<= num2 num3)` => `#t`
`(<= num1 num3)` => `#f`

But I didn't find any exemple so far.

If the transitivity of `<` and friends is not broken, then one solution to be R7RS-small compliant without causing too much problems would be:
1) To automatically convert the inexact arguments of `=` with the procedure `exact`, into exact numbers (when at least one initial argument is exact), and
2) To leave  `<`, `>`, `>=` and `<=` alone (keep the current behaviour of converting exact arguments to inexact when there is a mix of exact/inexact arguments).

This would introduce an unattractive discrepancy in the behaviours of the comparison procedures though.

**Comment by ashinn** [comment]
I'm enjoying this discussion but having trouble keeping up, and also think the Chibi issue tracker isn't the best place for it.  Someone should probably summarize and ask for wider feedback on the WG2 list.

For Chibi I remember I had already partially implemented this logic - bignum/flonum ordering works by converting the flonum to exact.  I had overlooked this for fixnums and ratios so have fixed that.
