### ISSUE TITLE
SRFI-22 script `main`s are called with the wrong argument

### ISSUE THREAD

**Issue by OrichalcumCosmonaut** [ashinn/chibi-scheme#814]
According to [SRFI-22](https://srfi.schemers.org/srfi-22/srfi-22.html):

> Upon invocation of a script, the Scheme system calls a procedure named `main` with one argument, a list of strings containing the Unix command-line arguments *to the script*, i.e. the elements of the `argv` vector of the Scheme script interpreter process from index 1 on. Thus, the first element of the list is the name of the script.

However, running the following script with Chibi:
```scheme
#! /usr/bin/env scheme-r7rs
(import (scheme base)
        (scheme write))

(define (main args)
	(write args)
	(newline)
	0)
```
produces the output (assuming it is named `test.scm`):
```
("main" "test.scm" "foo" "bar")
```
instead of the expected:
```
("test.scm" "foo" "bar")
```

**Comment by ashinn** [comment]
How are you running this?  chibi-scheme doesn't distribute a scheme-r7rs command.

**Comment by OrichalcumCosmonaut** [comment]
`scheme-r7rs` is a symlink to `chibi-scheme`, which is handled here:
https://github.com/ashinn/chibi-scheme/blob/82d61b3d8e50bacc266b450e21127663f3c39de5/main.c#L314-L324

Running the script in any of the following ways:
```
./test.scm # with #!/usr/bin/env scheme-r7rs
./test.scm # with #!/path/to/chibi-scheme -r
scheme-r7rs ./test.scm
chibi-scheme -r ./test.scm
```
produces the wrong output, with “main” added to the front of `args`.  I also modified the test script to also print `(command-line)` (from `scheme.process-context`), and it is broken in the same way.

However, if `(main (command-line))` is added to the end of the script and ran with `chibi-scheme` directly (i.e. `chibi-scheme ./test.scm` or via the equivalent shebang-line), it does work as expected.  It seems this is a bug with the `-r` option.
