### ISSUE TITLE
The linkers in the section of http://synthcode.com/scheme/chibi#h2_StandardModules take us to the empty page

### ISSUE THREAD

**Issue by APIPLM** [ashinn/chibi-scheme#817]
As going to check the documentation of the ` (chibi ast) `  module on the [website](http://synthcode.com/scheme/chibi). then come to
[ the section ](http://synthcode.com/scheme/chibi#h2_StandardModules), then there is the linker for the documentation of the module. But it takes me to the empty webpage. The linker is http://synthcode.com/scheme/lib/chibi/ast.html. But in fact the linker https://synthcode.com/scheme/chibi/lib/chibi/ast.html is available for people to look the documentation of the ` (chibi ast) `  module

**Comment by ashinn** [comment]
Sorry, the top link should be http://synthcode.com/scheme/chibi/ with a trailing slash "/".

**Comment by ashinn** [comment]
The link from https://synthcode.com/wiki/chibi-scheme is correct, if there are any other bad links I'll fix them, and otherwise try to redirect if the trailing slash is omitted.
