### ISSUE TITLE
Segfault when `import` is used wrong

### ISSUE THREAD

**Issue by Oxyd** [ashinn/chibi-scheme#833]
I was poking around the REPL when I typed `import` by itself – without parentheses – and Chibi segfaulted:
```
% ./tools/chibi-run             
> import
./tools/chibi-run: line 3: 43554 Segmentation fault      (core dumped) LD_LIBRARY_PATH="$DIR": DYLD_LIBRARY_PATH="$DIR": CHIBI_MODULE_PATH="$DIR"/lib "$DIR"/chibi-scheme "$@"
```
Same effect when you ask Chibi to execute a file that beings with just `import` instead of `(import)`.

**Comment by lockywolf** [comment]
Fixed in `master`?

**Comment by ashinn** [comment]
Appears to be fixed.
