### ISSUE TITLE
Incomplete stack traces

### ISSUE THREAD

**Issue by dpapavas** [ashinn/chibi-scheme#834]
I mentioned the following in #813, but I'm reposting it as an issue, in case ti slipped your attention there.

I notice that stack traces (obtained via `sexp_get_stack_trace`, or via `sexp_exception_stack_trace`) seem to be incomplete.  Consider for instance a foreign procedure defined as

```C
static sexp foo(sexp ctx, sexp self, sexp_sint_t n, sexp x)
{
    sexp_assert_type(ctx, sexp_realp, SEXP_NUMBER, x);

    /* ... */

    return SEXP_VOID;
}
```
and exported via

```C
sexp_define_foreign(ctx, env, "foo", 1, foo);
```

If I call it from a file named, say `test.scm`, containing:

```Scheme
(foo "foo")
```

Then the stack trace I get from the thrown exception looks like:

```
#0 /usr/local/share/chibi/init-7.scm:1264
#1 /usr/local/share/chibi/init-7.scm:796
```

If I change the call to, say `(foo 42)`, and get the stack trace via `sexp_get_stack_trace` from within the C `foo` function, I get the same trace.  In any case, no stack frame with location within `test.scm` appears.

If I wrap `foo` in another function as in

```Scheme
(define (bar x) (foo x))

(display (bar "foo"))
```
I now get a more complete stack trace:

```
#0 test.scm:3
#1 /usr/local/share/chibi/init-7.scm:1264
#2 /usr/local/share/chibi/init-7.scm:796
```

But this seems to work only when the call is wrapped in another call (as in `display` here).  Am I doing something wrong?  If not, is there some way of getting a complete strack trace consistently?  (If work is required on the Chibi-Scheme side, I could *try* to help out, given some pointers.)

**Comment by lockywolf** [comment]
I may be wrong, but it seems that the call to `foo` is in a tail context, so it gets optimised out, naturally.

What if you compile chibi without TCO?

**Comment by ashinn** [comment]
Yes, this looks as expected due to TCO.  You don't need to recompile, you can disable TCO at runtime with `chibi-scheme -T`.
