### ISSUE TITLE
More incoplete stack traces

### ISSUE THREAD

**Issue by dpapavas** [ashinn/chibi-scheme#835]
This is a continuation of #834.  I meant to re-open the issue and keep discussion of all such (potential) problems in one place, but I can't, since I wasn't the one who closed it.

I don't really remember why I brought up this specific (and unfortunate) example any more, but my general problem is that I often get errors when evaluating scripts via my embedded chibi-scheme, where no stack frames are located inside my source (i.e. I only get frames inside `init-7.scm`).  Many of these instances may be due to errors inside tail calls (and I have added a switch to disable TCO, as in `-T` for that purpose), but I suspect not all of them are.

I briefly tried to recreate an error with incomplete stack trace and found the following:

```scheme
;; (foo 1 1)
;; (foo (let ((a 1)) a))
(foo (let ((a 1)) a) 1)
(list foo (let ((a 1)) a) 1)
```

Running this via `chibi-scheme` (with, or without `-T`) or via my application, results in "complete" stack traces with both of the commented out forms.  With any of the uncommented forms, all stack frames are inside `init-7.scm`.  This seems to be the case other forms, besides `let`:

```scheme
(list foo (case 1 ((1) 10) (else 20)) 1)
```

Similar input with e.g. `cond`, instead of `case` seems to be fine though.  Also note that if the error (the reference to `foo` here) is after the `let`/`case` form the resulting exception has a complete stack.

**Comment by ashinn** [comment]
Thanks for the report.  I tentatively fixed this by propagating more source info manually in let, but want to think on this a little more.  Arguably it may make sense for the top-level form returned by a macro expansion to always be overwritten with the call site source.

**Comment by ashinn** [comment]
Specifically, I still haven't seen any examples where a non-tail-call was omitted from the stack trace, but there is the fundamental problem/feature of macros expanding into the source location of the macro definition.

**Comment by dpapavas** [comment]
Thanks for looking into this so quickly.  I suspected this would be related to macro expansion and think I have found a similar issue, where a frame is missing when the error is within a form that is part of a (user-defined) macro.  I need to investigate it a bit more carefully though, which I should be able to do later tonight.

**Comment by dpapavas** [comment]
Upon more careful examination, this doesn't seem to be a case of a *missing* frame, but consider for example the following trivial macro invocation:

```scheme
(define-syntax plus-2
  (syntax-rules ()
    ((plus-2 exp ...) (+ 2 exp ...))))

(plus-2 foo 1)
```
The resulting stack trace is:

```
$ chibi-scheme -T -mscheme.small /tmp/test.scm 
ERROR on line 3 of file /tmp/test.scm: undefined variable: foo
  called from <anonymous> on line 1245 of file /usr/local/share/chibi/init-7.scm
  called from eval on line 1244 of file /usr/local/share/chibi/init-7.scm
  ...
```

The error appears reported at the location of the matching macro pattern.  This is not a serious issue in a trivial case such as this, but in more complex scenarios, you have no way of knowing where the error is really generated, other than that it is somewhere where the macro in question is expanded.

If I understand correctly that the alternative option you mention would remedy this, allowing the user to know where the error really originated, then I would thing that this is preferable, strongly so, as far as I can tell.  If it would be somehow possible to show both locations as separate frames (only one of which would be a real frame), that might be preferable still.

**Comment by ashinn** [comment]
I've gone ahead and made this change, closing for now.
