### ISSUE TITLE
Piping a process to another process.

### ISSUE THREAD

**Issue by lockywolf** [ashinn/chibi-scheme#838]
I would like to write an equivalent of "ls | grep bash" in chibi.

So far I have created the following code, which kind of works, but has some drawbacks:

```
(display
       (call-with-process-io
        "ls"
        (lambda (pid in out err)
          (close-output-port in)
          (let ((res (port->bytevector out)))
            (waitpid pid 0)
            (close-input-port out)
            (close-input-port err)
            (call-with-process-io
             "grep -F bash"
             (lambda (pid in out err)
               (write-bytevector res in)
               (close-output-port in)
               (let ((res (port->string out)))
                 (close-input-port out)
                 (close-input-port err)
                 res)))))))
```

1. It is verbose. Perhaps, not the worst thing ever, and I can write an ad-hoc function/macro to make it shorter, but a more "default" version would have been better.
2. It is buffering the whole output of `ls`, and only then is piping it into `grep`. While this is fine for small runs, it is not as good for production usage, as the bytevector might grow very large.

How hard would be to add something like a `fork/pipe` procedure from scsh? This would allow implementing something like the "pipe" macro, in the shape of `(| cmd1 cmd2)`. (Perhaps, all of the Chapter 2 would be too much work, but pipes would make life much easier, I suspect.)

**Comment by ashinn** [comment]
I had actually been working on a SCSH redesign for Chibi to make this kind of thing easier.  Let me share what I have later.

**Comment by ashinn** [comment]
I've just pushed a WIP but usable `(chibi shell)` library.  Expect changes.

**Comment by ashinn** [comment]
OK, this is fleshed out pretty well and has basic docs.  I'm liking it better than SCSH :)

**Comment by lockywolf** [comment]
Why is the sequencing command called `(do cmd1 cmd2 ... )`? For consistency with Scheme, I would have expected it to be called `begin`, if not some disjoint symbol?

**Comment by ashinn** [comment]
That was deliberate to avoid conflict with SCSH's `begin` which has a very different meaning.
