### ISSUE TITLE
snow-chibi is installing packages into $DESTDIR/$PREFIX, not into $PREFIX

### ISSUE THREAD

**Issue by lockywolf** [ashinn/chibi-scheme#844]
So, I am building chibi like this:

```
make -j$(nproc)     PREFIX=/usr LIBDIR=/usr/lib64 MANDIR=/usr/man SOLIBDIR=/usr/lib64 MODDIR=/usr/share/chibi-scheme DESTDIR=$PKG
make -j$(nproc) doc PREFIX=/usr LIBDIR=/usr/lib64 MANDIR=/usr/man SOLIBDIR=/usr/lib64 MODDIR=/usr/share/chibi-scheme DESTDIR=$PKG
make install        PREFIX=/usr LIBDIR=/usr/lib64 MANDIR=/usr/man SOLIBDIR=/usr/lib64 MODDIR=/usr/share/chibi-scheme DESTDIR=$PKG
```
This is basically taken from fedora.spec.

Then I package the installed tree and install it into the system. This works for running `chibi-scheme -R`, and such, and importing libraries works. However, installing packages does not do what I expect it to do, it installs the packages into `$DESTDIR`, where chibi, obviously, cannot later find them.

 UPD1:

If I run snow without snow.img, the result is slightly more meaningful. It installs the package into `/usr/local/share/snow/` . `chibi-scheme` still cannot find the package after installation, but  at least it does not go into the `$DESTDIR`.
That `$DESTDIR` is recorded somewhere in the snow.img, which I doubt is correct. Those images, after all, should only be used to speed up loading, if I am not mistaken.

**Comment by ashinn** [comment]
Can you try that last commit?

**Comment by lockywolf** [comment]
Can't chroot somewhere where there is no bash.

I guess, fedora's spec should work, since it is building the rpm in chroot by default.

Maybe just not use the image at all if DESTDIR is used? Should not really affect anyone who is already building in a chroot. 
(The more I think about it, the more I am finding it weird to make an image in install-time. An image is, after all, what it is called, and "image". An image of a process running from A/ should not be, in general, callable from B/. I can understand some runtime-cache, like java or c# do it, but they do it after they are installed into the final destination, and update the cache every so often.)

However, what I am really concerned with is that `/usr/local/share/snow` and `/usr/local/lib/snow`. I suspect they are coming from `./include/chibi/install.h:#define sexp_default_module_path "/usr/share/chibi-scheme:/usr/lib64/chibi:/usr/local/share/snow:/usr/local/lib/snow"` , although I am not really sure about that.

What is even more curious is that it actually manages to install something into `/usr/local/{share,lib}/snow`, even though those directories are not writable by non-root. Apparently, snow silently uses "sudo" :D. Okay, if so, then why not in /usr/share/chibi-scheme/chibi?

So, the installation is incomplete:
```
lockywolf@laptop:~/>find /usr/local/ -iname '*xattr*'
/usr/local/share/snow/independentresearch/xattr.sld
/usr/local/share/snow/independentresearch/xattr.scm
/usr/local/share/snow/independentresearch/.xattr.meta
```
the xattr.so is missing. I guess, compilation failed, but how would I find that out?

**Comment by ashinn** [comment]
chroot has nothing to do with bash.  Did you get an error?

Snow is not specific to chibi, so `/usr/local/share/snow` is intentional.  This is using prefix, not destdir, so WAI.

It looks like now you have a working snow installation and are separately seeing an issue installing a package?  What is the output of the snow command?

**Comment by lockywolf** [comment]
It is working if used with `--noimage`.

Then I can run 
```
/tmp/RAMFS>snow-chibi --noimage --verbose install ./independentresearch-xattr-0.2.tgz 
(installing files: ("./independentresearch-xattr-0.2.tgz") for chibi)
;; ("cc" "-fPIC" "-shared" "-Os" "-o" "/tmp/pkg-22209-1659424771-0/independentresearch/xattr.so" "/tmp/pkg-22209-1659424771-0/independentresearch/xattr.c" "-lchibi-scheme")
```
>Snow is not specific to chibi, so /usr/local/share/snow is intentional. This is using prefix, not destdir, so WAI.

No, the prefix is `/usr/`, not `/usr/local`. Sharing a repository makes sense, but sharing `.so` files is not so easy. I don't think that an xattr.so linked with `-lchibi-scheme` can be loaded with chicken.

**Comment by ashinn** [comment]
The question is, did the chroot command fail and if so how?

**Comment by lockywolf** [comment]
```
Generating images
LD_LIBRARY_PATH="/usr/local/lib:" DYLD_LIBRARY_PATH="/usr/local/lib:" CHIBI_MODULE_PATH="/usr/local/share/chibi:/usr/local/lib/chibi" chroot /tmp/bla-bla-find-me/. /usr/local/bin/chibi-scheme -mchibi.repl -d /usr/local/share/chibi/chibi.img
chroot: failed to run command ‘/usr/local/bin/chibi-scheme’: No such file or directory
make: [Makefile:399: install] Error 127 (ignored)
LD_LIBRARY_PATH="/usr/local/lib:" DYLD_LIBRARY_PATH="/usr/local/lib:" CHIBI_MODULE_PATH="/usr/local/share/chibi:/usr/local/lib/chibi" chroot /tmp/bla-bla-find-me/. /usr/local/bin/chibi-scheme -xscheme.red -mchibi.repl -d /usr/local/share/chibi/red.img
chroot: failed to run command ‘/usr/local/bin/chibi-scheme’: No such file or directory
make: [Makefile:400: install] Error 127 (ignored)
LD_LIBRARY_PATH="/usr/local/lib:" DYLD_LIBRARY_PATH="/usr/local/lib:" CHIBI_MODULE_PATH="/usr/local/share/chibi:/usr/local/lib/chibi" chroot /tmp/bla-bla-find-me/. /usr/local/bin/chibi-scheme -mchibi.snow.commands -mchibi.snow.interface -mchibi.snow.package -mchibi.snow.utils -d /tmp/bla-bla-find-me/usr/local/share/chibi/snow.img
chroot: failed to run command ‘/usr/local/bin/chibi-scheme’: No such file or directory
make: [Makefile:401: install] Error 127 (ignored)
```

**Comment by lockywolf** [comment]
```
echo "Generating images"
Generating images
LD_LIBRARY_PATH="/usr/lib64:" DYLD_LIBRARY_PATH="/usr/lib64:" CHIBI_MODULE_PATH="/usr/share/chibi-scheme:/usr/lib64/chibi" chroot /tmp/chibi-find-me-2/. /usr/bin/chibi-scheme -mchibi.repl -d /usr/share/chibi-scheme/chibi.img
chroot: failed to run command ‘/usr/bin/chibi-scheme’: No such file or directory
make: [Makefile:399: install] Error 127 (ignored)
LD_LIBRARY_PATH="/usr/lib64:" DYLD_LIBRARY_PATH="/usr/lib64:" CHIBI_MODULE_PATH="/usr/share/chibi-scheme:/usr/lib64/chibi" chroot /tmp/chibi-find-me-2/. /usr/bin/chibi-scheme -xscheme.red -mchibi.repl -d /usr/share/chibi-scheme/red.img
chroot: failed to run command ‘/usr/bin/chibi-scheme’: No such file or directory
make: [Makefile:400: install] Error 127 (ignored)
LD_LIBRARY_PATH="/usr/lib64:" DYLD_LIBRARY_PATH="/usr/lib64:" CHIBI_MODULE_PATH="/usr/share/chibi-scheme:/usr/lib64/chibi" chroot /tmp/chibi-find-me-2/. /usr/bin/chibi-scheme -mchibi.snow.commands -mchibi.snow.interface -mchibi.snow.package -mchibi.snow.utils -d /tmp/chibi-find-me-2/usr/share/chibi-scheme/snow.img
chroot: failed to run command ‘/usr/bin/chibi-scheme’: No such file or directory
make: [Makefile:401: install] Error 127 (ignored)
```

**Comment by ashinn** [comment]
Thanks!  Will take a look.  In the meantime, yes, the images are optional.

Ignoring DESTDIR, if you disagree with the choice of snow install directory you can file a separate ticket.  You're right, it's not honoring prefix, it's just hard-coded to /usr/local as part of the snow specification.  You can override it with your snow config.

**Comment by lockywolf** [comment]
FWIIW, preparing the chroot dir with bash, and some .so libraries, seems to make it work, although I probably need more testing.

**Comment by ashinn** [comment]
Yes, sorry, I realized you need the .so's (libc, libdl, libm) for the chroot to work.  I don't think you need bash though, there's no shell involved.

**Comment by ashinn** [comment]
Note snow paths are intentionally disjoint from chibi paths as of commit 26061930e9c3d01f50f5ff354908347f23ecd13d.

**Comment by lockywolf** [comment]
> Note snow paths are intentionally disjoint from chibi paths as of commit [2606193](https://github.com/ashinn/chibi-scheme/commit/26061930e9c3d01f50f5ff354908347f23ecd13d).

I think this is more about the other issue? https://github.com/ashinn/chibi-scheme/issues/845
Let's make this issue about the image using the DESTDIR. The other one would be about the target directories.

**Comment by ashinn** [comment]
For now just disabling image generation when DESTDIR is set.
