### ISSUE TITLE
snow-chibi gives a misleading error message when the repository-uri is wrong

### ISSUE THREAD

**Issue by lockywolf** [ashinn/chibi-scheme#846]
```
lockywolf@hostname>snow-chibi install independentresearch.xattr
Can't find package: (independentresearch xattr)
```

I suspect that this is a redherring? Because in the config file I have `(repository-uri "http://snow-fort.org/repo.scm")`, but this URL does not seem to exist. Returns 404.

**Comment by lockywolf** [comment]
So, by trial and error I have replaced the URL with `(repository-uri "http://snow-fort.org/pkg/repo/index.scm")` and it worked, but the error message is, obviously, misleading. It's not that "Can't find package", it's actually that "repository-url is not pointing to a valid repository".

**Comment by ashinn** [comment]
snow-fort is down, will take a look later

**Comment by ashinn** [comment]
Sorry, it looks like you have a bad config.  The URL is http://snow-fort.org/s/repo.scm - you're missing the /s/.

**Comment by lockywolf** [comment]
That config used to be okay ~2 years ago. A warning would have been nice :).

**Comment by ashinn** [comment]
I couldn't reproduce this - I was already getting warnings - but added more warnings just in case :)
