### ISSUE TITLE
`map` instead of `for-each` in `(shell cmd ...)`?

### ISSUE THREAD

**Issue by lockywolf** [ashinn/chibi-scheme#851]
Would it be fine replacing `for-each` with `map`?

`map` would return the result of `waitpid`, which is the pid and the exit status. A nice thing to have.

**Comment by ashinn** [comment]
Since the processes are all finished the pids no longer matter, but the status can be useful.  Maybe simpler to just return the status of the final process though.

**Comment by lockywolf** [comment]
Well, if it is intended to be a "nice awesome shell", then I would think about a list tree with exit statuses of the processes of the original tree.

But so far I have just replaced definition of the shell with 
```
(define-syntax shell
  (syntax-rules ()
    ((shell cmd ...)
     (cadar (map shell-wait (shell& cmd ...))))))
```

Which is giving me the exit status of the last command in the pipe.
