### ISSUE TITLE
`environment` returns a mutable environment; should be immutable per R7RS

### ISSUE THREAD

**Issue by dpk** [ashinn/chibi-scheme#863]
```scheme
(import (scheme eval))
(define my-env (environment '(scheme base)))
(eval '(define foo 23) my-env)
(eval 'foo my-env) ;;=> 23
```

R7RS small section 6.12 is clear (by the last example under the `eval` procedure) that defining things in an environment created by `environment` causes an error to be signalled.

The other possibility is that the ‘error is signaled’ language in the example it itself erroneous (an erratum in R7RS), and it should be changed to a bog-standard ‘it is an error’. (Although 1.3.2 defines the ‘error is signaled’ language separately to ‘an error that satisfies PREDICATE is signaled’, all other ‘error is signaled’ situations than this one do define an explicit relevant predicate as far as I can tell.)

It pains me slightly to report this bug since the program I’m currently writing depends on it. Could there also be a ~~`mutable-environment`~~ `make-environment` (name suggested by @johnwcowan) procedure which makes an environment in which things can be defined?

**Comment by johnwcowan** [comment]
+1 to fixing the bug and to being able to create mutable environments, but I propose the name `make-environment` to pair with `environment` (cf. `vector` vs. `make-vector` and many other such paired names).

**Comment by mnieper** [comment]
> +1 to fixing the bug and to being able to create mutable environments, but I propose the name `make-environment` to pair with `environment` (cf. `vector` vs. `make-vector` and many other such paired names).

I don't understand the analogy. Both `vector` and `make-vector` create a mutable vector. They just take different sets of arguments.

In view of this, Daphne's original suggestion of `mutable-environment` is much clearer.

By the way, the small language does not specify the behavior of mutable environments.

PS Assuming that the "error is signaled" in the last example of 6.12 is itself erroneous is the assumption that is most consistent with the rest of the small language.

**Comment by ashinn** [comment]
`make-environment` already exists, returning a new mutable empty environment.  Importing into this is how we implement `environment`.

So I've made the `environment` result immutable and added `mutable-environment`.
