### ISSUE TITLE
(modified-julian-day->date (date->modified-julian-day (current-date))) fails

### ISSUE THREAD

**Issue by arthurgleckler** [ashinn/chibi-scheme#869]
Forgive me if I'm misunderstanding something here.  I don't see SRFI 19 in the Chibi source code, but I am able to import it, so I assume that it's somehow supported.

```
> @import (srfi 19)
> (modified-julian-day->date (date->modified-julian-day (current-date)))
ERROR on line 987 of file /usr/local/share/chibi/srfi/srfi-19.scm: invalid type, expected Integer: 104934009695990022425/63
```

**Comment by ashinn** [comment]
Is this the SRFI 19 from snow-fort.org packaged by Geoff Taylor?

I don't use SRFI 19, I use `(chibi chrono)` (also on snow-fort).

**Comment by arthurgleckler** [comment]
Forgive me.  I must be picking it up from a long-ago installation using Snow.

**Comment by lassik** [comment]
I can't find a `(chibi chrono)` on snow-fort, nor in the Chibi repo.

**Comment by lassik** [comment]
No problem. Thanks!
