### ISSUE TITLE
Unexpected parsing of "#u8  ("

### ISSUE THREAD

**Issue by asurati** [ashinn/chibi-scheme#879]
The r7rs spec defines `#u8(` as a token. Yet, chibi-scheme succesfully parses it even after it is split:
```
> #u8 (1 2 3)
#u8(#x01 #x02 #x03)
```

**Comment by ashinn** [comment]
Yes, this syntax is not specified by the standard, so is a valid extension.  I don't think it's worth signaling an error here.
