### ISSUE TITLE
dlsym fails to load functions when using images

### ISSUE THREAD

**Issue by lubgr** [ashinn/chibi-scheme#880]
After building and installing current `master`, loading any of `chibi.img`, `red.img`, or `snow.img` using the `-i` flag results in the error message
```
dynamic function lookup failure: <static> (sexp_proc1)sexp_peek_u8_stub
```
This doesn't cause the process to terminate; running scripts or the REPL still works. The particular function failed to be `dlsym`-ed here differs.

Might this be an accidental regression from the static userlib or image generation changes? I'm happy to do further diagnostics on my end to make sure I haven't missed or misused something. I could reproduce this on up-to-date Archlinux and MacOS, both x86.

**Comment by ashinn** [comment]
I can't reproduce this for `chibi.img`, but can for the other images.  Those are functions loaded from other dynamic libraries, not `libchibi-scheme`, so either they aren't being loaded yet when the image is mapped, or dlsym is failing to find them.  I'll take a look when I find time.
