### ISSUE TITLE
ffi question - how to pass a pointer to a (static) boolean variable to C from scheme?

### ISSUE THREAD

**Issue by husnoo** [ashinn/chibi-scheme#881]
Hi,

I'm trying to wrap a C function with signature:
```
bool ImGui_Begin(const char* name, bool* p_open /* = NULL */, int flags /* = 0 */);
```

I've written a .stub:
```
(define-c boolean ImGui_Begin (string (pointer boolean) int))
```

but I'm getting errors compiling:
```
deps/chibi-scheme-static/clibs.c: In function ‘sexp_ImGui_Begin_stub’:
deps/chibi-scheme-static/clibs.c:10814:3: error: unknown type name ‘boolean’; did you mean ‘bool’?
10814 |   boolean tmp1;
      |   ^~~~~~~
      |   bool
In file included from deps/chibi-scheme-static/include/chibi/eval.h:12,
                 from deps/chibi-scheme-static/eval.c:5:
deps/chibi-scheme-static/clibs.c:10821:63: warning: passing argument 2 of ‘ImGui_Begin’ from incompatible pointer type [-Wincompatible-pointer-types]
10821 |   res = sexp_make_boolean(ImGui_Begin(sexp_string_data(arg0), &tmp1, sexp_sint_value(arg2)));
      |                                                               ^~~~~
      |                                                               |
      |                                                               int *
deps/chibi-scheme-static/include/chibi/sexp.h:927:32: note: in definition of macro ‘sexp_make_boolean’
  927 | #define sexp_make_boolean(x) ((x) ? SEXP_TRUE : SEXP_FALSE)
      |                                ^
In file included from deps/chibi-scheme-static/clibs.c:10774,
                 from deps/chibi-scheme-static/eval.c:1381:
deps/cimgui/cimgui.h:337:53: note: expected ‘_Bool *’ but argument is of type ‘int *’
  337 | CIMGUI_API bool ImGui_Begin(const char* name, bool* p_open /* = NULL */, ImGuiWindowFlags flags /* = 0 */);
      |                                                     ^
make: *** [Makefile:17: deps/chibi-scheme-static/eval.c.o] Error 1
```

The _Bool* comes from https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdbool.h.html

Any ideas?

I'm also not too sure how to use this approach in scheme - presumably
```
(define (do_something)
    (define (x #t))
    (ImGui_Begin "Another window" x 0)
    ...)
```

And then I can watch the value of x for changes? In other words, how do I create a boolean variable, pass a pointer to it to C code and change its value from C? Can this (define (x #t)) be made "static" as it works in C, i.e. even though the function is called multiple times, the same variable is used?

**Comment by ashinn** [comment]
The FFI tries to abstract away pointers, wrapping and unwrapping pointers on the C side so everything just looks like an object in Scheme.  You should be able to pass a boolean directly, but you can't pass NULL.  If you really need the NULL option you'd have to write a separate wrapper around that function.

Alternatively, if you always want to pass NULL you can do this by hard-coding the values:

`(define-c boolean ImGui_Begin (string (value NULL boolean*) (value 0 int)))`

Note if you're missing headers you can c-include them.

**Comment by husnoo** [comment]
Thank you, I've wrapped the two cases separately, the null v/s the bool. I'm having an issue with the bool:

```
bool nh_ImGui_Begin2(const char* name, sexp show, int flags) {
     // todo: unwrap the (sexp show) here and get the bool as a pointer
     //printf(\"show: %d\", sexp_unbox_boolean(show));
     bool* show_ = sexp_unbox_boolean(show);
     //*show_ = true;
     return ImGui_Begin(name, show_, flags);
}
```

Upon getting to the C code, I need a pointer to the boolean variable, which can then be set on the C-side. But the unbox gives me a pure value:

```
loki-fhs-chrootenv:nawal@heisenbug:~/data/Loki$ grep sexp_unbox_boolean -R deps/chibi-scheme-static/include/
deps/chibi-scheme-static/include/chibi/sexp.h:#define sexp_unbox_boolean(x) (((x) == SEXP_FALSE) ? 0 : 1)
```

Is it a bad idea to dig into the sexp and grab the pointer?

**Comment by ashinn** [comment]
Sorry, is the show_ parameter read/write, i.e. does ImGui_Begin periodically update it?

**Comment by husnoo** [comment]
> Sorry, is the show_ parameter read/write, i.e. does ImGui_Begin periodically update it?

Yes that's right, ImGui uses the same approach for text buffers, etc, you create a text box with a buffer as a parameter and it gets updated over time

**Comment by husnoo** [comment]
> That's a terrible API :)

It seems quite intuitive from a cursory glance, which is why I'm trying to wrap it for chibi-scheme...

> You'll have to make a wrapper type to pass in to the wrapper function

Hmm, I seem to be hitting the same issue (with extra steps)... 

ffi-example.sld:
```
(define-library (ffi-example)
  (export ImguiBool make-ImguiBool ImguiBool-get ImguiBool-set use_bool)
  (include-shared "ffi-example/ffi-example"))
```

ffi-example.stub:
```
(c-declare "

#include <stdio.h>
#include \"stdbool.h\"

struct ImguiBool {
  bool the_bool;
};


void use_bool(struct ImguiBool x) {
    printf(\"Hello use_bool!\");
    printf(\">>>>>Bool: -----%d-----\", x.the_bool);
    x.the_bool = !x.the_bool;
    printf(\">>>>>Bool: -----%d-----\", x.the_bool);
    fflush(stdout);
}


")

(define-c-struct ImguiBool
  constructor: (make-ImguiBool the_bool)
  (bool the_bool ImguiBool-get ImguiBool-set))

(define-c void (use_bool "use_bool") ((struct ImguiBool)))
```

In scheme:
```
(begin
    (define x (make-ImguiBool #f))
    (use_bool x)
    (ImguiBool-get x))
```
prints `#f` to the scheme output and `Hello use_bool!>>>>>Bool: -----0----->>>>>Bool: -----1-----obj1: #f` to the C output.
So the C-code has mutated the contents of the bool it is given at `use_bool`, but that's not what's getting seen by scheme in the next instruction.

Sorry this is my first time with trying to wrap stuff in scheme, and I seem to have chosen an interesting case :P

**Comment by husnoo** [comment]
Hmm, I've changed the function to accept a pointer:
```
void use_bool(struct ImguiBool* x) {
    printf(\"Hello use_bool!\");
    printf(\"pointer: %p\", x);
    fflush(stdout);
}
```

and adjusted the define-c:
```
(define-c void (use_bool "use_bool") ((pointer (struct ImguiBool))))
```

But the pointer is nil.
```
Hello use_bool!pointer: (nil)
```

The generated `.c` contains:
```
sexp sexp_use_bool_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! (sexp_pointerp(arg0) && (sexp_pointer_tag(arg0) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), arg0);
  res = ((use_bool(*(struct ImguiBool**)sexp_cpointer_value(arg0))), SEXP_VOID);
  return res;
}
```
Thank you for your help so far!

**Comment by husnoo** [comment]
Actually this works:
```
(define-c void (use_bool "use_bool") ((pointer ImguiBool)))
```

Somehow it wants a `(pointer ImguiBool)` instead of a `(pointer (struct ImguiBool))`!

Thank you so much!

**Comment by husnoo** [comment]
Actually there's a warning during compilation, and now I worry in case it's working for the wrong reasons (and thus might break when I move on to more complicated types than bool):

```
deps/chibi-scheme-static/clibs.c: In function ‘sexp_use_bool_stub’:
deps/chibi-scheme-static/clibs.c:10803:20: warning: passing argument 1 of ‘use_bool’ from incompatible pointer type [-Wincompatible-pointer-types]
10803 |   res = ((use_bool((struct ImguiBool**)sexp_cpointer_value(arg0))), SEXP_VOID);
deps/chibi-scheme-static/clibs.c:10781:33: note: expected ‘struct ImguiBool *’ but argument is of type ‘struct ImguiBool **’
10781 | void use_bool(struct ImguiBool* x) {
      |               ~~~~~~~~~~~~~~~~~~^
```

The generated .c looks like this:
```
sexp sexp_use_bool_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! (sexp_pointerp(arg0) && (sexp_pointer_tag(arg0) == sexp_unbox_fixnum(sexp_opcode_arg1_type(self)))))
    return sexp_type_exception(ctx, self, sexp_unbox_fixnum(sexp_opcode_arg1_type(self)), arg0);
  res = ((use_bool((struct ImguiBool**)sexp_cpointer_value(arg0))), SEXP_VOID);
  return res;
}
```

The double star does look very suspicious!

**Comment by husnoo** [comment]
If I manually change the ** to *, the warning goes away ......... and the code still works.

**Comment by ashinn** [comment]
Structs are implicitly passed by pointer.  Explicitly annotating `pointer` tells it to add the extra `*`.  You want just:

`(define-c void use-bool (ImguiBool))`

**Comment by husnoo** [comment]
Oh wow thanks! This now works as expected with the toy example. I will try it with ImGui later.
