### ISSUE TITLE
json-write cannot write null

### ISSUE THREAD

**Issue by Zambito1** [ashinn/chibi-scheme#893]
```scheme
> (eq? (if #f #f) (string->json "null"))
#t
> (json->string (string->json "null"))
ERROR in "json-write": unable to encode element: #<undef>
```

`json->string` (and the underlying `json-write`) should write the Scheme representation of the JSON null as `null`.

**Comment by lassik** [comment]
According to [our survey](https://docs.scheme.org/surveys/json-representations/) the most popular null representation is the symbol `'null`. This is also the one used by SRFI 180. Could Chibi follow this convention?

**Comment by ashinn** [comment]
The problem with the symbol `'null` is that `(chibi json)` converts objects to alists with symbol keys, and thus there's no way to differentiate between the key `"null"` and `null`.

**Comment by Zambito1** [comment]
@lassik Thanks for that survey! I bumped into this issue because I'm writing a portable abstraction over many JSON libraries. That gives me a few more to work on :D 

@ashinn Can't one distinguish between `'null` and `"null"` if it shows up as a value though? ie: the `cdr`s of an object alist, values in a JSON array, or a top level value like in the original issue.

I don't mind either representation. I just would like `(equal? "null (json->string (string->json "null")))`

**Comment by lassik** [comment]
JSON only supports string keys. So a `'null` key always corresponds to the string `"null"`.

The issue might have to be re-visited with other encodings that can have arbitrary objects as keys. Note also that lots of Scheme implementations do not have a `void` value.
