### ISSUE TITLE
Links to Chibi's home page

### ISSUE THREAD

**Issue by lassik** [ashinn/chibi-scheme#906]
The files in the `doc` directory use the following three URLs to link to Chibi's home page:

```
http://code.google.com/p/chibi-scheme/
http://synthcode.com/wiki/chibi-scheme/
https://github.com/ashinn/chibi-scheme/
```

Which is the preferred one?

**Comment by ashinn** [comment]
Googlecode is dead.  Maybe prefer the github link.
