### ISSUE TITLE
The website has outdated documentation.

### ISSUE THREAD

**Issue by ghost** [ashinn/chibi-scheme#911]
https://synthcode.com/scheme/chibi/

The manual there does not have `(chibi shell)`. 

Would it be possible to re-generate the documentation via CI?

Or maybe even have two branches, one for the most recent release, one for the master?

**Comment by ashinn** [comment]
Will release the next version soon and update the docs.  Let me think about a separate URL for HEAD.

**Comment by ashinn** [comment]
Fixed in bfb6b4bf822937f99298cf1a32fd1120c0a8e413.
