### ISSUE TITLE
make test-all fails at srfi-231

### ISSUE THREAD

**Issue by mbamac** [ashinn/chibi-scheme#921]
srfi-231: nonempty intervals and generalized arrays: 
        index-* and miscellaneous tests: ........................
        24 out of 24 (100.0%) tests passed in 0.001341104507446289 seconds.
        interval tests: .......................................................
         ...................
        74 out of 74 (100.0%) tests passed in 0.007714986801147461 seconds.
        basic: ................................................................
         .........................................................
        121 out of 121 (100.0%) tests passed in 0.015033960342407227 seconds.
        permutation tests: ...............error in group outside of tests
ERROR: vector-set!: index out of range
    #(#f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f)
    -5

        15 out of 16 (93.8%) tests passed in 0.002140045166015625 seconds.
        1 error (6.2%).
        intersect/scale/sample: .......................error in group outside of tests
ERROR: vector-set!: index out of range
    #((-7) (-6))
    -7

        23 out of 24 (95.8%) tests passed in 0.003165006637573242 seconds.
        1 error (4.2%).
        tile/reverse/flip: ..........error in group outside of tests
ERROR: vector-set!: index out of range
    #(#f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f)
    -25

        10 out of 11 (90.9%) tests passed in 0.0018138885498046875 seconds.
        1 error (9.1%).
        stack/block: .
        1 out of 1 (100.0%) test passed in 0.0008230209350585938 seconds.
        assign/product: ...............error in group outside of tests
ERROR in "s32vector-set!": assertion failed: (< -1 arg1 (uvector-length arg0))
    5
    1

        15 out of 16 (93.8%) tests passed in 0.0017960071563720703 seconds.
        1 error (6.2%).
        reshape tests: ...................................
        35 out of 35 (100.0%) tests passed in 0.01175999641418457 seconds.
        curry tests: .............
        13 out of 13 (100.0%) tests passed in 0.0022499561309814453 seconds.
        misc: ....
        4 out of 4 (100.0%) tests passed in 0.12896490097045898 seconds.
    335 out of 339 (98.8%) tests passed in 0.17756915092468262 seconds.
    4 errors (1.2%).

**Comment by ashinn** [comment]
Thanks, I can reproduce, let me take a look.

**Comment by gambiteer** [comment]
These failures are gone now.
