### ISSUE TITLE
Can we add http-send-file into export?

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [ashinn/chibi-scheme#927]
It would make my life easier to create simple blog engine without servlet additional logic. Just serving html's with images and js'es. 

https://github.com/ashinn/chibi-scheme/blob/67fdb283b667c8f340a5dc7259eaf44825bc90bc/lib/chibi/net/http-server.scm#L142

**Comment by ashinn** [comment]
Sure.  Note the underlying `send-file` system call comes from `(chibi io)`.
