### ISSUE TITLE
equal? from (scheme base) not halting when it should

### ISSUE THREAD

**Issue by sham1** [ashinn/chibi-scheme#929]
Earlier today, I noticed a bug when I inputted the following forms in the REPL:

```scheme
(import (scheme base))
(equal? '#1=(#1# . #1#) '#2=(#2# . #2#))
```

Instead of this halting as expected and required by R7RS, it instead goes into an infinite loop.

**Comment by ashinn** [comment]
This isn't related to `equal?`, it's the compiler not supporting raw cyclic literals in the source:

This hangs as well:

```
((lambda (a b) #t) '#1=(#1# . #1#) '#2=(#2# . #2#))
```

and supporting that is a very low priority.  This, however, currently gives me a segfault:

```
 (let ((a (cons 1 2)) (b (cons 3 4)))
  (set-car! a a)
  (set-cdr! a a)
  (set-car! b b)
  (set-cdr! b b)
  (equal? a b))
```

will take a look.
