### ISSUE TITLE
Compare complex numbers

### ISSUE THREAD

**Issue by lassik** [ashinn/chibi-scheme#934]
```
> (< -3-4i 0)
#f

> (< 0 -3-4i)
#f

> (< -3-4i -3-4i)
ERROR on line X: invalid type, expected Number: -3-4i

> (< 0 -3-4i -3-4i)
ERROR on line X: invalid type, expected Number: -3-4i
```

R7RS says `< <= > >=` are only defined for real numbers. `=` is defined for all numbers.

**Comment by lassik** [comment]
cc @jpellegrini

**Comment by jpellegrini** [comment]
Perhaps also Chibi could either produce an error or compute the norm of the number when `abs` is applied to a complex argument?
https://docs.scheme.org/surveys/complex-abs/
