### ISSUE TITLE
Regex that should work just doesn't

### ISSUE THREAD

**Issue by exoess** [ashinn/chibi-scheme#952]
this is my code
```scheme
(regexp-replace-all '("#{1}\\s?([^\\n]+)") markdown "<h1>\\1</h1>")
```
but all i get out is like `<h1>\1</h1> Hello, world!`, am i doing something wrong or is it a problem with chibi?
(if you're wondering, i'm making a markdown to html parser)

**Comment by ashinn** [comment]
The syntax may look like that in other languages, but Chibi uses [SRFI 115](https://srfi.schemers.org/srfi-115/srfi-115.html) SREs:

```scheme
(regexp-replace-all
  '(: "#{1}" (* space) ($ (~ space) (+ nonl)))
  "#{1} Hello world"
  '("<h1>" 1 "</h1>"))
=> "<h1>Hello world</h1>"
```
