### ISSUE TITLE
0.11?

### ISSUE THREAD

**Issue by welcome-linja** [ashinn/chibi-scheme#967]
What is the release plan? I can see there have been many fixes and additions since 0.10, and it would be good to get those in repos.

**Comment by ashinn** [comment]
The plan is to release 0.11 in the near future (a week or so), hence the recent activity.

**Comment by welcome-linja** [comment]
Whooh. I'm psychic.

(I'll close this when it comes out.)

**Comment by ashinn** [comment]
Tagged and released.
