### ISSUE TITLE
0.11 commit DETACHED from master??

### ISSUE THREAD

**Issue by welcome-linja** [ashinn/chibi-scheme#989]
The 0.11 tag is apparently not referenced from any branch? At least that's what GitHub and my local Git installation says. That is _very_ strange and I'm guessing a mistake.

**Comment by ashinn** [comment]
It seems it doesn't like when I push a tag by itself without any new commits?

The tag was on the correct commit, there was nothing wrong with it.
Pushing a new, unrelated commit seems to have resolved that it's in master.

**Comment by welcome-linja** [comment]
Bizarre.
